### ISSUE TITLE
Suggestion: Towny Banning / Towny Outlaws

### ISSUE THREAD

**Issue by LlmDl** [LlmDl/Towny#1936]
Originally reported on Google Code with ID 1912

```
Hello. So i play on a server that has towny, and i've recently come across the fact
that you can't ban players specifically from just a town. Now, i like my town to be
(Open) but when a player does something and i want him out of my town he's able to
rejoin. And i don't want to make my town not (Open) because it's just silly to have
to do that for one person. Is there any way you guys would add a /t ban <name> command
for 1.7.2? I know you guys are quite busy but honestly this would be quite a resourceful
command. Perms would be able to be toggled in the config files and stuff like that.
I just feel like this would be a great new addition to your amazing plugin. Please
take this suggestion into consideration! :D



```

Reported by `Nathangrott` on 2013-12-03 19:26:04

**Comment by masternetra** [comment]
I support this! As a suggestion. Perhaps Mayors and Assistants could ban players /t Ban <name> (and /t unban) doing so could send and keep banned players outside the town via invisable barrier like thing and prevent them from using /t spawn to the city. Any non-towny tp in would be meet with a immediate tp to outside the town (nearest block) or instant death via high value dmg dealt (e.g. 10,000 dmg or whatever) whenever they move. The Ban would be negated if the town is at war with the town the banned person is part of.

**Comment by LlmDl** [comment]
I don't want to start monitoring every movement of every player just to check if they've moved into a town that doesn't like them. Towny will never disallow a player to walk somewhere, its up to the town or plot owner to build walls if they don't want people getting in.

**Comment by masternetra** [comment]
What about being able to jail them if they in town?

**Comment by LlmDl** [comment]
Also requires checking every player's movement constantly. If the player is an enemy of that town, someone in the town can kill them, which will send them to jail.

**Comment by masternetra** [comment]
Well no not constantly just when the command is issued do the check?

**Comment by masternetra** [comment]
Also walls are not very useful when the person is using enderpearls to tp.

**Comment by LlmDl** [comment]
There's plenty of work-arounds for enderpearls, they can be placed in the Towny itemuse id list, or the town can just make a 25 block tall wall, or you can get all kinds of plugins that change how they behave. The issue ticket you're posting in is for a ban list for towns which have Open status enabled, because they want to allow anyone to join but they don't want to have to deal with people they've already kicked out.

**Comment by masternetra** [comment]
Would itemuse actually prevent them from using it to TP in from outside the town?

**Comment by LlmDl** [comment]
Only if you disallow that itemuse of EPs in the wilderness via permission nodes. But which towns put their walls right up against the border of the wilderness anyways?

**Comment by masternetra** [comment]
Ones who forgot to keep such things into account when the wall was built. >.<

**Comment by LlmDl** [comment]
Work completed so far (probably a fair bit of stuff in the backend that needs to be tested) :
```
    - New Command: /town outlaw [add/remove] [name]
      - Requires permission node towny.command.town.outlaw
      - Outlaws can be any player who is not a resident of the town.
      - Open towns can declare people outlaws to keep them from rejoining.
    - New Command: /town outlawlist {town}
      - Requires no permission node to use.
      - View outlaws of your town, or for other towns when the optional {town} is added to the command.

```

**Comment by LlmDl** [comment]
Work completed:
```
    - New Command: /town outlaw [add/remove] [name]
      - Requires permission node towny.command.town.outlaw
      - Outlaws can be any player.
        - They do not need to be a member of a nation or a town.
      	- If you outlaw a member of your town, they are automatically kicked from the town.
        - Open towns can declare people outlaws to keep them from rejoining.
        - When you kill an outlaw in your town, they are sent to your jail if you have a jail
          - Requires jail.is_jailing_attacking_outlaws set to be true in your config.yml
          - Also requires the towny.outlaw.jailer permission node.
          - Outlaws can escape from jail in the usual ways:
            - Pay bail, escape into the wilderness, being let go via /t toggle jail command.
            - Outlaws are not freed by using /t leave.
	- New Permission Node: towny.outlaw.jailer
	  - Required to cause outlaws killed in your town to be sent to your jail.
	  - Newly made Townyperms.yml files will have this node given to mayors, assistants and sheriffs by default.
	    - Add this node to those ranks to properly make use of the isJailingAttackingOutlaws.
	    - Add it to the default town rank if you want anyone in town to be able to jail outlaws killed in town.
    - New Command: /town outlawlist {town}
      - Requires no permission node to use.
      - View outlaws of your town, or for other towns when the optional {town} is added to the command.
```

**Comment by LlmDl** [comment]
The feature is now complete. Hopefully there will be some good suggestions to come.
