### ISSUE TITLE
Town bank statement

### ISSUE THREAD

**Issue by LlmDl** [LlmDl/Towny#1955]
Originally reported on Google Code with ID 1931

```
A command for town mayors to monitor town bank activity.  Would show recent transactions
including withdrawals, deposits, and land claims.  Would state the amount and player
responsible.  Even the last 10 transactions would be helpful.  

Example:
/t bank log

Town name : Current balance
$50 deposited by Steve
$100 withdrawn by Herobrine
$250 withdrawn by Player1 (tclaim)

This would be extremely helpful to town mayors for tracking and monitoring all town
bank activity.  





```

Reported by `jimdunnet84` on 2013-12-24 00:22:05

**Comment by JohOply** [comment]
Is this feature scheduled? :)

**Comment by LlmDl** [comment]
It's on the list because its a good idea, it could also potentially piggy-back off the existing money.csv that Towny makes in the towny\logs folder. 

It's not currently being worked on however.

**Comment by LlmDl** [comment]
https://github.com/LlmDl/Towny/issues/2670 Closing this older ticket in favour of the newer one created by a user (and not auto-generated from our old ticket site on google code.)
