### ISSUE TITLE
Disabling Claiming of Regenerating Plots

### ISSUE THREAD

**Issue by LlmDl** [LlmDl/Towny#1981]
Originally reported on Google Code with ID 1958

```
When a chunk has been unclaimed in a world with plot regeneration enabled, it will stop
regenerating and will have its pre-claim setup reset.

A simple way to get around this would be to disable the ability to claim a chunk in
mid-regeneration.
```

Reported by `dannycaller` on 2014-02-06 20:46:21

**Comment by Articdive** [comment]
This won't be implemented into Towny:
What if you accidentally unclaim a chunk in your town, or it falls to lack of payment, you watch the whole thing (your town) disappear and you are unable to stop the regeneration.
