### ISSUE TITLE
Towny Chat Crash 1.8.8

### ISSUE THREAD

**Issue by johndcastro** [LlmDl/Towny#2372]
What steps will reproduce the problem?
1. Upon startup of the server and any chat in any channel and the crash will happen

What is your Towny version number? : 0.89.2.28

What is your TownyChat version number? : 0.45

What is your Bukkit version number? : 1.8.8

What operating system? : CentOS

Please use pastebin.com to link the following files:
- Your full server startup from server.log,
http://pastebin.com/Gc0Wts3n
That is the crash after the chat log

In the case of chat-issues please link your:
- Chatconfig.yml
http://pastebin.com/Rr5k26Ra

- Channels.yml
http://pastebin.com/jxtQ2LYL

Skipping these files is not an option. It is the easiest way to diagnose an
issue ticket properly. If you do skip this step then your ticket will most
likely be deleted and you will be asked to resubmit.

So the issue I am getting is update with Towny when trying to do a chat command I immediately get a crash every time.  Thanks for the help.

**Comment by LlmDl** [comment]
I'm going to need to see a full startup on pastebin.com.

Did this issue beginning coincide with you adding [titleprefix] and [titlesuffix] to the channel_format lines in the chatconfig.yml?

**Comment by johndcastro** [comment]
Entire log: http://pastebin.com/9yNzn0qJ

So we are upgrading from 1.8.3 so didn't change anything just updated from 0.84 towny to latest version of towny and towny chat (though towny chat is the same) a few other plugins updated and spigot to 1.8.8.  Nothing else new nothing else changed.  Works in 1.8.3 with 0.84 haven't tried 1.8.3 with latest towny yet

**Comment by LlmDl** [comment]
Does/did the [titleprefix] and [titlesuffix]  tags work?

**Comment by johndcastro** [comment]
In the channel format you mean in ChatConfig.yml?  Yeah it worked in the past.  Should it be {titleprefix} {titlesuffix}?  We use dstitle

**Comment by LlmDl** [comment]
Well it's not likely to be the cause then. You're the first person to have this issue, meaning its probably not towny. You'll probably want to check if its another plugin, by removing half your plugins and retesting. 

If that works then add back those removed plugin half-at-a-time until it starts again. 

If that doesn't work continue to remove half your plugins.

**Comment by johndcastro** [comment]
Alright let me check it out and see what happens.  Do you know if anybody has run on 1.8.8 yet?

**Comment by LlmDl** [comment]
afaik its been run on 1.8.8 just fine.

**Comment by johndcastro** [comment]
Well that didn't take long :)  Denizen was the culprit.  I will let them know.

**Comment by LlmDl** [comment]
Alright, thanks for using a proper form to submit, Good luck on receiving a timely update.
