### ISSUE TITLE
The /home command can be executed from a jail

### ISSUE THREAD

**Issue by doitliketyler** [LlmDl/Towny#2379]
I use UltimateCore instead of Essentials and when a player is jailed they can escape using the /home command. I'm on a Spigot server using 1.8.8

**Comment by LlmDl** [comment]
UltimateCore must be executing their teleport at the wrong priority, can you link me the source code of that plugin?

**Comment by doitliketyler** [comment]
Definitely. Here you go https://github.com/Bammerbom/UltimateCore

**Comment by LlmDl** [comment]
Looked at it but I can't see why its not being canceled. We are canceling the teleport event at normal priority, ignore whether it is being canceled.

https://github.com/LlmDl/Towny/blob/master/src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java#L586

**Comment by doitliketyler** [comment]
Hmm...I can share the issue with the other dev. Maybe you guys can figure it out together?

**Comment by doitliketyler** [comment]
I created a ticket for UltimateCore and am just waiting on his feedback.

**Comment by Bammerbom** [comment]
Does towny have a jail command?

**Comment by TheAsher** [comment]
You can disable command disabling in the config.yml file... maybe that you haven't disabled commands in the config.

**Comment by doitliketyler** [comment]
Can you please respond to @Bammerbom so the problem can be fixed?

**Comment by LlmDl** [comment]
@Bammerbom, the players can be jailed via other way besides the command, but mayors can jail their residents using /resident jail {name}
