### ISSUE TITLE
got this error

### ISSUE THREAD

**Issue by noorkoteb** [LlmDl/Towny#2380]
http://pastebin.com/zKAxts0r had an issue with some towns banks being reset after doing a reload, and those towns fell after awhile of tweaking i was able to get towny back up, but towny chat wasn't working

**Comment by LlmDl** [comment]
Stop your server. Start your server, let it load completely, then stop it. A new latest.log will be created in your logs folder. Please upload it to http://pastie.org or http://pastebin.com and post the link.

**Comment by noorkoteb** [comment]
http://pastebin.com/ZdmiheJR sorry for my late response

**Comment by LlmDl** [comment]
This is a known issue in essentials eco. You can't do anything aside from changing economy plugins. Craftconomy3 seems to be the best route to go.
