### ISSUE TITLE
Towny Colors

### ISSUE THREAD

**Issue by doitliketyler** [LlmDl/Towny#2381]
I searched everywhere before asking this to see if it had been answered previously but with no luck. I'd love more control over the colors and the ability to customize these headers:

.o0o.__________________.[Town (PVP) ].__________________.o0o.

Any chance of adding that into the english.yml so I can apply my servers theme to Towny?

**Comment by LlmDl** [comment]
The gold is the Towny theme, I don't think we'll be making this editable as that is Towny's look.
