### ISSUE TITLE
Towny config.yml reverts - No Bypass

### ISSUE THREAD

**Issue by RogueAvenger** [LlmDl/Towny#2382]
I have been searching the internet for hours on end, trying to find a solution. The only solution that's available is to set bypass_version_check: false. There is no bypass_version_check: in the entire config file. I'm using the newest craftbukkit, and the newest towny release. Any other question I've found has been marked invalid, or something like that, and no help was given. All I want to do is change the config.yml, and not have towny revert it back to the default config. I have tried both spigot, and craftbukkit, and both do the exact same thing.

Also, any explanation as to why bypass_version_check: was removed would be great. I don't see the logic behind that.

**Comment by LlmDl** [comment]
You don't need to bypass the version check because it was removed. There is not longer a proper craftbukkit number to check against, only spigot version numbers.

If you're running a version without the version check then its assumed you're running a 1.8 version of spigot or craftbukkit, which is fine.

**Comment by RogueAvenger** [comment]
It still reverts with 1.8 craftbukkit and 1.8 spigot.

**Comment by LlmDl** [comment]
I don't know what you mean by reverts. The version check has done nothing for a year or two, so even if you see that message, it doesn't matter. If you were using the later dev builds it would not show, as its removed. 

If you want further assistance, or make another ticket in the future please begin by pastebin.com'ing your full server startup and linking it here.

**Comment by RogueAvenger** [comment]
What I mean by revert is that the configuration file returns to the default after any changes whatsoever.

**Comment by LlmDl** [comment]
That's a completely separate issue. Please start a new ticket and pastebin.com your full server startup, your config and explain what program you use to edit the config.
