### ISSUE TITLE
Reverting Config

### ISSUE THREAD

**Issue by RogueAvenger** [LlmDl/Towny#2383]
In my previous post, I stated that the config was reverting (going back to the default config) upon startup. I further explained the issue in different words, and you claimed it was a completely seperate issue. I'll keep this as simple as possible.

Spigot version: 1.8
Towny version: 0.89.2.0 (Newest release, apparently compatible with 1.8 spigot)

What happens:
- installed the plugin.
- while my server was offline, I made adjustments to config.yml in notepad++.
- I saved changes.
- I ran the server.
- config.yml was changed back to the default. (In other words, the config.yml changed back to the default config.yml even after it was saved.)

The plugin works, but ONLY the config.yml changes back to the default. All other configuration files retain, or keep changes made to them.

As requested: http://pastebin.com/EiY0gRxF

It says Towny can not read the version of Craftbukkit, but I'm using Spigot 1.8.

**Comment by LlmDl** [comment]
Could you include the config, after you've made the edits and before you upload it to the server.

**Comment by RogueAvenger** [comment]
http://pastebin.com/jzfMTUFd

**Comment by LlmDl** [comment]
Well your config shouldn't have double-spaces everywhere. That might be why its reverting.

Update to the latest dev build 0.89.2.28, delete your current config.yml, and start the server up. 

Dev build is here: http://towny.palmergames.com/?p=687

Changelog is here: http://towny.palmergames.com/?p=576

**Comment by RogueAvenger** [comment]
With the latest dev build, the config kept the changes. Thank you.

As for the double spaces everywhere, I don't know why it was like that; the default config was in the same format when I first started the server.

**Comment by LlmDl** [comment]
Alright, I'll close this now, thanks.
