### ISSUE TITLE
[Suggestion] - /plot Info

### ISSUE THREAD

**Issue by masternetra** [LlmDl/Towny#2387]
It's not always easy to remember the details of specific plots (what you have toggled for it and such) and I think there should be a /plot info or something of that nature to reveal all the details about the plot your on (The Owner, the type, what's toggled, etc).

**Comment by LlmDl** [comment]
You can do /plot perm for that, in a coming dev build (probably 0.90.0.1) we have a new '/plot perm hud' using MC scoreboards. It's very nice and updates as you move as well as being always on.
