### ISSUE TITLE
[Suggestion] - Another Plotborder toggle option

### ISSUE THREAD

**Issue by masternetra** [LlmDl/Towny#2388]
Would like to suggest "Always On" option when toggling the plotborder option (Off,On, Always On -  cycling), When working on plots I find the effects quickly disappearing while working on a plot to be a bit problematic, having to leave and and come back on to the plot to get the borders again. Granted it's still better then not having it period, being able to keep it on would be very helpful.

**Comment by LlmDl** [comment]
This might come be in 1.9, as particles are no longer entities and do not lag anyone.

**Comment by LlmDl** [comment]
Part of Towny 0.91.4.10, using /res toggle constantplotborder
