### ISSUE TITLE
Custom language file overwrited (french)

### ISSUE THREAD

**Issue by MrMaleficus** [LlmDl/Towny#2389]
Hello LlmDl and ElgarL :)

Firstly thank you for your work about towny, a great plugin for all RPG server.
I open an issue because when i rewrite the current language file for my language, (the french) any modification are undo by set the old english language file :(
I've tried everything, set the name to french.yml, english-custom.yml etc...
The file is always replaced, and the only way i've found to make my language work, is to replace the internal english.yml in the jars with the all the french words.
Unfortunalety all the specials characters related to the french langage (like "à" "é" "è" "ô" etc) are replaced with "?" symbols in the output language file :(

Please guys, can you help me and the french community ? I can make a pull request to create the official french.yml file if you want after that ! :)

Thank you !
MM

**Comment by LlmDl** [comment]
We're always game for new language files, you can PR it or just send me it via pastebin.com and link it here.

As for the accented characters, make sure you're using the same encoding as the other language files. I'm pretty sure that the spanish files have them working.

**Comment by LlmDl** [comment]
The overwriting may be caused by the version number being behind the current version.

**Comment by LlmDl** [comment]
Looking at this, I'm sure this doesn't happen anymore if the version numbers are good, the file name is something that towny doesn't come with. Special characters are also working.
