### ISSUE TITLE
Display towny prefix/suffix in plot notifications.

### ISSUE THREAD

**Issue by TheBrianiac** [LlmDl/Towny#2390]
Currently, setting a player's title via /nation set title <name> <title> does very little if you aren't running TownyChat. The feature would be more useful if:
- Titles were shown when you walk into somebody's plot ("Player's plot" vs "Title Player's plot").
- Titles were shown in the town and resident profiles (/town, /resident).

It's not a large addition, but it'd be a nice one.

**Comment by LlmDl** [comment]
This is now a thing as of 0.92.0.2
```
    - New Config Option: notification.owner_shows_nation_title
      - default: false
      - If the notification.owner option should show name or {title} name. Titles are the ones granted by nation kings.
```
