### ISSUE TITLE
Display "Potential tax income from plots" in the /town stats.

### ISSUE THREAD

**Issue by MonkeysLP** [LlmDl/Towny#2391]
It would calculate the ideal, maximal amount of taxes that could be earned depending on how many plots are currently sold to residents and how much the taxes are, assuming all residents had enough money to pay them.

Or at least, display the amount of shop, embassy, default, etc.. plots that are currently not owned by the town and pay taxes.

Thanks!

**Comment by LlmDl** [comment]
Hey its been a while but this is now a thing:

0.91.4.7:
    - New Command: /town plots {townname}
      - Screen displays number of Town-owned plots, number of claimed/available claims.
      - Displays numbers of different plot types (ex: farms, jails)
      - Displays detailed stats on Embassies, Shops and Residential plots which includes:
        - Number owned by residents,
        - Number currently for sale, 
        - Number in town,
        - Estimated revenue from different types of plot tax.
      - Optional {towname} to look up plot type information for other towns.
      - Command uses towny.command.town.plots permission node.
