### ISSUE TITLE
[Towny] Task #74590 for Towny v0.90.0.0 generated an exception

### ISSUE THREAD

**Issue by AdminZero** [LlmDl/Towny#2400]
Got this error in my console logs not sure what caused it but hopefully you can use it to fix something.

http://pastebin.com/taCzzVTZ

Thanks

**Comment by AdminZero** [comment]
Okay so i went though the logs and tracked down when it first started... http://pastebin.com/Qah59B1A

Seem it got stuck trying when this happened "[16:23:50] [Server thread/INFO]: [Essentials] Found new UUID for Ender_Dude_95. Replacing 5ad9a85b-1449-3b91-9e6e-70cbc0209e2c with be626349-c0b5-493a-b6b8-f3c388c6ec80"

Shortly before this error i ran and /ess cleanup 0 1 1 command and then /essentials reload command

Hope this helps resolve this issue.

**Comment by LlmDl** [comment]
Pastebin.com your full startup please.
