### ISSUE TITLE
Unable to build Towny from source

### ISSUE THREAD

**Issue by Zbob750** [LlmDl/Towny#2401]
Hi, it is no longer possible to build from source using ant.
The issue appears to be that your site no longer hosts the dependencies it once did.
https://github.com/LlmDl/Towny/blob/master/build.xml#L19-L29

I have not made a PR to resolve this because I'm unaware how you'd prefer this fixed.

**Comment by LlmDl** [comment]
Thanks for pointing this out. I'll look into it

**Comment by LlmDl** [comment]
Rehosted and updated the source.
