### ISSUE TITLE
[Suggestion] Towns owned by users who have changed names fix

### ISSUE THREAD

**Issue by TRMayhem** [LlmDl/Towny#2405]
Currently if a player changes their name, they lose rights and access to the town that they created. My idea is to stop storing the owner/resident's name as whether or not the person owns/lives in that town, and replace it with their minecraft UUID, since those never change.

**Comment by LlmDl** [comment]
You need to update to teh latest release 0.90.0.0 and use the included townynameupdater. We will not be using UUIDs in the database as that would make it unreadable by humans.
