### ISSUE TITLE
Towny 0.9 upgared removed all firespread restrcitions 

### ISSUE THREAD

**Issue by hmmcrunchy** [LlmDl/Towny#2406]
Yea :) bit of a disaster.. upgrade from 0.88 to the new 0.90 seemed to go ok, but the plot toggle fire restriction all seemed to disappear

I did not have force world  fire spread on- and toggling plot firespread did nothing to abate the firestorm 

had to revert back to 0.88 which contains fire ok

thanks for continuing this utterly epic plugin :)

**Comment by hmmcrunchy** [comment]
forgot to say this is using MySQL database

**Comment by LlmDl** [comment]
I haven't seen anything like this reported. It's probably not a bug in Towny.

Please pastebin.com teh following files:

1) The full startup from teh latest.log
2) The config.yml
3) The mysql equivalent of the towny\data\worlds\WORLDNAME.txt file

**Comment by hmmcrunchy** [comment]
Hi I've done a bit more experimenting it may be due to me using the new towny version in a 1.8.1 server not 1.8.8? 

Seems to be ok on test server

**Comment by LlmDl** [comment]
As the page for that version of Towny clearly states, it is for MC 1.8.3 and up.
