### ISSUE TITLE
Not enabled characters in town names ect.

### ISSUE THREAD

**Issue by Szikszai60** [LlmDl/Towny#2408]
Hi! I started a Towny server and everything is fine, but:
The hungarian alphabet contains some characters that are not allowed to use in town names ect. (like: á,é,í,ó,ö,ő,ú,ü,ű)
This issue caused many problems, because we use these characters many times.
Can you add these characters?

**Comment by morfie78** [comment]
While we are at it, can we make it so you can use an aposrophe (') in the town board?

**Comment by Szikszai60** [comment]
I solved for myself. 
I just added manually in the config file.
regex:
    name_filter_regex: '[ /]'
    name_check_regex: ^[a-zA-ZáéíóöőúüűÁÉÍÓÖŐÚÜŰ0-9._\[\]-]*$
    string_check_regex: ^[a-zA-ZáéíóöőúüűÁÉÍÓÖŐÚÜŰ0-9\s._\[\]-]*$
    name_remove_regex: '[^a-zA-ZáéíóöőúüűÁÉÍÓÖŐÚÜŰ0-9._\[\]-]'
