### ISSUE TITLE
Option to limit plots for town ranks?

### ISSUE THREAD

**Issue by Nesseley** [LlmDl/Towny#2409]
Hey!
I'd like to have an option to give a persmission to limit a player from claiming more than 1 plot.
So that he needs to get ranked up by the town owner before he can claim more.

I can't seem to find a way to do this, other then giving permisions to a group in permissionEx, but this way the town owner has no controll over how many plots a resident can claim.

I'd like to give (as an example) - towny.plot.limit.1 to a town rank.

I hope you can help me with this, or if it's already implemented please tell me so! :)
Thanks in advance, from a dedicated Towny user.

**Comment by LlmDl** [comment]
Already exists: http://palmergames.com/towny/towny-permission-nodes/#Info/Option_Nodes

The towny_maxplots info/options node.
