### ISSUE TITLE
Cannot unclaim numerous townblocks at one time

### ISSUE THREAD

**Issue by coolsurdy** [LlmDl/Towny#2410]
Hello,

Whenever a player uses /t delete and if their town contains over 1000 townblocks, the server will crash because of all the townblocks becoming unclaimed. When the server comes back up, the townblocks are glitched and say they are already claimed when you try to claim them, but on towny map they do not show up and perms are as if it is Wilderness. 

Please fix this issue I am on Spigot 1.8.8 (stable version) and using Towny 0.89.2. I tried using Towny 0.90 and it still persists.

Also can you tell me how to fix these glitched townblocks? Thanks.

**Comment by LlmDl** [comment]
Does your world still have teh revert on unclaim feature enabled? If so your server may not be powerful enough to handle the reverting of so many townblocks.

**Comment by coolsurdy** [comment]
No. No blocks are reverted.

**Comment by LlmDl** [comment]
Stop your server. Start your server, let it load completely, then stop it. A new latest.log will be created in your logs folder. Please upload it to http://pastie.org or http://pastebin.com and post the link here.

**Comment by coolsurdy** [comment]
ALSO most important. Is there any way to fix the glitched townblocks? They display nobody owns the town when you walk on them no town enter alert in chat, /towny map displays nothing, "/t here" says no town exists but when you try to claim it says a town is already claimed there. Is there any way to fix it? I know I have to go into the folders but which ones, and what should I do. Thanks

And here is the pastebin:
http://pastebin.com/qBxjeVg1

**Comment by LlmDl** [comment]
Glitched townblocks sounds like someone deleted a town manually from the database, instead of doing it via the ingame commands. This made it so that there are still townblocks listed in the \towny\data\townblocks.txt and towny\data\townblocks\ folder. If the town was deleted via ingame commands then perhaps the server isn't capable of handling such a large amount of database changes, in the future if a large town wants to delete itself: try unclaiming it in smaller parts, then delete it.

**Comment by coolsurdy** [comment]
it was deleted via ingame commands.

also what would happen if I just reset the /towny/data/townblocks and or
townblocks.txt? is that the right way to do it, or is there another method?
there are at least 100s of townblocks stuck this in this state on my sever

**Comment by LlmDl** [comment]
You don't want to reset teh files or it will screw up every other town too. If you are having a hard time fixing it manually you can always go back to a backup that towny made, then try deleting the town again after you unclaim the town using smaller batches.
