### ISSUE TITLE
Explosions regenerate?

### ISSUE THREAD

**Issue by KingGuineaSquid** [LlmDl/Towny#2411]
I run a small bukkit server and I have noticed that explosions regenerate. I had some tech support help and they can't figure out what is wrong. I have sent you the config file so you can review it and hopefully help me out (It was a YML file, not ttxt but I had to change it to send it).
[config.txt](https://github.com/LlmDl/Towny/files/76663/config.txt)

**Comment by LlmDl** [comment]
if you dont want explosions to regenerate in teh wilderness use the '/tw toggle revertexpl' command in each world you want it off in.
