### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Superola86** [LlmDl/Towny#2412]
A setting suggestion for the config:

"Only use TownTax if resident owns a plot: true/false"

If the resident dont own a plot he/she will not pay taxes at al to the town.
Makes mayor not to invite a bouch of people just to collect taxes.

I know there is "plot taxes" but you cant use % taxes there.
Would be good to set a default tax for like 10% no matter how many plots you own.

**Comment by LlmDl** [comment]
There's already a plottax, strictly for players that own land. Perhaps you want to limit mayors' use of TownTax and only allow them to use the plottax.
