### ISSUE TITLE
[Suggestion] New Towny Plot {Farm}

### ISSUE THREAD

**Issue by kzaqul** [LlmDl/Towny#2414]
You Have Normal, Wilds, Embassy, Shop, but if I'm to understand correctly the ability to kill an animal in town is based on being able to destroy in that plot, but i don't want to set a plot perm as resident destroy as they can grief the plot, so i propose we do away with the wilds plot and replace it with farming, which would allow residents to destroy crops/ replant then, kill animals, harvest trees but not destroy anything else including mining within that plot (mining would be point less for after some time the chunk wouldn't have anymore resources. (some of which the wilds plot already does)

**Comment by morfie78** [comment]
This is a great idea!

**Comment by DragaoNimhe** [comment]
I love this idea! Would solve so many issues, towny permissions are tricky to work with, especially for young players. Being able to simply /plot set farm would be invaluable!!!

**Comment by Monkey0x9** [comment]
I would also like to see this feature added!

**Comment by LigerXT5** [comment]
Yes please. I've been having to set up worldgaurd areas for towns just for this reason.

**Comment by LlmDl** [comment]
You'll see this in the upcoming 0.91.0.3 dev build, courtesy of AndrewYunt.
