### ISSUE TITLE
Error using 0.90.0.1 new war mode. Ending war, turning off war hud. War Stats spam.

### ISSUE THREAD

**Issue by Kainzo** [LlmDl/Towny#2416]
Please note that there started TWO nations... and one of them midway through the war paid for neutrality.... now there's spam and errors.

https://puu.sh/mpxfk/f0e0062763.png
https://www.irccloud.com/pastebin/zWulEhq7/

**Comment by LlmDl** [comment]
http://i.imgur.com/nbrsMyq.png

Happened again.

**Comment by LlmDl** [comment]
Fixed in 0.91.0.1

**Comment by Kainzo** [comment]
Swwet!
