### ISSUE TITLE
[Suggestion] Anti-Slimeblock Griefing

### ISSUE THREAD

**Issue by starwarsmace** [LlmDl/Towny#2417]
I am player on a server Meepcraft(towny server) and one thing that I found out is that slime blocks were "nerfed" because they could be used to grief. The "Griefer" can use a piston and slime block to grab a block from another persons plot or unleash his flying machine to wreck houses and towns.

What I propose is that you have an anti-griefing for slime-block contraptions. Basically, you can check(on the event of a piston extending) whether the slime block or other blocks attached to it, will go outside of the plot bounds or into the wild.

I'm suggesting this so that we at Meepcraft, can finally use slime blocks for awesome uses and not worry about the griefers that could potentiality use it them for their malicious uses .

**Comment by TheUnkown675** [comment]
Agreed, better than what I said XD

**Comment by LlmDl** [comment]
Added this, you'll see it come out as part of 0.90.0.1, which should be available soon (TM), 

Join the Towny IRC and ask for me if you want a preview build of it.
