### ISSUE TITLE
[Suggestion] Custom plot type

### ISSUE THREAD

**Issue by Spooky4672** [LlmDl/Towny#2418]
Is it possible to create new plot type with defined rules in config.
If not could you implement it ? Also maybe I can help to do it
Thanks

**Comment by LlmDl** [comment]
If you're serious about helping join the Towny IRC, there's already an existing suggestion ticket for this sort of thing, it just needs to be implemented.

**Comment by Spooky4672** [comment]
How can I contact you ?

**Comment by LlmDl** [comment]
http://webchat.esper.net/?channels=towny
The Towny IRC
