### ISSUE TITLE
1.7.10 Towny & Quarries not working?

### ISSUE THREAD

**Issue by djoveryde** [LlmDl/Towny#2420]
I have just installed towny and im finding that Quarries will not break blocks. It tries to then flickers and moves on failing to break the block.

If i remove towny it works fine.

Any ideas?

**Comment by LlmDl** [comment]
I don't know enough about your mod or your server but in general if you want to have mods work with a bukkit plugin like towny you need to create a fakeplayer in your permission plugin for your mods machines.

Nothing I can do on my end, your mod doesn't directly support Bukkit plugins.

**Comment by djoveryde** [comment]
The mod in question is BuildCraft from the Tekkit Legends modpack
