### ISSUE TITLE
1.7.10 Towny & Quarries not working?

### ISSUE THREAD

**Issue by djoveryde** [LlmDl/Towny#2421]
Appologies for not giving enough information last time. 
Basically I am running the Tekkit Legends modpack on my kcauldron server.
I'm having issues with the BuildCraft item Quarry which uses a FakePlayer called [BuildCraft].
Even with a clean GroupManager config (towny.wild.* added) it fails to break blocks when the quarry is running. I have tried manually adding [BuildCraft] to GroupManager but no luck.

**Comment by LlmDl** [comment]
If you've given them that node in GroupManager and its still not working then I don't know what to say. Please do not open another ticket. I cannot provide support for mods.
