### ISSUE TITLE
Towns loosing deposits on server restarts

### ISSUE THREAD

**Issue by fenix12585** [LlmDl/Towny#2422]
Hello, 

I love towny, but recently I have been having an issue with it. Every time I do a /reload or restart, all the towns loose the money in there accounts. I am using the latest version of towny 0.90 and spigot 1.8.8 R0.1

I have checked the console, but there are no errors on shutdown or startup.

**Comment by LlmDl** [comment]
What economy plugin?

**Comment by fenix12585** [comment]
the essentials economy plugin

**Comment by LlmDl** [comment]
EssEco has been reseting bank accounts because of changes to their handling of fake-player-accounts. Essentials no longer gives support for their plugins for users of MC 1.8 and there is no update for 1.8 users in sight. Consider changing to CraftConomy3.

**Comment by fenix12585** [comment]
gotcha, thank you so much for your help!.. I will look in to converting ASAP.
