### ISSUE TITLE
[Suggestion] A Minimum Tax a Town Must Have Set for Members

### ISSUE THREAD

**Issue by CathalCraft** [LlmDl/Towny#2423]
A configuration option that specifies the minimum amount a town taxes its users would be a nice feature. For instance, the setting could be set to 1, so towns cannot lower how much they tax their users below 1. This would allow the plugin to be customized to make sure no towns have a tax of 0, forcing members of the town to pay taxes.

**Comment by Oblivioux** [comment]
I think if town mayors have the ability to pay for town fundings then they should be able to continue it and not let members (Especially if the town allows for new members to the server all the time) have to pay the town, especially if they don't have the money to support it.

I would decline this idea personally.

**Comment by CathalCraft** [comment]
It would be an option to change in the config, so it wouldn't be mandatory for every server that runs Towny. It just gives more options for the different people who use the plugin. On your server you could have it at 0 so towns can set no tax, but on my server it would be beneficial to the economy to set a minimum tax.

**Comment by Oblivioux** [comment]
Saying it like that actually makes more sense now.

I'd say it would be default to have it off, and server owners/developers will have to turn it on for something like that to happen.

**Comment by morfie78** [comment]
I'l love this option for minimum tax.  It would solve so many problems on my server, both economical and political.

**Comment by DragaoNimhe** [comment]
This would be -amazing-. An option to set a server-wide minimum tax would solve -so- many problems!!!

**Comment by morfie78** [comment]
@LlmDl What are your thoughts on implementing this?

**Comment by LlmDl** [comment]
It's something I'm considering as it has been met with lots of positive comments, no hard time-frame on it though. Probably before the next release build.

**Comment by morfie78** [comment]
Nice!  That is great news!

**Comment by DragaoNimhe** [comment]
Yay! I'm so excited for this! Thank you so much for looking into it!!!

**Comment by LlmDl** [comment]
This is a thing finally:
```
0.91.4.7
- New Config Option: Minimum Town tax. 
      - Found in the config at town.default_taxes.minimumtax
      - Default: 0.0
      - Sets the minimum tax required when mayors use the /t set taxes command. Affects both taxpercent/nontaxpercent situations.
      - Will not change any taxes already set by mayors.
```

**Comment by morfie78** [comment]
AMAZING!!  Thank you!!
