### ISSUE TITLE
Permission node for admins to be able to kill pets in plots

### ISSUE THREAD

**Issue by morfie78** [LlmDl/Towny#2424]
Currently, abandoned animals in plots cannot be killed, even by an Admin/OP.  They have to be moved out of the plot in order to kill the animal.  
Can there be a permission node so admins/mayors/assistants can kill other players abandoned pets left in plots?
Thanks.

**Comment by LlmDl** [comment]
I have never had an issue with that. Your admins have towny.admin right?

**Comment by morfie78** [comment]
No.  The server permissions are very tight.  Admins only have towny.claimed.*
However, I personally have the '*' permission node and still can't kill the pets in a plot.
I can try to /pex user ME toggle debug, hit a pet, and see what it says...

**Comment by LlmDl** [comment]
towny.claimed.* should allow people to kill animals. The test is whether a person can break grass blocks. If they can do that then they can kills animals. You're using pex though so that's probably why its not working like it should.
