### ISSUE TITLE
Chat in different worlds

### ISSUE THREAD

**Issue by noorkoteb** [LlmDl/Towny#2425]
I have 4 worlds for my towny server, Towny (wild is protected), WIld (you can break anywhere). spawn, and nether. for some reason when someone talks in spawn world everyone can see it but their reply cant be seen at spawn, you can see it if you are in the other worlds though.

**Comment by LlmDl** [comment]
Pastebin.com your chatconfig and link it here.

**Comment by noorkoteb** [comment]
http://pastebin.com/9KswwdqC

**Comment by LlmDl** [comment]
What permission plugin do you use and what towny chat permission nodes have you given in it?

**Comment by noorkoteb** [comment]
Im using the towny permisions, however I use the defualt of groupmanager

**Comment by LlmDl** [comment]
Pastebin.com your townyperms.yml

**Comment by LlmDl** [comment]
Oh and please tell me if your spawn world has usingtowny true or false?

**Comment by noorkoteb** [comment]
thats set on false for spawn, http://pastebin.com/PM2VWKQM

**Comment by LlmDl** [comment]
It's because its set to false, set it to true if you want the towny chat to be seen in teh spawn world. you can use /tw toggle claimable to make sure no one claims anything in that spawn world if you want.

**Comment by noorkoteb** [comment]
thank you
