### ISSUE TITLE
[Suggestion] A permission node for the /accept command

### ISSUE THREAD

**Issue by CathalCraft** [LlmDl/Towny#2427]
When a player is invited to a town with /t add <username>, the player has to type /accept to accept the invite. A permission node for the /accept command would be useful.

Even better would be a permission node that disallows a group or player from being invited to a town. For example, if a player has "towny.noinvite" and someone from a town use /t add <player> on them, the /t add <player> command won't work on that player.

**Comment by morfie78** [comment]
That would be fantastic!

**Comment by LlmDl** [comment]
No need for a new node, there is already towny.resident

Take that node away from the nomad group in the townyperms.yml and no one can join a town.

**Comment by CathalCraft** [comment]
I still want people to join towns, but I want to restrict a certain rank from joining towns. townyperms doesn't support ranks.

**Comment by LlmDl** [comment]
Take the towny.resident out of teh townyperms.yml and give it to the rank you want in your permission plugin.

**Comment by morfie78** [comment]
I tried something similar on my server.
The full story:
When people join the server, they are in the 'new' rank/group.  They need to complete a tutorial world. At the end of the tutorial, they get promoted to 'joined' and get TPd to spawn.   We want it so none on the server can /t add users while they are in tutorial, ie. have the 'new' group.  Only 'joined' or higher should be able to be invited to a town.

What we tried is:
1. Removed the towny.command.resident (I couldn't find something called 'towny.resident') from 'new'.
2. Added it to 'joined'.
3. Negated (added an explicit deny) the towny.command.resident permission from 'new'.

Despite what we tried in the above steps, users were still able to invite a 'new' person to town.

**Comment by LlmDl** [comment]
I went and looked it up, its in the nomad group of the townyperms.yml, it is   - towny.town.resident, without this node in that group, no one in your server will be able to join a town, unless they have that node given to them in your permission plugin's file.

**Comment by LlmDl** [comment]
re: morefie78

Your method doesn't work because you didn't remove the node from the townyperms.yml

**Comment by morfie78** [comment]
Cool. I'll try it out and let you know. Thanks!  @CathalCraft  will this work for you, too?

**Comment by CathalCraft** [comment]
This has worked now. Thank you.
