### ISSUE TITLE
New way to set claim land

### ISSUE THREAD

**Issue by Oblivioux** [LlmDl/Towny#2429]
The current grid plots of having a 16x16 (or so) plot of land available to purchase when one goes up to sell a plot to build a home seems very American/western in style and doesn't give options to have a neat layout inside of a town (Without having to entrust people not to destroy your properties)

The idea is very simple... Upon creating a town, and having a sprawling city booming, you can have the ability to set a specific area to use as the plot, instead of the normal 16x16 plots.

The ability to do this will allows players to have different style/size of plots, to which could be sold for more or less.

Here are the commands, and the description that would be added (theoretically) to this type of addition.

_/Plot set pos1_
While looking at the block that you want to be the edge of the plot, you may type this command, and it'll place your position for a plot.

_/Plot set pos2_
This would be the second position for a plot, it's basically the same thing as /plot set pos1

_/Plot set world_
This command will allow you to specifically set the plot that they have every block between the two points, as well as everything above and below it.

_/Plot set area_
This command will allow you to set one specific area directed by the two plots **(The block height difference must be a minimum of 3 to do this**) This is more for your multihome apartment complexes inside of a town.

_/Plot add (Plot Name) pos1_
This command works just like the normal /plot set pos1, but you can add onto your plot to give the plot a more different shape **(There has to be at least one or more connecting edges to the plot in order for you to do /Plot set world or /Plot set area)**

_/Plot set zone_
The command for setting a 16x16 plot like you can do currently on the plugin.

It's kind of like setting a worldguard when it comes to world edit, but you're doing it with plots.

**Comment by LlmDl** [comment]
Towny at its core has and always will be a system of claiming plots on a grid. 

Thank you for your long-winded ticket and the effort you put into it, but as we have in the past, this request will be denied.

**Comment by Oblivioux** [comment]
Alright, thanks for responding. I really tried to hopefully convince to get it placed onto there ^^
