### ISSUE TITLE
Towny Mod/admin showing on dynmap

### ISSUE THREAD

**Issue by GothkittyGirl** [LlmDl/Towny#2430]
anyway to fix this that ive not found yet? i dont want everyone to read the message that the staff are sending.

**Comment by LlmDl** [comment]
Have you tried this:

https://bukkit.org/threads/misc-info-dynmap-towny-v0-50-display-towny-towns-and-nations-on-dynmaps-maps-1-5-2-r1-0.46680/page-3#post-1191161

**Comment by GothkittyGirl** [comment]
does this do anything to the chat on dynmap? like hide certain chats from the dynmap?

**Comment by LlmDl** [comment]
I don't know I googled your question and that was what I found. I don't use dynmap.
