### ISSUE TITLE
Also another Task generating an exception problem

### ISSUE THREAD

**Issue by ChiuChiuTrains** [LlmDl/Towny#2432]
Never really had a problem with towny for awhile. This issue seemed to randomly show up after not fiddling with towny.

I saw someone previously also had an issue but with a different task number. Hopefully this isn't too repetitive.

Stack trace: http://pastebin.com/nNCahmjz

Chatconfig.yml: http://pastebin.com/E8Kh3snN

I ran our yml files through a parser and it doesn't seem to be a syntax issue.

I would appreciate the help and any explanation as to why this issue occurred.

If you need any more information please let me know and I will happily provide it!

Thank you,

- Brendan

**Comment by ChiuChiuTrains** [comment]
I would also like to add that we are running the most recent build of towny advanced version 0.90.0.0

**Comment by LlmDl** [comment]
The chatconfig doesn't auto update, you're missing the newer alone message stuff, if you rename your chatconfig to oldconfig.yml, then start the server townychat will make a new chatconfig.yml with the missing lines. Copy them into the oldconfig.yml, save it, rename it back to chatconfig.yml and then use /townychat reload in game.
