### ISSUE TITLE
Towny error

### ISSUE THREAD

**Issue by NOBUTSS** [LlmDl/Towny#2433]
[Error(Paste it on pastebin)](http://pastebin.com/yJL8fcdA)

I have no idea about how this happene

**Comment by LlmDl** [comment]
Could it be that someone manually deleted a town from the database which had claims there?

**Comment by NOBUTSS** [comment]
No,no one delete his town,just checked the "latest.log"

**Comment by LlmDl** [comment]
I don't mean using the ingame commands, I mean did someone go into the towny database (flatfile or mysql) and delete the town without also deleting the townblocks associated with the town.

Please go to the chunk that causes the error to pop up and use /towny map. Note the co-ordinates of the chunk.

Then in your database go to \towny\data\townblocks\ and see if there is an associated .txt file that matches the coordinates. Then go to the towny\data\townblocks.txt and make sure there is an entry for the coordinates.

**Comment by NOBUTSS** [comment]
I'm sure no one delete anything in database.
I'm going to check the things that you said.If there have any problem I will tell you.

**Comment by NOBUTSS** [comment]
I can't find any problem...If I have problem again,I will report.
Thanks for your help :)
