### ISSUE TITLE
Using sponge block bug towny

### ISSUE THREAD

**Issue by ospa555** [LlmDl/Towny#2435]
Hi, I'm using last towny version.
When someone like a foreigner user, tries to place a sponge block near water, the sponge block can't be placed but water gets soaked by the sponge.

**Comment by LlmDl** [comment]
Fairly sure this was due to a lack of a soak event in the Bukkit API. I'll look into whether they've made that event yet, if so I can stop it from doing that.

**Comment by LlmDl** [comment]
Checked again, there is still no event in the bukkit/spigot api for limiting sponges from taking water, sorry.

**Comment by ospa555** [comment]
WorldGuard can stop sponge soak. Maybe you can make something similar to stop sponge soak.

**Comment by LlmDl** [comment]
Looked through their code and saw no such code.

**Comment by DragaoNimhe** [comment]
If this is possible I am all for it. I have pools in front of all my plot... the other day someone went thru my shop district and did almost 5000 blocks of water grief using this exact glitch.

**Comment by LlmDl** [comment]
As of this comment, still no sponge soak event in the bukkit API.

**Comment by LlmDl** [comment]
So I tested this myself on 1.8 and 1.9 and its not due to Towny. Testing it using only Towny the sponge was not placed and the water was untouched. It must be another plugin interfering, something like WorldGuard or Craftbook perhaps.
