### ISSUE TITLE
Negative Upkeep

### ISSUE THREAD

**Issue by Dysth** [LlmDl/Towny#2436]
Towny Config: http://pastebin.com/DFQxHLES
Startup: http://pastebin.com/XwpwGMJC
Setting negative upkeep to give towns/players money instead of taking money is not working.
What we're trying to do is charge heavy taxes for towns and nations that are in a neutral state, and then grant negative taxe bonuses to nations that are not in neutral mode to give them a "tax break" in exchange for risking them entering war

**Comment by LlmDl** [comment]
This is fixed in the upcoming 0.91.1.0
