### ISSUE TITLE
Ban someone from town

### ISSUE THREAD

**Issue by morfie78** [LlmDl/Towny#2442]
Feature Request:
If there is an open town, and someone gets kicked for not following the rules, they can keep rejoining and mess around until they get kicked again- then repeat.   Thankfully this issue doesn't happen often, but it would be great if we could have a /town ban playername that would ban a user from joining an open town.
Please let me know if this is okay.  Thanks!

**Comment by DragaoNimhe** [comment]
I have been having MAJOR issues with this. This would be incredibly useful. Hopefully this gets some attention.

**Comment by achen954** [comment]
This happens to me a lot and is really ruining the experience when it happens. Please someone help resolve this!

**Comment by CathalCraft** [comment]
This would be very helpful for my server, too.

**Comment by yonib05** [comment]
+1
I have this issue too.  Would love to see this fixed

**Comment by Hickies** [comment]
I have mayor's complaining to me all the time about this. If this were implemented it would not only be great, but reduce my ticket load as well.

**Comment by trashcollector** [comment]
+1

Same here. It would be nice to get this resolved.

**Comment by LigerXT5** [comment]
Ditto, would be nice.
Maybe, just an addon function to banned, have them flagged as outcast towards the town. Possibly a permission setup to block or limit them access to town functions?

**Comment by LlmDl** [comment]
https://github.com/LlmDl/Towny/issues/1936
