### ISSUE TITLE
Unregistered townblocks preventing claiming land in wilderness.

### ISSUE THREAD

**Issue by coolsurdy** [LlmDl/Towny#2444]
Spigot version: Spigot 1.8.8-R0.1

Towny version: 0.90.0.0

Description:

**WILLING TO PAY FOR THIS, THAT IS HOW DESPERATE I AM**

I  am requesting /ta unclaim to check townblocks.txt, the /townblocks, and all the towns to ensure the plot becomes wilderness. Currently on my server, there are numerous areas that are "glitched" in that they are wilderness, but when you try to claim them it says they are claimed by someone else, when they aren't. I would estimate that at least 5-10% of my world is in this state, which leaves several thousand blocks unusable. 

It has gotten to a very bad rate. The only way for me to fix this is extremely tedious, I need to go into the /townblocks folder and edit the files for each individual town block. There are 35k individual files in my townblocks folder, which makes the directory incredibly slow with any FTP program. It is virtually impossible to do this all by hand.

So again, I am requesting that /ta unclaim makes the land into wilderness and removes it from this state. I know how this glitch happens, it's when the townblock gets removed from some areas but remains in others, which results in it becoming half-claimed. So if /ta unclaim could remove the townblock entirely, that would be great.

I know that you may be busy with other things, in which case I am willing to pay you for your coding time. This is a huge problem on my server and is causing many players to leave.

I desperately require help. Thank you so much for reading this.

**Comment by LlmDl** [comment]
The only way those things happen is when someone manually deletes a town in the database by FTP. Stop letting people manually edit the database and this wont be an issue.

 I can't promise that this will happen soon but it is something I'll look into.

**Comment by coolsurdy** [comment]
I didn't give a single player access to my database. Whenever players use /t unclaim all it glitches the townblocks.

Aside from that, I appreciate you looking into this. If you read my entire issue, then you would know that this is a huge issue. So many areas are unusable because of this. It is virtually impossible to fix it too, as I explain.

If ta unclaim all could unclaim the plot everywhere, that would solve the issue. I know you are probably very busy, so I am willing to pay. If you are not interested, do you think a develoler for hire could develop a fix for me?

**Comment by LlmDl** [comment]
Please tell me which message towny says to you exactly when someone tries to claim the land.

**Comment by coolsurdy** [comment]
This area (-245, 322) already belongs to someone.

In /towny map it is marked as Wilderness, all the flags are wilderness too (any player can destroy things which they are allowed to do in wilderness but not inside a claimed town.)

**Comment by coolsurdy** [comment]
Also, if I try to set the flags:

The TownBlock at (world, -245, 322) is not registered to a town.

**Comment by LlmDl** [comment]
Can you pastebin.com your townblocks.txt and the file in the towny\data\townblocks\world\ folder which corresponds to one of the townblocks that cannot be claimed.

**Comment by coolsurdy** [comment]
townblocks.txt exceeded Pastebin's 512KB limit, so here is the link:
https://paste.ee/p/G2hH7

The townblock which cannot be claimed does not exist in the /townblocks/world folder, so I cannot copy the text from it.

I can send you the entire /townblocks/world folder if you wish.

**Comment by LlmDl** [comment]
There's a discrepancy between what you have told me so far. I need you to clarify.

If I test a townblock that is in the townblocks.txt but not in the townblocks\ folder, by trying to claim it I get the Message: "This area has already been claimed."

But you say that I should be seeing "This area (-#, #) already belongs to someone." which is it?

**Comment by LlmDl** [comment]
Ok, I've got a test build that should fix this issue. If you want to join the Towny IRC we can see about getting it our early to you to test: http://webchat.esper.net/?channels=towny

**Comment by LlmDl** [comment]
Managed to fix this and a second type of townblock corruption. Corruption will automatically be fixed on server startup or use of '/ta reload'
