### ISSUE TITLE
Add title when enter in a region

### ISSUE THREAD

**Issue by JohOply** [LlmDl/Towny#2446]
Hi,

Like factions, i hope it is possible to add a title feature, with possibility to be disabled in config

Example : http://i.imgur.com/eh21lDh.png

Thank you

**Comment by LlmDl** [comment]
There is currently no Bukkit API to accomplish this. As we do not rely on CB or NMS code we cannot accept this ticket at this time.

**Comment by graywolf336** [comment]
Commenting on this as they have added one, although it's marked as deprecated due to it highly likely to change in the future: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#sendTitle(java.lang.String,%20java.lang.String)

**Comment by TekkitCommando** [comment]
@graywolf336 Oh interesting :) May try to add this functionality and send a pr if I get it working.

**Comment by LlmDl** [comment]
PRs are welcome, as long as it defaults to off, set in a config. Also would be nice to add a resident mode (res set mode towntitle and res toggle towntitle commands,) so players could turn it on for themselves if they like.

**Comment by TekkitCommando** [comment]
Ok if I can get around to trying this I will see if I can add those options as well.

**Comment by LlmDl** [comment]
I've added this into 0.91.4.7, it defaults to off but it'll be there for servers that want it.
