### ISSUE TITLE
Adding custom rules for towns

### ISSUE THREAD

**Issue by lewisnolan1** [LlmDl/Towny#2450]
Hi.

I think it would be a great idea if each town could do a command for example: /towny rules 

So you can create rules if you are an assistant and Mayor but residents can't.

I think this would be a great feature to towny plugin.

**Comment by LlmDl** [comment]
I dont see this happening, as they wouldn't enforced by Towny. Any player can write a rule book, make a rules section in their town spawn, and enforce it as they see fit.
