### ISSUE TITLE
HELP, ghost town in spawn

### ISSUE THREAD

**Issue by shadyblues** [LlmDl/Towny#2451]
Help! in spawn there is a issue where players could not open enderchests or even interacts with anvils, at first i assumed it was world edit but someone noticed there is a town called "none" in spawn, it appears on the towny map and If i try to create a town it says there already is a town in this area. Yet, when i try to delete it or force clear the plot it says there is no town there....HELP

**Comment by LlmDl** [comment]
If you update to 0.91.0.0 then you'll probably find the ghost town is automatically cleared up. This is a bugged area that was once claimed and when it was unclaimed it was not properly removed.
