### ISSUE TITLE
Bonus block purchase - Output text.

### ISSUE THREAD

**Issue by ntall1** [LlmDl/Towny#2452]
Regardless if the server owner is breaking the EULA or not, there is a sentence that clearly reads: "The server you play on breaks the Minecraft EULA and, worse, is selling part of Towny which your server admin did not create. You should consider changing servers and requesting a refund of your money."

As a server owner who follows the MineCraft EULA and does not sell bonus Towny blocks. This text output is a little off putting. While part of a full paragraph, each sentence can be comprehended interdependently from each other and taken out of context. 

If a statement like this needs to be there, than it should not be worded ambiguously. It should make clear statements that can not be taken out of context or misinterpreted by less intelligent players.

This is just an example but I feel this would be much better as there is no single sentence, out of context, that makes accusations about the server owner, staff, or administration: "Paying real money for this purchase is against the Minecraft EULA. If you paid real money for this upgrade, we recommend contacting your server administration to request a refund."

**Comment by LlmDl** [comment]
I see what you mean, if you leave off the first sentence entirely. Not really an issue if there wasn't a money-exchange. 

I'd be willing to clear it up like so:

"If you have paid any real-life money for these townblocks please understand: the creators of Towny do not condone this transaction, the server you play on breaks the Minecraft EULA and, worse, is selling a part of Towny which your server admin did not create."
"You should consider changing servers and requesting a refund of your money."

**Comment by ntall1** [comment]
That is much better. Thank you for your quick response.

**Comment by LlmDl** [comment]
http://palmergames.com/file-repo/Towny%20Advanced/Development/0.91.0.2/ has the new message

**Comment by NorbiPeti** [comment]
This message is still a bit too harsh in my opinion, especially as the second paragraph tells players to switch servers unconditionally. Of course, you can't ask for a refund if you didn't pay anything but it's still a bit weird to me.
