### ISSUE TITLE
Warn while updaing from 0.90.0.1 to 0.91.0.3

### ISSUE THREAD

**Issue by Blackyvk** [LlmDl/Towny#2455]
[04:09:29] [Server thread/WARN]: [Towny] Error: Error updating table RESIDENTS :Can't DROP 'townBlocks'; check that column/key exists
[04:09:29] [Server thread/WARN]: [Towny] Error: Error updating table TOWNS :Can't DROP 'townBlocks'; check that column/key exists

I checked those tables and yes those columns dont exist, is that ok ??

**Comment by LlmDl** [comment]
Pastebin.com your full startup from the latest.log.

**Comment by LlmDl** [comment]
Also, neither of those versions you mentioned were ever released to the public at large so I would like you to tell me which version you actually updated from, and to which version you're using now.

**Comment by Blackyvk** [comment]
I did update from that version, I compile towny myself because I translate some things you cant translate with the lang files.

http://pastebin.com/3XPU8xf7

**Comment by LlmDl** [comment]
Nothing has changed on the sql side of things since before 0.90.0.1. I don't know that this has anything to do with the update itself. The townBlocks tables haven't been stored in resident/town for a long long time.

**Comment by Blackyvk** [comment]
so I just ignore it and nothing to worry about I guess ?

**Comment by LlmDl** [comment]
Does it appear on subsequent startups?

**Comment by Blackyvk** [comment]
It doesnt, clean startup, I think I have seen that warning before whenever I update... maybe old config files or something ?

**Comment by LlmDl** [comment]
Your config had to be for 0.90.0.0 if its showing the changelog for 0.90.0.1, I'd just ignore it. Its meant to clean up the SQL when the townblocks were moved. No clue why it would decide to try and clean it up now. 

You'll need to review the language file, there have been some new strings added recently.
