### ISSUE TITLE
Friendly-fire as a per-world flag, and add auto deletion for towns in which all members exceed an inactivity threshold.

### ISSUE THREAD

**Issue by coolsurdy** [LlmDl/Towny#2456]
Hello,

2 things. Firstly, I would love to see friendly fire as a toggleable per world flag. The reason I ask this is because I have one separate world for my mini games. I have Towny disabled so that friendly fire is allowed. The problem is is that players cannot see chat in the main world. If you could add friendlyfire as a per-world flag I would enable Towny so that they can see chat but disable claiming and friendly fire and my problem would be fixed.

Secondly, I have plenty of towns on my server that can afford upkeep but all the members have been inactive for several months. If you could also add the ability to specify a time in days "x" in config.yml, then towns in which ALL residents have not been online for "x" days, the town will delete. I cannot use the built in resident feature as that only deletes residents, not towns.

Thanks once again!

**Comment by LlmDl** [comment]
In regards to part 2, the old resident deletion will delete the town if there's no residents. Use it.

**Comment by LlmDl** [comment]
https://github.com/LlmDl/Towny/issues/1242
