### ISSUE TITLE
When Claiming a stop and then unclaiming some blocks rollback

### ISSUE THREAD

**Issue by LoadedServerowner** [LlmDl/Towny#2457]
Hello,
So i got this problem it's all in the video but i have on unclaim revert blocks thing set to false but
https://www.youtube.com/watch?v=85haRKkejZA&feature=youtu.be

Can you please tell me what the problem could be?

heres the config http://pastebin.com/txrifiHJ

**Comment by LlmDl** [comment]
I can't access your video.

If you had read the comments for that section of the config you'd know that the config is only default settings for new worlds. This is also covered in the Towny install guide. You have to use the /tw toggle command to turn off the revertunclaim in each world you don't want it on.
