### ISSUE TITLE
/back problem

### ISSUE THREAD

**Issue by LoadedServerowner** [LlmDl/Towny#2458]
Now you may be thinking what does a essentials command have to do with towny?

Well when players join the server and lets say they were at some spot in the wild and then do /t spawn and then /back it will just take them to the /t spawn point?

any idea why towny is doing this?

**Comment by LlmDl** [comment]
Probably because the the town spawn isnt an essentials teleport? The only thing I can think that would change any of this in Towny would be to make sure you have using_essentials: true in your Towny config.yml.

That being said, Towny doesn't have anything to do with the essentials /back command.

**Comment by LoadedServerowner** [comment]
Ok thank you
