### ISSUE TITLE
Nation member can go t spawn to any town in the nation

### ISSUE THREAD

**Issue by LoadedServerowner** [LlmDl/Towny#2460]
Is there a way to stop anyone in a nation from spawning to a nation members town? Cause lets say the town is not public is off nation members can still do that and at the moment nation spawn is totally off and i want it up but only for towns that pick to allow nation members to teleport to their town.

Is there a way to do that?

PS. Sorry for all the questions

**Comment by LlmDl** [comment]
Add the negated  node - -towny.town.spawn.nation into the townyperms.yml

**Comment by LoadedServerowner** [comment]
Ye but will this allow people with town public mode to be able to tp?

**Comment by LlmDl** [comment]
If the Towny is public and the person that wants to get there has the public town spawn node then yes it will work.
