### ISSUE TITLE
Farm Plot anyone can kill animals

### ISSUE THREAD

**Issue by Blackyvk** [LlmDl/Towny#2462]
Anyone can kill animals inside a farm plot. it doesn't matter if they belong or not to any town, if the are inside other plot that isnt a farm plot they cant kill it. I believe only resident should based on permissions.

my perms inside the farm plot
http://i.imgur.com/cYG2Ea8.png

also, i even tried to add wheat to the list but nobody can destroy it, anything else is fine

farm_plot_allow_blocks: LONG_GRASS,DOUBLE_PLANT,YELLOW_FLOWER,RED_ROSE,PUMPKIN_STEM,MELON_STEM,BEETROOT_BLOCK,CARROT,POTATO,WHEAT

**Comment by LlmDl** [comment]
This is probably a bug, I'll test it. It should only allow residents of the town to kill the animals.

**Comment by LlmDl** [comment]
Found it and fixed it, this will go public tomorrow in a new release build 0.91.1.0

**Comment by Blackyvk** [comment]
Thanks, Tested and worked and btw the wheat material is CROPS, I think you should add it to the default

**Comment by LlmDl** [comment]
Indeed, I think my list of blocks might have been reverted to a previous version. Would you mind trying out carrot and potatoes. I'm thinking that the names we have in there right now aren't correct.

**Comment by Blackyvk** [comment]
yes those work fine, I think I tested all of them.

i have it like this

  farm_plot_allow_blocks: LONG_GRASS,DOUBLE_PLANT,YELLOW_FLOWER,RED_ROSE,PUMPKIN_STEM,MELON_STEM,BEETROOT_BLOCK,CARROT,POTATO,CROPS

**Comment by LlmDl** [comment]
Ok, thanks for double checking, dunno how crops got missed after we'd tested with them earlier.

**Comment by Blackyvk** [comment]
and I just added these ,MELON_BLOCK,PUMPKIN in my config. else you can only take the seed and leave the block there.

**Comment by LlmDl** [comment]
Thanks
