### ISSUE TITLE
Translate the plugin to another language

### ISSUE THREAD

**Issue by Szikszai60** [LlmDl/Towny#2464]
I translated parts of the plugin to Hungarian but something is very annoying. I cannot translate some words that are variables (build, switch, destroy, itemuse ect.) 
Can you add an option to translate it? 
Or i have to delete the variable and only write you do not have permission to do that?

**Comment by LlmDl** [comment]
If you have a Hungarian language file you want to share I'd gladly add it to the plugin.

We cannot have some things like build/destroy/switch and commands translated however.

**Comment by Szikszai60** [comment]
If it will be completed and tested i will share.
