### ISSUE TITLE
Having problems with using plot payments and negetive upkeep

### ISSUE THREAD

**Issue by ErrantSperm** [LlmDl/Towny#2465]
I want my towns to make money depending on how many plots they have.  When the new day event happens, it does not add any money to the town balance or personal balances event though it says town upkeep -10.  I have tried every combination of settings I can think of and it doesn't seem to work.  I have essentials and vault.

**Comment by LlmDl** [comment]
please pastebin.com your full config.yml

**Comment by ErrantSperm** [comment]
I'm not sure how to use pastebin but maybe this will work while I try and figure it out.

[config.txt](https://github.com/LlmDl/Towny/files/190270/config.txt)

**Comment by ErrantSperm** [comment]
Do you have to do an account to use pastebin because I can't seem to paste anything

**Comment by LlmDl** [comment]
You don't need an account. You are not up to date. Update your towny to 0.91.1.0, it has a fix for negative upkeep.

**Comment by ErrantSperm** [comment]
do you have a link to that?  I thought a had the latest version.  And thanks a bunch :)

**Comment by LlmDl** [comment]
http://towny.palmergames.com/?p=859

**Comment by ErrantSperm** [comment]
That fixed it.  Thanks again
