### ISSUE TITLE
Suggestion: Add permisson node to area claiming/selection size claiming.

### ISSUE THREAD

**Issue by ErrantSperm** [LlmDl/Towny#2470]
With towny.command.town.claim.town it lets you claim plots other than the plot you are standing on with the /t claim # command. (or /t claim auto)

As a temp solution is I am allowing outposts only with towny.command.town.claim.outpost but I would like to make it so that /t claim is allowed, while /t claim auto or /t claim # is not.

Let me know if this is possible or not.

**Comment by ThemInspectors** [comment]
use /res set mode towclaim

**Comment by LlmDl** [comment]
I deleted the last comment because it is not a proper workaround.

There are no permission nodes for area claiming, though it is a good idea to add them.

**Comment by LlmDl** [comment]
There is a new node towny.command.town.claim.town.multiple which is required as of 0.91.2.2, it is not given by default (it is not inherited from towny.town.claim.*)
