### ISSUE TITLE
Hostile mobs not being removed from town plots with mob spawns turned off

### ISSUE THREAD

**Issue by asdfjkll2** [LlmDl/Towny#2473]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Turn force mob spawning off for town mobs
2. Turn off mob spawning on a town plot or in a town
3.

### What is the expected output?
1. Monsters should not be able to spawn on town plots
2. Monsters get deleted when they step on town plots
3.

### What is your Towny version?
Do not say "latest".
Towny v0.91.1.0

### What is your spigot/craftbukkit version?
Do not say "latest".
Spigot version 1.9-R0.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : http://pastebin.com/3KMd8GMu
2. Your Towny config.yml (if using MySQL please remove password,) : http://pastebin.com/YKGY4gCH
3. Your townyperms.yml : http://pastebin.com/CRqWpiRu
4. Your log's error : http://pastebin.com/CXGXC73A

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Update your citizens to the version made for your version of Spigot/Bukkit/MC. This happens when your citizens is out of date.
