### ISSUE TITLE
No towny commands work?

### ISSUE THREAD

**Issue by OrenJinx** [LlmDl/Towny#2475]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1./tc /nc
2./t spawn
3.anything other that /town new doesnt work

### What is the expected output?
1.to talk in town chat or nationchat
2.to go to the town spawn
3. - 

### What is your Towny version?
Do not say "latest".

### What is your spigot/craftbukkit version?
Do not say "latest".
Dev Build: Towny Advanced 0.89.2.28 [1.8.4+]

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
You skipped all the files on pastebin.com which would have helped me help you.
