### ISSUE TITLE
Towny Channels wont work

### ISSUE THREAD

**Issue by Luseres** [LlmDl/Towny#2476]
Towny Channels

### What steps will reproduce the problem?
I tryd to make new channels and reloaded the server but then the channels wernt working anymore so i removed them and reloaded again but they still not work, I use some worlds for gun minigames and other for towny
Towny worlds:
Deathlands + nether + end
Wilderness + nether + end
Towny (no nether and end)

ps can you please say how i can add new channels to when you fixed the bug plz? ;D

### What is the expected output?
12.04 20:08:09 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.fetchBlockEntry(ScannerImpl.java:778) ~[spigot19.jar:git-Spigot-ccb6016-f92e01b]
12.04 20:08:09 [Server] INFO ^
12.04 20:08:09 [Server] INFO ... permsuffix}&f:{msgcolour} {msg}'-
12.04 20:08:09 [Server] INFO in 'reader', line 108, column 83:
12.04 20:08:09 [Server] INFO Caused by: org.yaml.snakeyaml.scanner.ScannerException: sequence entries are not allowed here
12.04 20:08:09 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
12.04 20:08:09 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot19.jar:git-Spigot-ccb6016-f92e01b]
12.04 20:08:09 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot19.jar:git-Spigot-ccb6016-f92e01b]
12.04 20:08:09 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot19.jar:git-Spigot-ccb6016-f92e01b]
12.04 20:08:09 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot19.jar:git-Spigot-ccb6016-f92e01b]
12.04 20:08:09 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot19.jar:git-Spigot-ccb6016-f92e01b]
12.04 20:08:09 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot19.jar:git-Spigot-ccb6016-f92e01b]
12.04 20:08:09 [Server] INFO at com.palmergames.bukkit.TownyChat.tasks.onLoadedTask.run(onLoadedTask.java:28) ~[?:?]
12.04 20:08:09 [Server] INFO at com.palmergames.bukkit.TownyChat.config.ConfigurationHandler.loadConfig(ConfigurationHandler.java:170) ~[?:?]
12.04 20:08:09 [Server] INFO at com.palmergames.bukkit.TownyChat.util.FileMgmt.getFile(FileMgmt.java:68) ~[?:?]
12.04 20:08:09 [Server] INFO plugins/Towny/settings/ChatConfig.yml
12.04 20:08:09 [Server] INFO java.lang.IllegalArgumentException: The following file couldn't pass on Parser.
12.04 20:08:09 [Server] WARN Task #69 for TownyChat v0.45 generated an exception

### What is your Towny version?
0.89.2.28

### What is your spigot/craftbukkit version?
Spigot 1.9

### Please use Pastebin.com to link the following files:

1. Full logs: http://pastebin.com/40PQFniT
2. Your chatconfig.yml : http://pastebin.com/WUbSqnSu
3. Your channels.yml : http://pastebin.com/8whXRDYF

**Comment by ThemInspectors** [comment]
Not Valid YAML For more infomation paste your chatconfig.yml into www.yamllint.com

**Comment by LlmDl** [comment]
End of line 108 of your chatconfig.yml has a -, remove that and be more careful in teh future when you're editing .yml files.
