### ISSUE TITLE
Add Method to get Mayor/King Prefixes

### ISSUE THREAD

**Issue by DrkMatr1984** [LlmDl/Towny#2477]
I understand there is resident.getFormattedName() which gets these prefixes, plus the name, But I feel like there should be a list of all prefixes accessible from API, and then a way to get Individual player prefixes. It would be handy to be able to JUST get the prefix so I can append it to getCustomDisplayName() to create unique messages. I understand I can just split the string, but that seems kind of backwards, like there should be a method to get the prefix in the API, and the plugin itself assembles the resident.getFormattedName() from the prefix and name. There's an isMayor() and isKing(), there should be a getTownPrefix() or getNationPrefix() to go along with those.

Thanks!

**Comment by LlmDl** [comment]
Is that not handled already by resident.getTitle() and .getSurname() ?

**Comment by DrkMatr1984** [comment]
Nah, getTitle() gets weird titles you set with /setTitle (It's some subcommand) and .getSurname() also has some weird subcommand setter. I looked through the source before I asked this and ran a few debug messages just to make sure.

**Comment by LlmDl** [comment]
I know this is late but I did some digging and I think you ought to be able to use the TownyFormatter.getNamePrefix(Resident) & TownyFormatter.getNamePostfix(Resident). 

If this doesn't work and you still want it let me know and I'll reopen this ticket.

**Comment by DrkMatr1984** [comment]
OK, I'll check it out and let you know. Thanks for the update/response.
