### ISSUE TITLE
Unbelievable intrusive message sent on givebonus

### ISSUE THREAD

**Issue by doitliketyler** [LlmDl/Towny#2480]
Reposting because developer just immediately closed this as if its not an issue. I'll keep reposting and send my players and friends to repost until you respond appropriately.

https://imgur.com/x2jku7b

Way to spread your personal opinions on a server where this doesn't even apply. Have you even considered the servers who use Towny and are 100% EULA compliant? You think its ok to flood a players chat with this kind of crap? Honestly...shame on you. I cant even give my players a few blocks out of kindness or for voting without this being sent to them. Its just bad user experience and it makes my players have to read something that doesn't even apply to them and actually makes them confused. Some have even asked me to disable it.

Residence looks so good right now...

**Comment by ThemInspectors** [comment]
Really don't double post.The devs are probably looking @ it now

**Comment by doitliketyler** [comment]
Did you read what I said? He closed it and ignored what I said. So no...he isn't looking at it.

**Comment by LlmDl** [comment]
Repeat, please speak in the existing ticket.

**Comment by doitliketyler** [comment]
You mean the one you closed and just said "k" immediately in?

**Comment by itsmariatee** [comment]
I think this needs to happen to. I don't sell town blocks to players. I don't even have a store for my server. Its ugly and long and no one needs to read this.

**Comment by LlmDl** [comment]
Yes, thats how the ticket system works. A closed ticket doesn't mean that discussin has ended.

 You state that I'm spreading my personal opinion like I have no right to do so, and then proceed to spread your own personal opinion. Life is a two-way street. 

If you do follow through with your threats to spam the issue tracker here I'll be forced to report your github account as I am instructed to do on this page: https://help.github.com/articles/disabling-issues/
