### ISSUE TITLE
Suggestion: Towny Upkeep Option

### ISSUE THREAD

**Issue by 05192000** [LlmDl/Towny#2481]
Current Towny Setup: Admin of the server is able to set the upkeep for the towny daily and it will not change.
Proposal: Keep that option and another option that says "Admin of the server does not set the upkeep for the town, but instead, for every x amount of players in a town, the upkeep will increase by x amount daily."
Example:
1:10 Ratio
2 Players would be $20/day
3 Players would be $30/day
4 Players would be $40/day
10 Players would be $100/day

**Comment by LlmDl** [comment]
This can be accomplished already by creating/adding to the townlevels section of the config and using the upkeep multipliers.
