### ISSUE TITLE
Suggestion: TownyRoyale

### ISSUE THREAD

**Issue by IDoctorI** [LlmDl/Towny#2484]
# **What is it?**

A fun way for players to strive to grow their town and have some friendly competition at the same time. TownyRoyale would utilize statistics of player towns to create a competitive, risk-free minigame that is designed to enhance the already amazing Towny experience.
# **Why is it needed?**

The simple answer is- it's not needed. Many players have had amazing fun with Towny and it pairs very nicely with a lot of economy resources and plugins, but I would like for it to be more than a land management plugin. TownyRoyale would introduce so many fun mechanics and bring a whole new perspective to the game. It would allow for a want to upkeep towns and make them better, and would take Towny to a whole new level. **TownyRoyale would be a separate plugin from Towny and be completely optional.**
# **What does it do, Specifically?**

Players would fight against two main enemies, other towns/players, and a single player type villain that you can read about in the next section. TownyRoyale would be single-player at the basic level, then Towns would be able to work together, utilizing Towny Wars much more effectively, Towns Being at war would mean that they could battle against each other alongside the actual war, or replace them altogether with settings in the config. Nations could serve a new purpose, giving actual meanings to partnerships between towns, together they would earn a multiplier or boost whenever they won a battle. Players could gain RoyalePoints or RP for each match they win, and each match they start would cost them a small amount of RP. It would give way to a whole new type of game, one that supports and is supported by survival Minecraft.
# **Battle Mechanics**

Any player: mayor, assistant, or member would be able to start a battle. Battles would be single player and risk-free to the player. When the player starts a battle he/she is taken to a birdseye view of the Royale Representation of their town, it will not represent the town's actual structure, but rather the town's depiction would be a stock town that represents the player's town in terms of rank and how many members it has. Different items such as traps, walls and troops could be deployed before the start of the match, these could be bought with RP or other currency, and players would be put into fly mode and be able to edit their town defences in 3D. Then once the battle starts they could switch from 3D view to 2D birdseye to watch their troops. Different spells or potions could be an added item, players could drop these after the battle starts. When a player wins a battle they would get a reward in the form of RP with an option for adding premium currency or items to the reward in the config.
# **TownyRoyale Arena**

This is a concept build I did just after posting this suggestion. Its a concept for how the board would look with no towns on it. 

![img](https://cloud.githubusercontent.com/assets/19360954/15269610/e95b9b72-19c9-11e6-9f80-3e826891fd90.jpg)

Reminder: This would be totally optional to servers and in no way would be required to run normal Towny.

With this all being said I really hope I get some support with this, I think that the Towny community would really like it and think it would add a lot of fun to the game itself. If you guys are interested in developing this sort of think tell me in the comments or by skype or email. Be sure to tell me that you are from this thread so I don't mark you as spam! :smile: Also check out my strawpoll I made for this suggestion! http://www.strawpoll.me/10209268

Skype: sirblazedoctor

Email: doctor.snapmc@gmail.com

**Comment by LlmDl** [comment]
This is one wild idea. I won't be developing the separate plugin but hopefully you find someone.
