### ISSUE TITLE
Command /t doesn'T working as suggested

### ISSUE THREAD

**Issue by Tomcatchriss** [LlmDl/Towny#2485]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. /(t standalone) will show the members of a town
2. each other command with /t begínning, like /t online gives us an error message like "[Ljava.lang.String;@67c5da8e ist nicht regestriert". Same happens with /town
3. /towny:t (variable) works well

### What is the expected output?
1.
2.
3.

### What is your Towny version?
Dev Build: Towny Advanced 0.91.0.2

### What is your spigot/craftbukkit version?
Spigot 1.9.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : http://pastebin.com/8hSHKQU1
2. Your Towny config.yml (if using MySQL please remove password,) : http://pastebin.com/4yAnr9Zu
3. Your townyperms.yml : http://pastebin.com/KCGce44Z
4. Your log's error : None

**Comment by LlmDl** [comment]
You're using 0.91.1.0. 

You need to update your Citizens to a newer built meant for 1.9.4.

Are you certain another plugin isn't using the /t alias ?

**Comment by Tomcatchriss** [comment]
Yes, and /t without any parameters is working and displays the members od the town. But if we add parameters like /t online it wouldn't work. And yes on this server, I forgot to update Citizens :)

**Comment by LlmDl** [comment]
Are you certain another plugin isn't using the /t alias ?

**Comment by Tomcatchriss** [comment]
Yes,we have on out other servers without towny only a customCommand, wich says that this command only works on our towny server. But this customCommand isn't on our towny server. I have checked it again and there is no other plugin using /t

**Comment by LlmDl** [comment]
So /towny:t online works and /t online doesn't?

That's got to be an issue with another plugin interfering.

**Comment by Tomcatchriss** [comment]
yes, this is working. but i don't understand with wich plugin this should be an interference.

**Comment by LlmDl** [comment]
Start removing plugins. Do half, then half again and so on until it stops interfering.

**Comment by Tomcatchriss** [comment]
okay, i will trying it.

**Comment by Tomcatchriss** [comment]
I have now runnign the minimum plugins, I need to run the server: Worldedit, Worldguard, ProySuiteBukkitBridge (this one is tested with towny), vault, craftconomy, multiverse and protocollib.

The problem is still there :(

**Comment by ThemInspectors** [comment]
Route an Alias In the commands.yml file If that still does not work Try preventing Bungee Plugins from handling the command
