### ISSUE TITLE
Flag-War not working

### ISSUE THREAD

**Issue by Sniddunc** [LlmDl/Towny#2488]
### What steps will reproduce the problem?
1. Attempt to place a war flag block (fence)

### What is the expected output?
1. The flag is placed along with the signal on top
2. The attack on that plot begins.

### What is your Towny version?
0.91.0.2

### What is your spigot/craftbukkit version?
CraftBukkit version git-Spigot-798f32d-0cd0397 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : http://pastebin.com/uRtkEt6y
2. Your Towny config.yml (if using MySQL please remove password) : http://pastebin.com/jJTaJgmS
3. Your townyperms.yml : http://pastebin.com/StXc52eC
4. Your log's error : No errors, it just refuses to work.

(optional) If this is to do with permissions, 
5. Your permissions file : I'm not sure if this is to do with permissions, but just in case: http://pastebin.com/R0PZCXTz

I have read that being OP can cause this so I made sure that none of the testers were opped.

Thanks!

**Comment by LlmDl** [comment]
Flag War isn't supported anymore but one thing most people don't realize is that people with towny.admin in their permission nodes cannot place war flags. Make sure you aren't OP'd or have towny.admin and retest.
