### ISSUE TITLE
Suggestion: Towny warp command.

### ISSUE THREAD

**Issue by ShadesMojo** [LlmDl/Towny#2490]
A basic **towny setwarp command** (Ex: /t setwarp Mines) and a **towny warp command** (Ex: /t warp Mines), making travel through a big town much easier.

**Comment by Leecook337** [comment]
You can just use outposts.

**Comment by andrewyunt** [comment]
The problem with outposts is that they aren't within the town so it's basically a completely different area. I'm most likely doing this in my major Towny pull request, although I'm going to talk with LlmDl about the idea first.

**Comment by TekkitCommando** [comment]
Each PR should add one feature so it is easier to control what will be added and what won't imo.

**Comment by LlmDl** [comment]
There's plenty of warp plugins, I don't think mayor's need their own warp system. We'll see what @andrewyunt has in mind.
