### ISSUE TITLE
Outsiders can access Brewing Stands

### ISSUE THREAD

**Issue by Spedwards** [LlmDl/Towny#2491]
Outsiders are able to access brewing stands in other towns.

### What steps will reproduce the problem?
1. Open a brewing stand in another town.

### What is the expected output?
1. Get denied, unless outsider has the Switch permission.

### What is your Towny version?
0.91.1.0

### What is your spigot/craftbukkit version?
Spigot 1.9

**Comment by LlmDl** [comment]
You skipped the config which could have told me if you had the brewing stand in the switch list.
