### ISSUE TITLE
Problem with outsiders

### ISSUE THREAD

**Issue by ingranne** [LlmDl/Towny#2492]
Hello!

In my server, outsiders can build and destroy in towns that they aren't in. I have set the setting for outsiders building and destroying in claimed area to false.
I am using 'using_permissions: true', so it will use the permission setup I have in PEX, not in Townyperms.yml.(That's how it should work, right?)

I need to set it to settings that won't allow outsiders build or destroy in claimed land.

NB! Only members of other towns can edit in the town that they are not in, regular members can't. I have put the permission that you can only build in your own town for members, too.

Please help!
Thanks.

**Comment by LlmDl** [comment]
You skipped the form entirely, so this ticket is being closed. But, like I said to you in the IRC previous to this, you need to remove all towny nodes from the pex files except the towny.wild.* node. 

If this does not fix your problem then join the IRC and I'll help you change from PEX to something else.
