### ISSUE TITLE
Suggestion:  Town/Plot Lock

### ISSUE THREAD

**Issue by Omnyth** [LlmDl/Towny#2493]
Currently there is a server out there that developed their own Towny plugin that adds the ability to lock plots.  However they won't release the plugin to the public and there's no similar plugins out there.

When a plot/town is locked with noclick, it disables outsider's abilities to click in or near the town.  What this means is that many means of bypassing towny (for modded servers this would help a lot) would be completely gone.  It keeps players from using click events, which I feel outsiders didn't need in the first place.

The second part that they added is that players are unable to move or are teleported out of the town when they attempt to enter the town.

If possible, you could even add a friend/townmember exception list and maybe even allow players to toggle their plots separately.

The current towny build I'm using is 0.88.0 due to having to use 1.7.10 minecraft for modding.  Anyway, thanks a ton guys!  I've always really loved towny and I think you've done a great job over the years!

**Comment by TekkitCommando** [comment]
It should be as simple as getting the chunk the player and if it is owned by a town and a resident and if plot locks is true in config then you just set onPlayerInteractEvent to cancelled if in a plot that is locked and same with the moving into the plot. Towny already use a moveToChunk event and so just get previousLoc and check if plot is owned by town and a resident and then getCurrentLoc and teleport them to previousLoc then send a towny messages that says "This plot is locked."

**Comment by Omnyth** [comment]
I wish I could just make it myself.  But as of right now, I don't really have the skills for it :\

**Comment by ThemInspectors** [comment]
Wait A house arrest permission to lock plots ingenious

**Comment by Omnyth** [comment]
I'm really curious if they'll consider adding something like this, as it's something that I've always thought was necessary for towny on modded servers.  I'm almost considering just making my separate plugin, just would rather it be something that's part of towny to be quite honest.

**Comment by TekkitCommando** [comment]
@Omnyth If you would go through the trouble of making a separate plugin then why not just make a PR and add this yourself?

**Comment by Omnyth** [comment]
Well, I can't say I WANT to go through the trouble of it.  I haven't done much work with plugins, so it would likely be a lot of work for me.  However, if I have no other options, then I might have to.

And making a separate plugin might help with version integration.  If I made something like this, I'd want it available to everyone, not just my version :P

**Comment by LlmDl** [comment]
This really does need to be a separate plugin. The Towny API has everything needed. If I were to put this into Towny it would still be years until your modded server is on to the current version of MC ( 1.11, soon to be 1.12)

If no one steps up to the plate I'll probably make this eventually but I wouldn't expect it soon.
