### ISSUE TITLE
Thaumcraft Golems with Use Core are unable to use items on blocks.

### ISSUE THREAD

**Issue by KruhlSentru** [LlmDl/Towny#2494]
The basic problem is that Towny is blocking Thaumcraft's golems from using items on blocks, such as using a sapling on dirt to plant a tree, or bonemeal on grass to grow tall grass and flowers.  Instead, the golem will repeatedly attempt the same action over and over, with no effect.  Disabling only the Towny plugin fixes this problem.  Others have found similar issues with plugins such as WorldGuard, verifying the likelyhood of such a problem being related to protections.  Furthermore, Thaumcraft uses a fake player called FakeThaumcraftGolem in order to have the golems perform various operations.  Personally, I suspect that I may have incorrectly entered the fake player into the configuration file while attempting to have Towny ignore FakeThaumcraftGolem.
### What steps will reproduce the problem?
1. Install Both Towny and Thaumcraft on a Cauldron server for Minecraft 1.7.10
2. Build a golem, give it a "use" core, and tell it to plant something or to use bonemeal on the ground.
3.  In the configuration, ensure that under the "Tekkit" portion, which enables fake players to be ignored for the purposes of Towny's protection, enter in [FakeThaumcraftGolem].
### What is the expected output?
1.  The golem should be able to plant things like saplings, seeds, etc., as well as use bonemeal on grass to create tall grass and flowers.
2.  Currently, "use core" golems are enabled to interact with levers and buttons, but not to plant or use items on blocks.
3.  The configuration to have towny ignore fake players should be able to bypass this problem via entering in the fake player generated by Thaumcraft 4.2.3.5, namely [FakeThaumcraftGolem].
### What is your Towny version?

Release Version: Towny Advanced 0.88.0.0 [CB 1.7.2-R0.3]
### What is your spigot/craftbukkit version?

cauldronbukkit: 1.7.10-1.1207.01.198
cauldron: 1.7.10-2.1403.1.54
### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log : [http://pastebin.com/VSb47YXc](http://pastebin.com/VSb47YXc)
2. Your Towny config.yml: [http://pastebin.com/c2Fwdajf](http://pastebin.com/bUKyBhJR) (Of note, line 411 contains the fake residents portion.)
3. Your townyperms.yml: [http://pastebin.com/c2Fwdajf](http://pastebin.com/c2Fwdajf)
4. Your log's error: Sadly, there is no error message printed to the log.  =(

If further information is needed, please let me know.  I can record a video of the error if needed as well.  Thank you for your time, and for the great plugin.  =)

**Comment by LlmDl** [comment]
The config looks fine to me, as long as those are the right names. Have you given the fake user in your permission plugin the ability to use items? It's towny.claimed.alltowns.itemuse.* or towny.claimed.alltowns.item_use.*, the proper node is on the permission node page of the website.

**Comment by KruhlSentru** [comment]
I've been trying a few methods of implementing the towny.claimed.alltowns.item_use.* permission.  I still have a couple of ideas to try when I get a chance (it takes a bit to keep bringing the server up and down), but so far no luck.  One thing I did want to ask, is what the individual permission nodes were under this permission?  The * doesn't always work, and I'm thinking that one method of trouble shooting would be to put in the individual items themselves and test that way.  For example, are you going by item numbers?  Or, do you need the name, or even the NBT data?

As far as the name, yes, I've checked in more than one site.  Also of interest, there is a second fake player, FakeThaumcraftBore, which can mine without any problems.  In fact, the only affected is the use of items on blocks, including air blocks.  At one point, I did receive some error codes regarding the FakeThaumcraftGolem fake player, but adding them into config only seemed to stop the error messages.

In any case, thanks for your response.  I'm going to probably look into making sure I have some of the sillier points double checked, like the order I give permissions to the golems lol.  I'm not sure bPermissions is capable of recognizing fake players, though.  *shrug*

**Comment by LlmDl** [comment]
What permission plugin are you giving the fakeplayers the nodes in? The .* is short for numbers I believe. If its not numbers its names. You can use the Towny clay brick tool to see what the name/number you need to use for an item is. Just hit a block while you hold the clay brick item. I don't know how you'd figure out an item_name for your purposes. We use bukkit names, which are not always the same as mojang's names/wiki names.

**Comment by KruhlSentru** [comment]
As I mentioned, I'm using bPermissions.  As far as getting the item_name, I also have chestshop, which comes with a /iteminfo command which gives the full ID of the item you are currently holding.  I'll double check with the clay brick to ensure the numbers are the same either way.

For reference, here is a list of my mods/plugins:
Forge Mods:
AntiqueAtlas, DoomlikeDungeons, RoguelikeDungeons, and Thaumcraft
Bukkit Plugins:
bPermissions, Chestshop, Chestshop-Towny, CoreProtect, Craftconomy3, mcMMO, MoneyDrop, PetProtect, PorteCoulissante, ProtocolLib, SwearReplacer, Towny, TownyChat, and Vault

In all cases, I'm using the most up to date non-beta version that would work for Minecraft 1.7.10.

Also, so far no luck.  Is there perhaps another place to add in a permission to a fake player?  I still have yet to try specific item IDs, though.

**Comment by LlmDl** [comment]
You add permissions to fake players in your permission plugin.

**Comment by LlmDl** [comment]
Also just noticed I made a typo with the alltown nodes earlier: http://palmergames.com/towny/towny-permission-nodes/#Admin/Moderator_Nodes
towny.claimed.alltown.item_use.* is what you ought to use, as well as towny.wild.* for the wilderness.

**Comment by KruhlSentru** [comment]
Alright, I got a chance to test a bit more thoroughly.  The permissions were given to FakeThaumcraftGoelm in my permission plugin, but had no effect.  This includes using the direct ID number or item_name.  To be honest, they never needed permissions to do anything before, so I suspect that something about them may be bypassing towny's usual restrictions.

One thing of note - if I don't put the FakeThaumcraftGolem fake player into the Tekkit field, I get this error printed to the console:

[15:18:47] [Server thread/INFO]: Failed to fetch resident: FakeThaumcraftGolem

Placing the FakeThaumcraftGolem into the Tekkit field stops this from showing up, but does not fix the issue with using saplings, bonemeal, etc.

Also, thanks for pointing out the issue with the typo lol.  It always seems to be those tiny errors that mess things up.

P.S.  Has anyone else reported this problem?  I'm just wondering if this is an incompatibility issue between Towny and Thaumcraft 4.  Other than that, I'm running out of ideas.

**Comment by LlmDl** [comment]
Took a look at your config, saplings and bonemeal aren't even defined as item_use_ids. Mods sometimes don't work well with the bukkit API, make sure you're using the right name for your fakeplayers, have the []'s around the name and so on. Use the towny debug stuff to figure out what things are called and assign the fake player (named properly) the nodes in your permission plugin. If that doesn't work, consult the author of teh mod.
