### ISSUE TITLE
suggestion.  playing on 1.8.8 server with excessive passive spawns in town.  is there a way to make town unspawnable for passive without killing them on entry but still having animals breadable?  not sure if this is something you have seen before.  just a thought so players would have to bring initial stock animals in from the wild but could then breed them or keep horses or whatever they wanted.

### ISSUE THREAD

**Issue by popps73x** [LlmDl/Towny#2495]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1.
2.
3.

### What is the expected output?
1.
2.
3.

### What is your Towny version?
Do not say "latest".

### What is your spigot/craftbukkit version?
Do not say "latest".

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
No but there are plugins out there that can control passive spawn rates. Check out Mob Manager.
