### ISSUE TITLE
Towny command suggestion

### ISSUE THREAD

**Issue by Leecook337** [LlmDl/Towny#2496]
Been using Towny for years, over that time I have taught countless people how to use it. I'd like to requests a command:

/t create 
People alwayyyss run that command, sends them an error and then shorty after that they bug staff... If that was a added command to create towns that be amazing!

Thanks, this plugin is the shit,
Lee

**Comment by LlmDl** [comment]
You can create an alias for it yourself. The players who use the ingame help or our website know what the command is.
