### ISSUE TITLE
Bug: Towny data does not save

### ISSUE THREAD

**Issue by CitrusFruit** [LlmDl/Towny#2497]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Every time I reboot my server, Towny rolls back and loses a lot of data, like towns, claims etc. It's been happening for a few days now and my players and I are getting really annoyed. 

### What is the expected output?
1. Rebooting the server causes Towny to rollback data.

### What is your Towny version?
0.91.1.0

### What is your spigot/craftbukkit version?
1.9.4

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : http://pastebin.com/Z924eziY
2. Your Towny config.yml (if using MySQL please remove password,) : http://pastebin.com/fqgNX76v
3. Your townyperms.yml : Not a permissions error as far as I am aware
4. Your log's error : There is no errors regarding Towny

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by ezeiger92** [comment]
Is towny throwing any errors when the server shuts down?

**Comment by LlmDl** [comment]
This could be caused by the server not having permission to save data in the Towny directory I suppose. 

Are you sure the ownership/permissions of teh directory are good?

**Comment by LlmDl** [comment]
No response after 28 days.
