### ISSUE TITLE
Suggestion: Vanish Support

### ISSUE THREAD

**Issue by GershonR** [LlmDl/Towny#2499]
Add support for SuperVanish to display online status as offline in /player and /resident if they are currently vanished.

**Comment by ThemInspectors** [comment]
This has already probably been fixed please actually look at the closed Issues before reporting

**Comment by GershonR** [comment]
Not on latest dev build of towny 0.91.0.2

**Comment by ThemInspectors** [comment]
yes look, #974

**Comment by GershonR** [comment]
That's vanishnopacket i'm asking for SuperVanish because VNP doesen't support Spigot and that was reported 11 months ago as fixed and latest dev build is in April so wasn't applied

**Comment by ThemInspectors** [comment]
*facepalm* Didn't you read it? Also check the committing history and the code.
[https://github.com/ElgarL/Towny/commit/74c23656320ba186d47c2371f3e7143f6c8b346e]

**Comment by GershonR** [comment]
ElgarL committed on Mar 30, 2014

 Towny Advanced 0.91.0.2 17th March 2016 

Means its broken

**Comment by LlmDl** [comment]
This ^

Sounds like SuperVanish doesn't actually use Spigot/Bukkit's player.canSee which is goofy.

**Comment by MyzelYam** [comment]
That's not true, SuperVanish does use player#hidePlayer(..)
https://github.com/MyzelYam/SuperVanish/blob/master/src/de/myzelyam/supervanish/visibility/PlayerHider.java

**Comment by TekkitCommando** [comment]
That is just using a function from there own API called hidePlayer. Not the same thing.

**Comment by MyzelYam** [comment]
No, it is Bukkit's API.
