### ISSUE TITLE
Towny update ?? for 1.10

### ISSUE THREAD

**Issue by jayisback12** [LlmDl/Towny#2500]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1.Town doesnt show any towns list or the town here in the chat
2.Players are having issue
3.Devs on my server having issues with configuring 

### What is the expected output?
1.
2.
3.

### What is your Towny version?
"0.91.1.0"

### What is your spigot/craftbukkit version?
"git-Spigot-687a019-4c1e934"

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by ezeiger92** [comment]
From the template you copied: "Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit."

Use pastebin to upload the files it's asking for if you want your issue to be looked at. You've provided no information, so it's impossible to diagnose problems.

**Comment by LlmDl** [comment]
You skipped the form. Ticket invalid. Maybe try again if you want to put some effort into it.
