### ISSUE TITLE
Server crash apparently linked to Towny

### ISSUE THREAD

**Issue by HollishKid** [LlmDl/Towny#2503]
Hello,

Could someone please help me with the following error? This seems to cause the server to crash regularly, only minutes after start up.
This does not seem to occur when Towny is removed from server.

Thanks for your help!

### What steps will reproduce the problem?
1. None, simply starting the server, whether people connect or not.

### What is your Towny version?
[Server thread/INFO]: Towny version: 0.91.1.0

### What is your spigot/craftbukkit version?
This server is running CraftBukkit version git-Spigot-798f32d-0cd0397 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : http://pastebin.com/376SUTYi
2. Your Towny config.yml : http://pastebin.com/0NR2tMkm
3. Your townyperms.yml : http://pastebin.com/K8YFc3Hc
4. Your log's error : None

(optional) If this is to do with permissions, 
5. Your permissions file : http://pastebin.com/6rvwezFa

(optional) If this is to do with chat,
6. Your chatconfig.yml : http://pastebin.com/bZn8yMuQ
7. Your channels.yml : http://pastebin.com/FyNCgp3W

**Comment by LlmDl** [comment]
This is nothing to do with Towny, your crash report doesn't mention Towny. Make sure your craftbukkit or spigot is up to date for your MC version.
