### ISSUE TITLE
Towny UUID issue

### ISSUE THREAD

**Issue by Leecook337** [LlmDl/Towny#2504]
### What steps will reproduce the problem?
1. Player name change

### What is the expected output?
1. http://pastebin.com/2aiBZ51p

### What is your Towny version?
Towny 0.91.1.0: https://gyazo.com/7236a77076d73b3cfcf93ae690344b47

### What is your spigot/craftbukkit version?
Spigot 1.10: https://gyazo.com/6d18f1c1fc88488c7e2c2dbd1bf375f6

Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your Towny config.yml: FlatFile
All other info is simply not needed.

**Comment by LlmDl** [comment]
Your player somehow changed UUID. You also left out a big chunk of the form. Invalid ticket.
