### ISSUE TITLE
[BUG] Support for switching non-oak doors

### ISSUE THREAD

**Issue by Portanna** [LlmDl/Towny#2509]
### Problem:
Every outsider can switch doors that are not oak-doors due to a lack of support of the new kind of doors. Can you add support for those, so that the switch perm restrictions work properly?

### How to reproduce the problem:
1. Create a Town
2. Disable switch for outsiders
3. Place a non-oak door (for example Acacia)
4. Teleport an outsider to you
5. Tell him to try to switch the door
6. He opens the door even if he is not supposed to

### Towny Version:
Happens on both 0.91.1.2 (DEV) and 0.91.1.0 (RELEASE)

### Spigot Version:
1.8.8

Tested on a testing environment with just Towny and its dependencies all with default config
DEFAULT Towny config.yml, townyperms.yml and spigot/bukkit config files
NO error shows up in console

**Comment by LlmDl** [comment]
Dont skip the forms. Invalid ticket.
