### ISSUE TITLE
Bug Report: Problems with /t set mayor

### ISSUE THREAD

**Issue by Der0zro** [LlmDl/Towny#2510]
Hello,

### What steps will reproduce the problem?
1. Executing command /town set mayor _Player`sName_ by a mayor.

### What is the expected output?
1. The old mayor can destroy in all plots of the town, wihout be mayor (when is no longer mayor).

### What is your Towny version?
0.91.1.0

### What is your spigot/craftbukkit version?
Spigot 1.8.8

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : [http://pastebin.com/sgjupRk1](url)
3. Your townyperms.yml : [http://pastebin.com/MHq4wFxg](url)
4. Your log's error : [http://pastebin.com/8rskWsqb](url)

(optional) If this is to do with permissions, 
5. Your permissions file : 
No, it isn`t.

(optional) If this is to do with chat,
The problem is not from the chat.

Thanks!

**Comment by LlmDl** [comment]
This might still be a permission issue, can you link your full server startup and your permission file please.

**Comment by Der0zro** [comment]
Permission file is from towny, not from another plugin.

**Comment by LlmDl** [comment]
Have you got any Towny nodes in your permission plugin's file? I need to double check that. Please link the file.

**Comment by Der0zro** [comment]
The link for permissions is in my last post....
And no, I don`t have towny permissions in groupmanager...

**Comment by LlmDl** [comment]
I've fixed this and its available in 0.91.1.3 http://towny.palmergames.com/?p=887

Take note that 0.91.1.2 made some very significant changes so you may want to hold off from updating your production server to 0.91.1.3 right away.
