### ISSUE TITLE
Safemode Towny Corruption Re-Opened

### ISSUE THREAD

**Issue by TheCoolsurdy** [LlmDl/Towny#2511]
### All I am and have been asking for is a little line in config.yml to delete towns or nations that lock up Towny just to eliminate the problem. Even I don't know what exactly causes it other than random, normal flatfile corruption.

**IGNORE THE CRASH, THAT WAS NOT DUE TO TOWNY AT ALL. I AM ASKING FOR A SOLUTION TO THE TOWNY CORRUPTION**
### What steps will reproduce the problem?

**It's hard for me to break down what exactly caused it because if I knew I would try to fix it myself. It just happens to new towns/nations**
Own a small to medium sized Towny server for some time (25-35 concurrent players) and the safe mode issue will occur at least every 30 days. **This issue only happens to new towns or nations, and Towny locks to safe mode the next time it's loaded up again (after a restart)**
### What is the expected output?

Towny to read all data normally without any bugs.

**Towny**: 0.91.1.0

**Spigot Version**: git-Spigot-6c9b0a1-de5c261 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
1. Your full server startup from the logs\latest.log: http://pastebin.com/QqRHgE0Z
2. Your Towny config.yml:
3. Your townyperms.yml: http://pastebin.com/SywuPzrK
4. Your log's error : 

[11:48:54] [Server thread/WARN]: [Towny] Error: Loading Error: Exception while reading nation file Blood
[11:48:54] [Server thread/INFO]: [Towny] Loading Error: Could not read nation data 'Blood'.
[11:48:54] [Server thread/INFO]: [Towny] Error: Failed to load!
[11:48:54] [Server thread/INFO]: =============================================================
[11:48:54] [Server thread/INFO]: [WARNING] - ****\* SAFE MODE ****\* 0.91.1.0
[11:48:54] [Server thread/INFO]: =============================================================

**Comment by TekkitCommando** [comment]
That would be a useless config option but you can code it in yourself if you like :P

**Comment by TheCoolsurdy** [comment]
Except I don't know how to code, and it's not really useless as in my case the towns and nations that corrupt are all new and created on that day so there's minimal damage there.

**Comment by medievalevils** [comment]
Hello, a friend of mine's server had this happen twice in 3 days (large server, 40-50 on in the day), and another server 3 times in a month. I do not have files to give you, but I understand that this is a large, persistent and widespread issue with the plugin that usually gets a towny rollback and multiple players killed with the glitch-seizure they have. I can confirm that the issue is fixed if a certain new town is deleted, and the problem starts after a restart. I currently can not find a single fix or reason, and know for sure I am not the only one.

**Comment by LlmDl** [comment]
@medievalevils 
Start a new ticket. If you aren't using the latest dev build then you could try that first. As of about 0.91.1.2 there was a change to the backend that should solve many of the problems in mysql setups.

**Comment by medievalevils** [comment]
@LlmDl The fact that this guy has "Re-Opened" in the title tells me that opening a new ticket won't do much. The information would be the same, and as I said before it's definitely widespread. The servers I was talking about used 1.7.10, the version that almost all modpacks are using.

**Comment by LlmDl** [comment]
Well this ticket is pre-0.91.1.2 and if you're using MC 1.7.10 then you wont be able to use that version of Towny on it.

**Comment by medievalevils** [comment]
Don't you think that's a problem for modpack users? Almost all modpacks are on 1.7.10, and will be for a while. Would you consider making a small fix to the 1.7.10 version, just applying your new fixes? Hundreds of servers and thousands of players would be very grateful.

**Comment by ThemInspectors** [comment]
This is like taking a radio from the 80s and asking RSS feeds to implement into it.

**Comment by medievalevils** [comment]
Except that entire portions of the population still use the radio for the 80's, and the fix is simply applying what was added in 1991?

**Comment by TekkitCommando** [comment]
@medievalevils Most servers are on 1.8+ and the modded server community can use the 1.7.x version (it works just fine.)

**Comment by TekkitCommando** [comment]
@medievalevils If you want your friends 1.7.10 server to have the MySQL fixes then just have him hire some devs to code it or just look at the 1.7.10 code compared to the current and move it over. Not hard.
