### ISSUE TITLE
DefenseTech Mod Nukes wont break blocks with Towny enabled

### ISSUE THREAD

**Issue by TheCrimsonKnight** [LlmDl/Towny#2512]
The problem is that with the Towny plugin installed on the server, DefenseTech (a minecraft mod) nukes do not break blocks even with explosives enabled. After removing TownyAdvanced or using the "/townyworld toggle usingtowny" command to off, the nuke will then break blocks.
### What steps will reproduce the problem?
1. Installed Towny Advanced plugin and DefenseTech mod on the same Cauldron server for 1.7.10
2. Make a nuke go off in the wilderness
### What is the expected output?
1. The nuke should be able to break blocks and create a huge crater in the ground, instead it just shows the particles and plays  the sounds for a nuke but no blocks are destroyed.
2. Turning explosives to true should allow  the nuke to break blocks but either way, it still doesn't unless towny is removed/disabled.
### What is your Towny version?

Towny Version: 0.88.0.0_(1.7.2)
### What is your spigot/craftbukkit version?

cauldron: 1.7.10-2.1403.1.54
### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : http://pastebin.com/iLYXKryC
2. Your Towny config.yml (if using MySQL please remove password,) : http://pastebin.com/j6sKFmTT
3. Your townyperms.yml : http://pastebin.com/Cmc9bmWA
4. Your log's error :  (No errors)

**Comment by LlmDl** [comment]
Sadly there's no development for 1.7 still happening. Still pretty strange that the explosions setting set using /tw toggle explosion wouldnt work.
