### ISSUE TITLE
Suggestion: /t online [nameoftown]

### ISSUE THREAD

**Issue by Neoblade298** [LlmDl/Towny#2514]
Title should mostly clue you in on what's being suggested.

Suggest adding commands like /t online nameoftown and /n online nameoftown (with the permissions ofc) because there are way too many times when I just see players ask in global if there's anyone in this town that can tp them or so-and-so.

Thanks!

**Comment by LlmDl** [comment]
This is now a thing in the forthcoming 0.91.4.6 build of Towny.
