### ISSUE TITLE
Anyone can withdraw, how to limit to just mayor??

### ISSUE THREAD

**Issue by YepImRobbie** [LlmDl/Towny#2515]
Hi, any player can withdraw from the town. How do I make it so ONLY the mayor can? Thanks!!

**Comment by YepImRobbie** [comment]
Negate the 'towny.command.town.withdraw' permission node. The mayor will still be able to withdraw, but residents. not.

**Comment by LlmDl** [comment]
Sounds like you put some towny permission nodes into your permission plugin. 

This is not how to set up towny. The only node you might need to add into your permission plugin is the Towny.wild.* nodes for using the wilderness. The rest are already pre-configured in the townyperms.yml file.

**Comment by YepImRobbie** [comment]
Thank you very much! I'll be removing any other nodes now.

**Comment by YepImRobbie** [comment]
Also what is this 'promote' other towny servers have, it's not a thing on ours.

**Comment by LlmDl** [comment]
I don't know what you're refering to re:'promote', do you mean /t rank  ?
