### ISSUE TITLE
Death tax doesn't go into closed economy

### ISSUE THREAD

**Issue by ThemInspectors** [LlmDl/Towny#2516]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:
### What steps will reproduce the problem?
1. set up death tax
2. set up closed economy
3. somehow die to see where the money goes
### What is the expected output?
1. the death tax goes into the closed economy account
### What is your Towny version?

0.91.1.5.
### What is your spigot/craftbukkit version?

CraftBukkit version git-Spigot-1e4dd71-5e5cf84 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT).
### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : Irrelevant
2. Your Towny config.yml (if using MySQL please remove password,) : http://pastebin.com/yirXdBSS
3. Your townyperms.yml : Irrelevant
4. Your log's error : Irrelevant

(optional) If this is to do with permissions, 
5. Your permissions file : Irrelevant

(optional) If this is to do with chat,
6. Your chatconfig.yml : Irrelevant
7. Your channels.yml : Irrelevant

**Comment by LlmDl** [comment]
You're speaking about the price_death in the config, and specifically when it is not a PVP kill right? Like when a player goes out and gets killed by a skeleton?

**Comment by ThemInspectors** [comment]
in my death tax part of the config i have this http://paste.ubuntu.com/24036081/

**Comment by LlmDl** [comment]
Right, this was from a while ago but I think I looked into the code and this feature was eitehr left out or overwritten. I'll try to get it working again for Non-PVP deaths.

**Comment by LlmDl** [comment]
Fixed as of 0.91.4.6, this still requires testing.
