### ISSUE TITLE
Towny Tax issue

### ISSUE THREAD

**Issue by Leecook337** [LlmDl/Towny#2517]
### What steps will reproduce the problem?
1. /townyadmin newday

### What is the expected output?
1. Errors: http://pastebin.com/SER1KQvd
2. Taxes don't get taken out

### What is your Towny version?
0.91.1.0

### What is your spigot/craftbukkit version?
Spigot 1.10 R0.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : http://pastebin.com/yqYu3eLF
2. Your Towny config.yml (if using MySQL please remove password,) : http://pastebin.com/QpquJPLp
_Reset the towny config and was still getting that error_
3. Your townyperms.yml : http://pastebin.com/t0mtZfnL
4. Your log's error : http://pastebin.com/p3k5NyT4

(optional) If this is to do with permissions, 
5. Your permissions file : N/A

(optional) If this is to do with chat,
6. Your chatconfig.yml : N/A
7. Your channels.yml : N/A

Side note: This started happening after I moved all the files to mysql.

**Comment by LlmDl** [comment]
That error is pointing at Vault's handling of your essentials economy. You're running a UUID version of MC in offline mode, ess eco probably doesn't know what UUID to use for your players and/or towns.

Esseco has been resetting people's bank accounts so I suggest not using it anymore.

**Comment by Leecook337** [comment]
What do you suggest I use? Think this would help: https://www.spigotmc.org/resources/mysql-economy-bridge.6174/

**Comment by LlmDl** [comment]
I don't have any suggestions, I use one that's 5+ years old but it wont work for most servers nowadays.

**Comment by Leecook337** [comment]
Well, thanks for letting me know, I'll let you know if that plugin fixes my issues.
