### ISSUE TITLE
Server locking up and rebooting if town claim is repeated again and again

### ISSUE THREAD

**Issue by DevilAdvocate02** [LlmDl/Towny#2520]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Claiming Plots repeatedly
2.
3.

### What is the expected output?
1. Able to claim Plots
2.
3.

### What is your Towny version?
Do not say "latest".
Version 0.91.1.0

### What is your spigot/craftbukkit version?
Do not say "latest".
Version 1.10.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : http://pastebin.com/p37rMK0h
2. Your Towny config.yml (if using MySQL please remove password,) : http://pastebin.com/iUnpjmzL
3. Your townyperms.yml : default
4. Your log's error : http://pastebin.com/BG39skmA

(optional) If this is to do with permissions, 
5. Your permissions file : http://pastebin.com/dV0EqB0s

(optional) If this is to do with chat,
6. Your chatconfig.yml : default
7. Your channels.yml : default

**Comment by LlmDl** [comment]
Looks like your server isnt able to handle the revert-on-unclaim feature. I'd suggest turning off that feature in each world using /tw toggle revertunclaim. After that is done you can remove the plot-block-data folder in the towny\data\ folder.

**Comment by DevilAdvocate02** [comment]
@ LImDI

Thanks did the trick.

Regards

Devil
