### ISSUE TITLE
SQL problem

### ISSUE THREAD

**Issue by zenandreas** [LlmDl/Towny#2521]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Restart server
2.
3.

### What is the expected output?
1. Towny database isnt loaded and towns are being deleted
2.
3.

### What is your Towny version?
0.91.1.5

### What is your spigot/craftbukkit version?
 git-Spigot-1e4dd71-5e5cf84 (MC: 1.10.2)

### Please use Pastebin.com to link the following files: 

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : http://pastebin.com/UQ9p2Aua
2. Your Towny config.yml (if using MySQL please remove password,) : http://pastebin.com/w1jzcNcJ
3. Your townyperms.yml : http://pastebin.com/hUfYBrBP
4. Your log's error :  http://pastebin.com/RhBVHD55

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Your server is in safe mode, to get it out of safe mode you can follow these instructions: https://code.google.com/archive/a/eclipselabs.org/p/towny/wikis/Troubleshooting.wiki#Towny_locked_in_safe_mode

It's probably easier to convert it back to flatfile while you do this. Please file another ticket if you can figure out how it got into safemode.
