### ISSUE TITLE
Towny spamming chat

### ISSUE THREAD

**Issue by JumanjiCraft** [LlmDl/Towny#2522]
Towny is spamming my chat window with [Town Name] (Settlement) - no pvp
Everytime I move, this message appears.
Here is a screen shot of my chat after about 1 minute of gameplay:
http://prntscr.com/clymu0

### What steps will reproduce the problem?
1. Walking
2. Being inside of my town

### What is your Towny version?
0.91.1.0

### What is your spigot/craftbukkit version?
unknown

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : http://pastebin.com/3mffzesP
2. Your Towny config.yml (if using MySQL please remove password,) : http://pastebin.com/9LfCXqAy
3. Your townyperms.yml : http://pastebin.com/rNixKzJ9
4. Your log's error : none

**Comment by TekkitCommando** [comment]
You are walking in and out of chunks that are owned by that town. This is supposed to happen. If you would like to see it less don't move around in and out of the claimed chunk(s) so much. Alternatively just claim more chunks so you are less likely to walk on a non-claimed one.

**Comment by JumanjiCraft** [comment]
This doesn't seem accurate because at no point (you can see in the screenshot) do I go onto a wilderness plot. I am consistently in my town. I also noticed that if I stop moving for a second, when I move again, it tells me I'm in my town. As far as chunks go, I can get the same spam message from moving 2 or three blocks.

**Comment by JumanjiCraft** [comment]
Also, I checked the permissions from plot to plot. They are identical. The perms are consistent throughout my town.

**Comment by LlmDl** [comment]
TekkitCommando is correct in his guess that you're leaving town, likely because the database has been tampered with. If it were just crossing plots within the town you wouldn't see the Town name in the chat, only the plotname or plotowner. 

You likely manually removed some of the townblocks in your towny database, or manually removed the town but left the townblocks. Converting to flatfile might clean up some of the orphaned townblocks. 

After you move back to mysql consider using the dev builds on the towny website, they are more reliable for mysql databases.

**Comment by JumanjiCraft** [comment]
" If it were just crossing plots within the town you wouldn't see the Town name in the chat, only the plotname or plotowner."

Yes, but this IS what is happening. I am barely moving 2 blocks and both plots I'm standing in are owned by the town. And I get this message. There's no indication that I'm not standing in a town and there's no indication of a missing townblock. What I'm saying is that even if I just stop moving for a few seconds and then as soon as I move again, I get the alert. 

"You likely manually removed some of the townblocks in your towny database"

I haven't tampered with any database.

"Converting to flatfile might clean up some of the orphaned townblocks."

I will try this and report back.

**Comment by JumanjiCraft** [comment]
I am still having the issue after converting to flatfile. 

Here's screenshots:
http://prntscr.com/cml4lz
http://prntscr.com/cml4sc
http://prntscr.com/cml4w2
http://prntscr.com/cml4zs
http://prntscr.com/cml540
http://prntscr.com/cml59j

As you can see, just by moving 2-3 blocks at a time and stopping for less than 30 seconds, the message spams the chat.

**Comment by LlmDl** [comment]
Can you tell me if this happens in other towns?

Can you take a screenshot of the '/towny map big' screen for us.

**Comment by JumanjiCraft** [comment]
This seems to be happening in all towns, but only for my character [HungYungGai]
I was able to confirm that this is only happening to my character by having a friend login with his character using my computer and explore a couple of towns on the same server.

Screenshot of '/towny map big': http://prntscr.com/cmqr9h

**Comment by LlmDl** [comment]
I cant think of a reason why it would only affect one person. The code for that stuff doesn't differentiate between who is moving around. Can you show me a map of the area you took teh screenshots at?

**Comment by JumanjiCraft** [comment]
This is the area where the screen shots were taken:
http://prntscr.com/cmqv88

**Comment by JumanjiCraft** [comment]
The town is in the extreme hills, the unclaimed plots are sheer drops into water, so I wouldn't be crossing into those areas

**Comment by LlmDl** [comment]
Can you show me the permission file you use? There's a possibility that you've added a mode to yourself or your group that might be misinterpreted.

**Comment by JumanjiCraft** [comment]
I have *
http://prntscr.com/cmrjbs
http://prntscr.com/cmrj71

**Comment by LlmDl** [comment]
please link the files on pastebin.com

**Comment by JumanjiCraft** [comment]
I can't because I am using MYSQL with pex. :(
There is no flatfile

**Comment by LlmDl** [comment]
I dont troubleshoot pex anyways

**Comment by JumanjiCraft** [comment]
That's fine, but this isn't really a permissions issue, noted by the fact that there are no towny perms. The owner of the server didn't have this problem and he is also OP with the same perms.

**Comment by LlmDl** [comment]
I don't see how only one player could be affected. It would have to be a resident mode acting on a player which would be permission issue. Its an issue that everyone would have. I can't say why one person would have trouble in any town while no one else has it in any town.

**Comment by JumanjiCraft** [comment]
I understand what you're saying, but this couldn't be a permission issue as my perms are identical to the Owner and other GMs on our server and even when they came to my town to see if it happened to them, it didn't. It's only happening to me. And I don't have any special perms they dont, nor do I have any towny modes turned on. This is not a permissions issue.

**Comment by LlmDl** [comment]
Well pex is unreliable and does all kinds of strange things you never see it again.

I don't know what to say about your issue, it makes no sense and I cannot diagnose it using teh files you've pasted and the screenshots alone.

**Comment by JumanjiCraft** [comment]
I would disagree that pex is unreliable. I've never had an experience using PEX thatcauses "strange things". But regardless, I don't know what else I could possibly provide you that would assist you in a diagnosis of the issue.

**Comment by LlmDl** [comment]
I've troubleshooted towny for 5+ years and have had countless issues traced back to pex, which is why i dont waste anymore time on it. That's my anecdotal evidence. If you want more help join the IRC, its much easier to figure out things when we can maintain a conversation.

**Comment by JumanjiCraft** [comment]
I'll probably do that. I don't mean to sound defensive. I've been using towny and pex for 5+ years and haven't experienced this issue before. But, could be a ghost in the machine.
