### ISSUE TITLE
Can I remove the "PvP" notification in wilderness?

### ISSUE THREAD

**Issue by WakeCa** [LlmDl/Towny#2523]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:
### What steps will reproduce the problem?
1. Leaving a towns claimed area entering the Wilderness
2. Having world pvp in towny enabled and letting Worldguard block pvp(Due to pvp arenas in wilderness)
   https://i.gyazo.com/d3864ecf1d48534af4c2813b52f6cb6d.png
### What is the expected output?
1. Avability to remove the "PvP" from the line when going into wilderness
### What is your Towny version?

0.91.1.0
### What is your spigot/craftbukkit version?

Spigot 1.10.2-R.0.1
### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by TekkitCommando** [comment]
Any specific reason? It has been a while since I used towny but I didnt think it had the PvP tag unless you moved into a claimed town chunk.

**Comment by WakeCa** [comment]
Well. I did /townyworld toggle pvp to toggle the pvp "On" in towny.
as I use Worldguard to disable pvp in the __global__ region, which makes it easier to create pvp arenas and just make a new region for it with pvp enabled, else towny overrides it and blocks pvp everywhere :/

**Comment by LlmDl** [comment]
I thought this was going to require some actual coding on my part because we'd not made it configurable but no, all you have to do is set this in your config: area_wilderness_pvp: '', removing the %s
