### ISSUE TITLE
Towny locked into safemode whenever config is changed!!

### ISSUE THREAD

**Issue by dannyboy169373** [LlmDl/Towny#2525]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1.Change config of towny
2.Restart server
3.

### What is the expected output?
1.Towny will be locked in safe mode
2.
3.

### What is your Towny version?
Do not say "latest".
v0.91.1.0

### What is your spigot/craftbukkit version?
Do not say "latest".
Spigot 1.10

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
http://pastebin.com/WbVYcj84
2. Your Towny config.yml (if using MySQL please remove password,) 
This does not apply as we cannot change the config.
3. Your townyperms.yml :

4. Your log's error : 
When i go into the log helper, all it says is that there is a townychat error and the error could not be determined.

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

I don't know what to do please help. I dont think that it is a problem with towny conflicting with any other plugins. Plus i have run the towny debug and checked the data files and there is no conflicting data. This is real odd. We reset a lot of plugins and it still didnt work.
Before we did this we got this error : Could not pass event PlayerTeleportEvent to towny
But now it doesnt show up but towny is still being stupid.
PLEASE HELP. I dont really care if this takes you a fair bit of time to solve i just wantt help. The other owner and i have also contacted the host to see if they can help. We have spent so long trying to fix this but nothing has worked. You are pretty much our final hope.

**Comment by LlmDl** [comment]
What are you using to edit the config?

The log shows an error in the regex section of the config, are you changing it?

Are you trying to put any special characters that contain accents, umlets, etc into the config?

**Comment by dannyboy169373** [comment]
To edit the config i am using the lagacy file manager on the host providers control panel.

The only thing we change is the config. Just one simple setting will put it into safe mode

And no we have not put any special characters into the config.

**Comment by LlmDl** [comment]
Sounds like you should be relying less on that legacy file manager and more on an FTP client + text editor combo.

**Comment by dannyboy169373** [comment]
Thank you so much LlmDI you are an absolute legend. You are so great. Our host provider sent us back an email saying that it probably wasn't working because towny is probably outdated xD. 
It works perfectly. I can't thank you enough we had so much trouble with it and couldn't find what was wrong.
