### ISSUE TITLE
Please fix bug revert on unclaim towny

### ISSUE THREAD

**Issue by vanthoi** [LlmDl/Towny#2526]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Bug revert item on unclaim
2. If the player puts the previous block. After that create new town and break blocks away. Then delete town. The blocks that still revert back. Although the configuration is ignored!

Example: The iron ore and cauldron

### What is your Towny version?
I use towny ver Towny Advanced 0.91.1.0 after update to Towny Advanced 0.91.1.5 still not fix! 

### What is your spigot/craftbukkit version?

This server is running CraftBukkit version git-Spigot-850da7e-b5fb9a1 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : Not error from console
2. Your Towny config.yml (if using MySQL please remove password,) : http://pastebin.com/QneYKU7r
3. Your townyperms.yml :
4. Your log's error : Not error

**Comment by LlmDl** [comment]
Read the install guide over again, or the config section you're editing.

That section of the config is only default settings for newly created worlds.

Use the /tw toggle command or edit the Towny\data\worlds\worldname.txt files
