### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by goldenmasterly** [LlmDl/Towny#2529]
suggestion for towny is to allow a player to set multiple towns that could be enabled/disabled via config and in game command because i want to use it on a small server me and some friends have but with 15 towns and 5 players it a little annoying that we can only claim 1 a player make 10/15 towns unclaimed

**Comment by TekkitCommando** [comment]
Is this a way to get around the chunk claim limit? You can up the limit in the config and you can also use the towny admin command to add more chunks able to be claimed to your town.

**Comment by LlmDl** [comment]
Enable more chunks using /ta givebonus # and you can set aside a town using the /ta set mayor to make the mayor an NPC so you can make other towns without losing the first one.
