### ISSUE TITLE
Deleted Nations and Towns with MySQL

### ISSUE THREAD

**Issue by gerardvanschip** [LlmDl/Towny#2530]
I moved from flatfile to mysql for speed and so far that has worked out great till today when a nation got accidentally deleted. This if course meant all claims, plots etc were gone. With flatfile you can dig out the deleted files and with a bit of work have it all back up. Is that or is that not possible with mysql. Its not clear either way. Thanks.

### What steps will reproduce the problem?
1. delete a town or a nation

### What is the expected output?
1. have them be marked as deleted so errors or mistakes can be reversed 

### What is your Towny version?
0.91.1.0

### What is your spigot/craftbukkit version?
1.11

### Please use Pastebin.com to link the following files:
I'm happy to supply all these details but this is not so much a bug as a question about a feature. Is it possible to revert town or nation deletes when using MySQL. I could not find anything online about it.

**Comment by TekkitCommando** [comment]
You want it to stay in the database but just have it set to deleted as a database value? Is that what you are asking? If so, wouldn't that means gigabytes of useless storage space taken up from deleted towns for big servers?

**Comment by LlmDl** [comment]
We already have a warning message when a town is deleted. When a nation is deleted there's no claims to remove. This is the part about keeping backups of your own when you use mysql. If you don't want to do that you can use flatfile. There is nearly 0 speed difference between mysql and flatfile as both are used in ram.

**Comment by gerardvanschip** [comment]
No warning. The capital of a large nation was deleted and boom, whole nation gone, no warning. Also I understand about the big servers but most servers are small, there are only a few mega servers. Our whole mysql database is under 100 and has stats 3, mcmmo  and towny data in it. Also you could have it as an option in the config file, one that is off by default. Just flag something as deleted but staying for say 48 hours. An administrator could reverse that deletion.

**Comment by TekkitCommando** [comment]
Adding a new value to the database would corrupt the rest of the towns more than likely. There would have to be a converter scripted as well. This seems more of something that should be done as a private update for a server. 

Ofc I am just a community member and it isn't up to me lol.

**Comment by LlmDl** [comment]
I'll need you to provide real steps to recreate this problem, so that I can reproduce the not getting a warning message.
