### ISSUE TITLE
False Already in Town Message

### ISSUE THREAD

**Issue by CitrusSponge** [LlmDl/Towny#2531]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1.Someone invites a player to their town
2.They accept the invitation and join the town, and are not already in a town
3.

### What is the expected output?
1."You are already in a town"
2.
3.

### What is your Towny version?
0.91.1.5

### What is your spigot/craftbukkit version?
Paper Spigot 1.10.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : [latest log.txt](https://github.com/LlmDl/Towny/files/615131/latest.log.txt)
2. Your Towny config.yml (if using MySQL please remove password,) : [config.yml.zip](https://github.com/LlmDl/Towny/files/615138/config.yml.zip)

3. Your townyperms.yml :[townyperms.yml.zip](https://github.com/LlmDl/Towny/files/615135/townyperms.yml.zip)

4. Your log's error : Doesnt have one

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :[ChatConfig yml.zip](https://github.com/LlmDl/Towny/files/615134/ChatConfig.yml.zip)
7. Your channels.yml :

**Comment by TekkitCommando** [comment]
This isn't really gonna help you with the "player already in town" message but that is the spammiest console log I have ever seen. "Ambiguous plugin name" means you have two jars of the same plugin uploaded.

**Comment by CitrusSponge** [comment]
Okay this is a pretty new server, and I try to get as much as I can fixed with the time I have :D But, thanks for the help that I didn't ask for *no sarcasm*. But, could someone try to fix this problem as fast as possible, because some players are getting pissed. Maybe @LlmDl ? Thank you

**Comment by LlmDl** [comment]
I don't quite follow the issue here, are you saying that if you invite someone to town that is already in a town, the inviter isn't getting a message saying that they're already in a town?

**Comment by CitrusSponge** [comment]
@LlmDl No, what is happening is that when a there is a player that is NOT in a town that is invited to a town. Then, that player that is NOT in a town accepts the invite, it says "You are already in a town", but it adds them to the town they were invited to. So, my problem is that it gives the wrong message.

**Comment by LlmDl** [comment]
OK, I just tested using 0.91.1.6 (though that shouldn't make a difference,) and did not get that message. Is there some other step I'm missing. What I did was:

With Player A: Left town.
With Mayor B: Invited to town.
With Player A: Accepted invite. Joined town with the proper message displayed.


In your case has Player A received more than one invite or something?

**Comment by CitrusSponge** [comment]
@LlmDl You did it right, but in my server the proper message isn't displayed.
![screen shot 2016-12-07 at 10 10 04 pm](https://cloud.githubusercontent.com/assets/24213711/20997329/163e43bc-bcca-11e6-95ef-db28212ad80b.png)

**Comment by LlmDl** [comment]
Heh, based on the grammar of it I think I might know what's going on. I'll take a look at the code for it now.

**Comment by LlmDl** [comment]
Looks like it only happens if you're missing our Questioner.jar. You should get it and this will stop.
