### ISSUE TITLE
Disconnected when perform command "/t new or /t claim"

### ISSUE THREAD

**Issue by dinhthi2001** [LlmDl/Towny#2534]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Disconnected when perform command "/t new or /t claim"
2.
3.

### What is the expected output?
1. 
```
[21:52:02] [Server thread/INFO]: [PLAYER_COMMAND] _DinhThi_: /t new xyzhehe
[21:52:43] [pool-10-thread-1/INFO]: Creating empty config: C:\Users\Administrator\Desktop\MienNamSsII\plugins\Essentials\userdata\73f5e68e-50b4-3f6d-a859-174ff3851907.yml
[21:52:44] [Server thread/INFO]: [Global Msg] _DinhThi_ created a new town called xyzhehe
[21:52:44] [Server thread/INFO]: _DinhThi_ lost connection: Disconnected
[21:52:44] [Server thread/INFO]: [Admin] _DinhThi_ left game.
```
2. 
3.

### What is your Towny version?
Do not say "latest".
v0.91.1.0

### What is your spigot/craftbukkit version?
Do not say "latest".
Spigot 1.8.8

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : http://pastebin.com/Mhp7Bb4H
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Could be related to Essentials, could be related to TownyOfflineFix (which I have no information about), no towny error though.

**Comment by dinhthi2001** [comment]
In another server using /t new or /t claim is normal, but in this server, it looks like what i posted.

**Comment by dinhthi2001** [comment]
Disconnected with msg : "The server you were previously on went down, you have been connected to a fallback server"

**Comment by dinhthi2001** [comment]
Here is error when use command /t claim : http://pastebin.com/YuS4X1X7

**Comment by LlmDl** [comment]
Looks like a problem with the snapshot being taken of the plot. That snapshot is the one used in the revert-on-unclaim feature. Some servers cannot handle that extra load. You can turn it off using '/tw toggle revertunclaim' in each one of your worlds.

**Comment by dinhthi2001** [comment]
> > [22:03:40] [Server thread/INFO]: [Towny] Enabling Towny v0.91.1.0
> [22:03:40] [Server thread/INFO]: ====================      Towny      ========================
> [22:03:40] [Server thread/INFO]: [Towny] Database: [Load] mysql [Save] mysql
> [22:03:40] [Server thread/WARN]: [Towny] Error: SQL: Load Town unknown Error - 
> [22:03:40] [Server thread/WARN]: com.palmergames.bukkit.towny.exceptions.AlreadyRegisteredException: §ccaptaiin12343 đã là cư dân thị trấn MeoXinhGai (Hamlet).
> [22:03:40] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.object.Town.addResidentCheck(Town.java:206)
> [22:03:40] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.object.Town.addResident(Town.java:192)
> [22:03:40] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.db.TownySQLSource.loadTown(TownySQLSource.java:774)
> [22:03:40] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.db.TownyDataSource.loadTowns(TownyDataSource.java:247)
> [22:03:40] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.db.TownyDataSource.loadAll(TownyDataSource.java:99)
> [22:03:40] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.object.TownyUniverse.loadDatabase(TownyUniverse.java:326)
> [22:03:40] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.object.TownyUniverse.loadSettings(TownyUniverse.java:277)
> [22:03:40] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.Towny.load(Towny.java:217)
> [22:03:40] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.Towny.onEnable(Towny.java:112)
> [22:03:40] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
> [22:03:40] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
> [22:03:40] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
> [22:03:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
> [22:03:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
> [22:03:40] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
> [22:03:40] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
> [22:03:40] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
> [22:03:40] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
> [22:03:40] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
> [22:03:40] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
> [22:03:40] [Server thread/INFO]: [Towny] Loading Error: Could not read town data OverDown'.
> [22:03:40] [Server thread/INFO]: [Towny] Error: Failed to load!
> [22:03:40] [Server thread/INFO]: =============================================================
How to fix error ?

**Comment by LlmDl** [comment]
There is a player ccaptaiin12343 who is in 2 towns at once, remove him from either OverDown or MeoXinhGai
