### ISSUE TITLE
Shulker Box Bypasses Town Claims

### ISSUE THREAD

**Issue by ThatProgrammerRian** [LlmDl/Towny#2535]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Place Shulker box in your town
2. Get a non town resident to open the box
3. Repeat

### What is the expected output?
1. Player can open the box and retrieve items

### What is your Towny version?
Do not say "latest". 0.91.1.0

### What is your spigot/craftbukkit version?
Do not say "latest". git-Bukkit-622630c API Version 1.11-RO.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : No Access granted by host
2. Your Towny config.yml (if using MySQL please remove password,) : Default
3. Your townyperms.yml : Default

**Comment by LlmDl** [comment]
I'll be adding them into the default config when I do a build made for 1.11, but until then you can just add the shulker boxes to the config's switch list. You have to add each colour, RED_SHULKER_BOX and so on.

**Comment by gerardvanschip** [comment]
I dont seem to have a switch list in my config?

**Comment by LlmDl** [comment]
@gerardvanschip You ought to have a switch_ids: list
