### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by nathan93** [LlmDl/Towny#2537]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Cannot edit and save config. Upon uploading via FTP to server, error produced: 
`Copying files to remote side failed.
Could not create file.`
Or trying to edit via server command center, error "Could not save" is produced. 

### What is the expected output?
1. 
2.
3.

### What is your Towny version?
0.91.1.0

### What is your spigot/craftbukkit version?
Spigot 1.10.2-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : http://pastebin.com/f8z16Mej
2. Your Towny config.yml : http://pastebin.com/FhGWiwng
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by TekkitCommando** [comment]
I'm sure because you closed you found this out but that's an FTP permission error.
