### ISSUE TITLE
[Suggestion] Separate permissions for using inline chat color and format codes

### ISSUE THREAD

**Issue by nathan93** [LlmDl/Towny#2540]
Hello! Would it be possible to use separate permissions for chat formatting, instead of grouping color and all the formatting into one node as it is now? Maybe have two permissions such as _townychat.chat.color_ and _townychat.chat.format_ or separate everything like as follows;

townychat.chat.color
townychat.chat.bold
townychat.chat.magic
townychat.chat.strikethrough
townychat.chat.underline
townychat.chat.italic

**Comment by WaterQuarks** [comment]
one year bump

**Comment by LlmDl** [comment]
This is now a part of the forthcoming TownyChat 0.51, 
```
v0.51:
    - New Permission node: townychat.chat.format.*
      - default: op
      - Provides the ability to use bold, italics, etc in chat.
      - Child nodes: 
        - townychat.chat.format.bold
        - townychat.chat.format.italic
        - townychat.chat.format.magic
        - townychat.chat.format.undeline
        - townychat.chat.format.strike
    - New Permission node: townychat.chat.format.reset
      - default: everyone
      - Provides the ability to reset chat formatting to default using &r.
```
