### ISSUE TITLE
Mobs spawn in towns when they are toggled off

### ISSUE THREAD

**Issue by Ice2496** [LlmDl/Towny#2541]
Our server has currently updated to 1.11.2 and when I joined the Towny server to see how the update was, mobs were spawning all over the town even though they are toggled off.

### What is your Towny version?
dev build 1.8.4

### What is your spigot/craftbukkit version?
0.91.1.7

**Comment by LlmDl** [comment]
You skipped the form so I'm going to close this ticket. This problem is usually caused by not using a Citizens meant for the version of MC you're using.

**Comment by Ice2496** [comment]
Is citizens required because we were forced to get rid of it

**Comment by LlmDl** [comment]
No it's not required. Using a version of citizens that is made for an older version of MC is why you would be having this problem.

**Comment by Ice2496** [comment]
There are also no errors showing at all so I couldn't put it above

**Comment by Ice2496** [comment]
can you confirm that the mobs don't spawn in towns on your world with the latest build?

**Comment by LlmDl** [comment]
I can't help you, start a new ticket and don't skip the form.
