### ISSUE TITLE
Mobs spawn even when they are toggled off

### ISSUE THREAD

**Issue by Ice2496** [LlmDl/Towny#2542]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1.Make a 3x3 test town
2. have mobs toggled off
3. put spawner in the middle and watch them not disappear like they should
4. Have the time set to night and watch the mobs spawn in town

### What is the expected output?
1.Have the mobs not spawn
2.Have them disappear when they spawn from the spawner
3.

### What is your Towny version?
0.91.1.7

### What is your spigot/craftbukkit version?
1.11.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :http://pastebin.com/raw/uQPUyhrC
2. Your Towny config.yml (if using MySQL please remove password,) :http://pastebin.com/raw/WR0gs0x1
3. Your townyperms.yml :http://pastebin.com/raw/W31zQR4d
4. Your log's error : http://pastebin.com/raw/9qnnaQXF

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Your Citizens is out of date for 1.11:

https://dev.bukkit.org/projects/citizens/files/2360848

**Comment by Ice2496** [comment]
We don;t have citizens is the issue

**Comment by LlmDl** [comment]
Sure you do: 

2017-01-13 12:11:01 [INFO] [Citizens] Loading Citizens v2.0.19-SNAPSHOT (build 1374)
