### ISSUE TITLE
Pistons and Stickypistons are able to move blocks if placed on a chunk/plot border.

### ISSUE THREAD

**Issue by NathanAdhitya** [LlmDl/Towny#2543]
### What steps will reproduce the problem?
1. Place a piston and a sticky piston, directly at a border of a plot, facing another plot/chunk
2. Activate the piston.
3. Blocks would move.

### What is the expected output?
Piston / StickyPiston would not extend.

### What is your Towny version?
Towny Advanced 0.91.1.7

### What is your spigot/craftbukkit version?
PaperSpigot 1.11.2 (paperclip-1021)

### Files

I do not think the files are neccesary. There were no config regarding this bug anywhere. (Default Config for version 0.91.1.7. Complete untouched.)
Server logs didn't produce any errors either.

**Comment by LlmDl** [comment]
Skipped form. Invalid ticket. Resubmit.

On a side note: it could be PaperSpigot at fault here.

**Comment by NathanAdhitya** [comment]
I'll test with regular spigot.

**Comment by NathanAdhitya** [comment]
Oh, and what did I missed?
