### ISSUE TITLE
TownyAdvence Instalation Problem

### ISSUE THREAD

**Issue by naskopicha** [LlmDl/Towny#2548]
Probelm Instaling TownyAdvence
When i run TownyAdvence 0.91.1.0 at console i see this 
"ERROR Error occurred while enabling iConomy v5.01 (Is it up to date?)"
I put Here Console Log
Can you help me pls?
### What is your Towny version?
0.91.1.0
### What is your spigot/craftbukkit version?
1.8.3

### Console Log
http://pastebin.com/1taXVMg0

**Comment by LlmDl** [comment]
Its not able to find the h2.jar you need to run ico 5.01, try this instead: https://dl.dropboxusercontent.com/u/31426972/h2.jar
