### ISSUE TITLE
Corrupted townblocks are back again

### ISSUE THREAD

**Issue by TheCoolsurdy** [LlmDl/Towny#2549]
###What steps will reproduce the problem?
1. Get a town with a lot of townblocks (over 1000-2000)
2. Delete the town using /t delete
3. The server needs to crash (and probably will if the town has enough townblocks)
4. The town will be deleted but every plot that once belonged to the town will be in a 'corrupted' state

The corrupted state of townblocks:
In /towny map they will appear unclaimed as grey -'s.
When doing /t here it will say "The TownBlock at () is not registered to a town."
However, when typing /t claim it will say "This area () already belongs to someone"
When traveling OUT of the corrupted townblock and into Wilderness, it will state "~ Wilderness - (PvP)" however when you travel from Wilderness to the corrupted townblock it will not say anything.

### What is your Towny version?
Towny version 0.91.1.0

### What is your spigot/craftbukkit version?
Spigot 1.8.8-R.01-SNAPSHOT

**Comment by LlmDl** [comment]
I'm guessing you have teh revert-on-unclaim feature activated and the server crashes when it attempts to start that process. With the town gone and the townblocks files in the townblocks folders still around you will see problems with orphaned townblocks. I thought I had created a way for towny to fix itself in flatfile but as you skipped the form I can't say much about this ticket.

Resubmit and don't skip the form.
