### ISSUE TITLE
Suggestion: Using Worldedit when replacing disbanded towns + Saving town and wilderness regions in .schematic format

### ISSUE THREAD

**Issue by Portanna** [LlmDl/Towny#2551]
In order to make Towny **more compatible** and **easier** to manage, I think that implementing **WorldEdit features** in it would be much better.

**1)** Using Worldedit when replacing a disbanded town with the wilderness snapshot taken when it was claimed. Would be done in an instant and without lag (servers with 3+ big towns disbanded at the same time nearly crash the server or kick everybody for 5 mins). This way the process could be queued and optimized by Worldedit addons like FastAsyncWorldedit (which is open source and offers a great API) or AsyncWorldedit.
**2)** Saving a schematic when disbanding a town so that people could easily recover the deleted town if it's deleted for error
**2)** Saving wilderness snapshots in schematic format, so that people could easily recover a certain wilderness claim.
**3)** Generally speaking, **always using schematics for saving claims and wilderness**.

This change in the Towny plugin could help a lot of server owners, because **backups would be more lightweight and everything could be restorable**.

If this is not possible, I would at least suggest to add block logging compatibility to plugins like CoreProtect or BlocksHub so that when a Town is deleted a server owner can "rollback" the town to its previous state.

**Comment by LlmDl** [comment]
Sorry, wont be using WE schematics. Most of what you want is easy to self-manage using your own backups and MCEdit.
