### ISSUE TITLE
Town members can attack their own town.

### ISSUE THREAD

**Issue by KarlOfDuty** [LlmDl/Towny#2552]
### What steps will reproduce the problem?
Going to one of the border plots of my own town and starting the war event, then it captures my own plot claiming my town took the plot from itself. (I have set the HP to 1 for this test)

Not sure if it's related, but I use gold ingots as currency and even if I have set a base spoils number in the config all nations always get 0 gold at the end of the war regardless of points.

### What is the expected output?
Not being able to attack your own town?

### What is your Towny version?
Tested in 0.91.1.0 and 0.91.1.7

### What is your spigot/craftbukkit version?
Tested in Spigot 1.10 and 1.11 (the latter specifically spigot-1.11.2-R0.1-SNAPSHOT.jar)

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : [http://pastebin.com/mXYDF0LY](http://pastebin.com/mXYDF0LY)
2. Your Towny config.yml (if using MySQL please remove password,) : [http://pastebin.com/tvuxFh0Y](http://pastebin.com/tvuxFh0Y)
3. Your townyperms.yml : [http://pastebin.com/x2KR9jwN](http://pastebin.com/x2KR9jwN)
4. Your log's error : None, but here is the message it gives: 
```
[16:39:25 INFO]: [Town Msg] Karlskrona: Your town ran out of funds to support yourself in war.
[16:39:25 INFO]: [Global Msg] [War] Karlskrona was awarded 100 points for eliminating the nation Sweden!
[16:39:25 INFO]: [Global Msg] [War] Karlskrona was awarded 30 points for eliminating the town Karlskrona! (122 town blocks captured)
```

(optional) If this is to do with permissions, 
5. Your permissions file : I have no idea if it's related, but I'll post this too, [http://pastebin.com/scPuqXsr](http://pastebin.com/scPuqXsr) (bpermissions)

(optional) If this is to do with chat,
6. Your chatconfig.yml : -
7. Your channels.yml : -

**Comment by KarlOfDuty** [comment]
Actually, there is an error after the war ends:


[17:01:55 WARN]: [Towny] Plugin Towny v0.91.1.7 generated an exception while executing task 42
java.lang.NullPointerException
        at com.palmergames.bukkit.towny.object.TownyUniverse.clearWarEvent(TownyUniverse.java:422) ~[?:?]
        at com.palmergames.bukkit.towny.war.eventwar.WarTimerTask.run(WarTimerTask.java:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-0b1090d-7fdc749]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-0b1090d-7fdc749]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by LlmDl** [comment]
This is using the /ta toggle war event or the flag war ?

**Comment by KarlOfDuty** [comment]
The /ta toggle war

**Comment by LlmDl** [comment]
I've updated Towny to 1.9 this last week and will test this as I begin to build Towny for 1.10/1.11. This did not happen when we were working on the war event and actively testing it. 

As for the towny war spoils not paying out into Gringott's I'm not entirely surprised. Does gringott's work for depositing and withdrawing from your town and nation banks?

**Comment by KarlOfDuty** [comment]
The actual transactions when you take a town block work, it's just the war spoils at the end that says 0. And yes, depositing and withdrawing from the vaults works.

I'm gonna try to find out if this still happens when I only use towny and no other plugins. I have only had access to a single minecraft account which has made troubleshooting difficult as I have only been able to have one town and thus not start a war when building it from scratch. 

But I'm currently uploading this to a server connected to the internet instead of my usual test setup which is just plugged directly into my home PC via ethernet, so I'll be able to test it out with another person soon.

**Comment by LlmDl** [comment]
Keep this updated with your findings, the 1.10 update doesn't look like it will have much work at all involved, the 1.11 update shouldn't be much either from what I've seen so far.

**Comment by LlmDl** [comment]
Just thought, if there's only one nation involved in a war I believe it shouldn't start at all, it may be starting and ending immediately. Because your townblocks have a single HP it may appear that you're taking one but it might just be that the war is ending right after it begins. It really shouldn't be starting at all without at least 2 nations who are enemies of each other.

**Comment by KarlOfDuty** [comment]
No, I haven't even tried it with a single nation. When I tried it I just used a backup from our live server which has many nations.

**Comment by LlmDl** [comment]
In that backup, there are nations who've set each other as enemies?

**Comment by KarlOfDuty** [comment]
I am not sure, I wasn't aware that was required for the event war. I could try it out.

**Comment by LlmDl** [comment]
Check a couple nations on your main server by doing /Nation {name}, see if any have any enemies listed.

**Comment by KarlOfDuty** [comment]
Yes, I found at least one nation has an enemy.

**Comment by KarlOfDuty** [comment]
Not the one I'm in which I have used to test things though.

**Comment by KarlOfDuty** [comment]
I also just tried to start the war while my nation had an enemy and the same thing happened. The new test server also refuses to install java, so it might take a while before I can try a clean install.

**Comment by KarlOfDuty** [comment]
We still tried a war today and it was a buggy mess. I have some more bugs to report:

The greifing seems to be inverted, when a town isn't taken over it can be looted, but as soon as it is taken it becomes protected again.

Going neutral doesn't seem to protect except from plots being taken, people can still greif and kill.

Being someone's ally doesn't do anything but I'm not sure if it's supposed to anyway.

This was with greifing turned on. We first had it off thinking that would let players greif only when they had seiged the plot down, but it just turned it off completely. Once again, not sure if this is intentional.

**Comment by KarlOfDuty** [comment]
Another update:

The problems are still present in the latest version of Towny we have tried (the 1.10.2 one).

Also, we have now tried running the server completely without any other plugins and having deleted the whole Towny folder and the problems still persist. 

The "attacking your own land" bug can be overridden by turning on the plot healing option in the config. It doesn't just counter it by both healing and attacking, it fixes the bug completely.

**Comment by KarlOfDuty** [comment]
Also, we tried some things with the flag war system and found the following bugs (same version of towny as above): 

The Warzone block permissions do not seem to work. Anyone can build as soon as the flag has been placed completely ignoring the editable_materials line.
```
    editable_materials: fence
    item_use: 'true'
    switch: 'false'
```

The number of players needed in both town and nation is checked for both attacking and defending town, even though the comment says it's only for the defending town.

And a small thing, the comment for light_block is wrong and misleading.

**Comment by LlmDl** [comment]
The flag war isn't supported/developed anymore. 

I'll look into the war stuff once I'm done with 1.11.2, we only ever tested it with the healing on.

**Comment by LlmDl** [comment]
Closing this, this was fixed.
