### ISSUE TITLE
MySQL SSL connection attempts.

### ISSUE THREAD

**Issue by Carbonawk** [LlmDl/Towny#2553]
The  plugin wants to connect to MySQL and gives an error due to no verification. So it seems like towny wants to use SSL. However, I see no way to configure towny with certifiications. Please disable SSL connection attempts within the plugin.  (&useSSL=false)

### What steps will reproduce the problem?
1. reconnect to the Mysql server.

### What is the expected output?
1. no warning.

### What is your Towny version?
0.91.1.7 after changing to the latest version 0.91.2.0

### What is your spigot/craftbukkit version?
This server is running CraftBukkit version git-Spigot-b32c8f8-4d3bf20 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. http://pastebin.com/GgZe8Ehw
2. http://pastebin.com/yCbfD4Nx
3. http://pastebin.com/gTbSBmAD
4. http://pastebin.com/Y6RbQ9EB

(optional) If this is to do with permissions, 
5. -

(optional) If this is to do with chat,
6. -
7. -

**Comment by LlmDl** [comment]
If you aren't going to use SSL for your MYSQL server, you add "-DuseSSL=false" before "-jar" in your server start command.

**Comment by Carbonawk** [comment]
That works. But, why does towny not deal with this?

**Comment by Carbonawk** [comment]
I suppose that's a way of dealing with it. Why does towny not though?

**Comment by LlmDl** [comment]
The change is something that Spigot made, which is following MYSQL's best-practice of using SSL. Towny could decide to add a useSSL flag so people can disable it on just Towny,but that would end up missing the point that Spigot and MYSQL are trying to make. Every plugin that an admin uses which has a MYSQL database would require a disable SSL option, if the admin didn't want to use SSL, it makes more sense to set the entire server to ignore SSL in the startup rather than having to disable each individual plugin.

**Comment by Carbonawk** [comment]
Then I suppose having  SSL disabled completely on the SQL server doesn't matter either?

![i7p2n4o 1](https://cloud.githubusercontent.com/assets/25295327/22225996/db9b58ce-e1c4-11e6-8ed3-c21c6ecf73dd.jpg)

**Comment by LlmDl** [comment]
Guess not. If you weren't hosting the MYSQL on localhost I'd say you ought to use SSL but I don't think it matters much in your situation.

**Comment by Carbonawk** [comment]
Yeah, it's not remote MySQL, so it really doesn't really matter 👍 
Thanks for the help.

**Comment by Carbonawk** [comment]
I have been using "-DuseSSL=false" and it has not changed anything for me. I do use multicraft but I suppose that shouldn't matter as it's recognized. I tried "-useSSL=false" to test that and obviously did not work.

Still get the warning regardless of the value above.
If you have any other suggestions I gladly hear them.

**Comment by LlmDl** [comment]
Maybe you should use SSL then?

**Comment by jordanwilliams1** [comment]
Dose towny run fine with it saying about SSL? I've seen this error a ton and it seems to be running fine just spamming the error now and again. I Would prefer if it didn't though.

**Comment by Carbonawk** [comment]
Well as I see it, it runs fine.

However, these warnings are annoying and can easily be changed by a small change in the plugin.
Enabling SSL is not something many would do on a game server as it would use more power and bandwidth. 

Disabling SSL in the command line does not seem to affect towny at all as mentioned above.
So where does it leave us? well, we just have to "accept" this warning over and over or downgrade to a lower version of MySQL. connector. Which again, may not be acceptable.

**Comment by winnerDash101** [comment]
i got a new microphone !

**Comment by LlmDl** [comment]
Part of 0.91.4.8
```

    - New Config Option: plugin.database.sql.ssl
      - Defaults to false.
      - Adapts to Spigot's recommendation that MySQL databases use SSL.  
```
