### ISSUE TITLE
Towny command Crashes Minecraft Server

### ISSUE THREAD

**Issue by p376em** [LlmDl/Towny#2557]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. setup spigot 1.11.2 spigot-1.11.2-R0.1-SNAPSHOT.jar
2.add essentials towny and vault
3. using the towny default config issue /town new saphira P376em

### What is the expected output?
1. The Server Should Crash see log file

### What is your Towny version?
0.91.4.0 and 0.91.3.0 

### What is your spigot/craftbukkit version?
spigot-1.11.2-R0.1-SNAPSHOT.jar

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : check the log from 22:36:54
[2017-02-04-22.txt](https://github.com/LlmDl/Towny/files/754205/2017-02-04-22.txt)

2. Your Towny config.yml (if using MySQL please remove password,) :[config.txt](https://github.com/LlmDl/Towny/files/754470/config.txt)
3. Your townyperms.yml :[townyperms.txt](https://github.com/LlmDl/Towny/files/754471/townyperms.txt)
4. Your log's error : 

please see attached for the files above

**Comment by p376em** [comment]
git-Spigot-7d78b81-f9e0440 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by LlmDl** [comment]
It looks like your server isnt allowed to write the plot-block-data used in the revert-on-unclaim. It may be a server permissions issue, or it could be that the feature is too stressful on your server hardware. Try turning the feature off using /tw toggle revertunclaim

**Comment by p376em** [comment]
The server runs amd 9590 5ghz and 32gb ram
it also crashes on the /town new command

**Comment by p376em** [comment]
Many thanks the issue is resolevd and i will colose the issue if i can very helpful
