### ISSUE TITLE
/plot still shows command help while towny is disabled

### ISSUE THREAD

**Issue by Cboxhero** [LlmDl/Towny#2558]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Create a new world with towny enabled
2. Disable towny using "/tw toggle usingtowny"
3. Type "/plot"

### What is the expected output?
1. For nothing to show up
2. "This world is exempt of all towny interactions"
3.

### What is your Towny version?
Do not say "latest".
Towny Advanced 0.91.4.0 

### What is your spigot/craftbukkit version?
Do not say "latest".
spigot 1.11.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : http://pastebin.com/vmT4V2uH
2. Your Towny config.yml (if using MySQL please remove password,) : http://pastebin.com/BskyMEPU
3. Your townyperms.yml : http://pastebin.com/xTqbz9yu
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
What do you see as a response when you type /plot in the world with Towny disabled?

**Comment by Cboxhero** [comment]
.o0o.------------------.[ /plot ].------------------.o0o.
  Resident: /plot claim : Claim this town block
  Resident: /plot claim [rect/circle] [radius]
  Resident/Mayor: /plot notforsale: Take down a plot for sale
etc.

**Comment by LlmDl** [comment]
Alright, I've taken care of it, it ought to be a part of 0.91.4.2, which should be out after I test it tomorrow.

**Comment by LlmDl** [comment]
Fixed in 0.91.4.2
