### ISSUE TITLE
Town blocks not being claimed properly while using high radius values

### ISSUE THREAD

**Issue by akiraic** [LlmDl/Towny#2559]
### What steps will reproduce the problem?
1. High limit for town blocks (thousands)
2. High radius while claiming town blocks (8+)

### What is the expected output?
1. 20 claimed chunks in all direction from the player position
2. Square figure in the /t map
3. Me happy

### Towny version
0.91.4.1

### Spigot version
Spigot 1.11.2-R0.1-SNAPSHOT (git-Spigot-b4417b8-a1d3777)

### Pastebin files
1. Latest.log : http://pastebin.com/raw/d5nGH85z
2. config.yml: http://pastebin.com/raw/Fb3JdZye
3. townyperms.yml : http://pastebin.com/raw/yU5FtiJy
4. Your log's error : no errors

If this is to do with permissions
5. Your permissions file : 
MySQL. But it is a OP user in a group with all permissions (*)

Map: https://goo.gl/Fx9Aae (doesn't matter the direction i'm facing, North seems to work properly.

**Comment by akiraic** [comment]
Update:
Clean install solved the problem but the same thing still happens with the the command /plot forsale <price> within rect <radius>. Same "upside-down pyramid" in the map, setting up plots for sale only North of player's location.

**Comment by LlmDl** [comment]
I tried to reproduce this today and got all the way up to '/t claim rect 33' (a 67x67 box of claims,) and had no failures at any time. If this bug is still happening on your server please file a new ticket.
