### ISSUE TITLE
Chorus Fruit teleportation within town

### ISSUE THREAD

**Issue by Seeroh** [LlmDl/Towny#2560]
### What steps will reproduce the problem?
1. Add CHORUS_FRUIT to item_use_ids to block chorus fruit usage within towns
2. Eat chorus fruit in town where you do not have Item_use permission
3. If facing a block, no teleportation, it facing air, teleports with message saying item use not allowed.

### What is the expected output?
1. Chorus fruit to be edible, but block teleportation in disallowed areas
2. Or if not possible, just block chorus fruit usage 100%

### What is your Towny version?
  - 0.91.4.1

### What is your spigot/craftbukkit version?
  - I'm using Paper 1043 on my test server, but I'm sure it'll work the same elsewhere

### Please use Pastebin.com to link the following files:
  - Sorry, skipping these, no need for this particular issue.

**Comment by LlmDl** [comment]
Fixed in 0.91.4.2
