### ISSUE TITLE
MySql conversion to flatfile error

### ISSUE THREAD

**Issue by jordanwilliams1** [LlmDl/Towny#2562]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
Converting Flatfile to SQL
http://towny.palmergames.com/towny/757-2/#Converting_Flatfile_to_SQL

1. Stop your server
2. Open the \towny\settings\config.yml and find the Plugin Interfacing section.
3. Find the database_load, make sure it’s set to flatfile.
4. Find the database_save, set it to either mysql, sqlite or h2.
5. Save the config and start your server.

After the server starts it spams this error:
 https://hastebin.com/wegojanuzi.pl

What is the expected output?
 https://hastebin.com/wegojanuzi.pl

### What is your Towny version?
Towny Advanced 0.91.4.0 [CB/Spigot 1.10.2]

Also tried a few others.

### What is your spigot/craftbukkit version?
paperclip-1056

### Please use Pastebin.com to link the following files:
Error thats spammed:  https://hastebin.com/wegojanuzi.pl
Log file: https://hastebin.com/owetemadul.rb 
Tried on 2 different servers with a fresh install of mysql

**Comment by LlmDl** [comment]
Skipped form, resubmit
