### ISSUE TITLE
Towny does not protect switching of blocks added by mods.

### ISSUE THREAD

**Issue by Kanton5089** [LlmDl/Towny#2563]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1.Try to open an item from a mod while not added to the town of the area the item is claimed.
2.The time allows you to open and take things from it as if it is not claimed at all.
3.

### What is the expected output?
1.It is expected that the item will be protected and not allow you inside of it.
2.
3.

### What is your Towny version?
Do not say "latest".
0.88.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
Thermos 1.7.10

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
You skipped the form, so this ticket will be closed.

As an aside you can see if your mod gives a name for the block you can add to the switch_id list in the config. Right click the modded block while holding a clay brick in your hand and try adding the name to the config.
