### ISSUE TITLE
Towny Outpost Problem?

### ISSUE THREAD

**Issue by onycius** [LlmDl/Towny#2564]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. I don't know, honestly. I copy and pasted the server files onto another server and the outpost claiming was fine.

### What is the expected output?
1. [Towny] null
2.
3.

### What is your Towny version?
Do not say "latest".
1.10.2 (0.91.4.0)

### What is your spigot/craftbukkit version?
Do not say "latest".
Spigot 1.10

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml 
Here's my config: http://pastebin.com/H0y5dK0u
3. Your townyperms.yml : http://pastebin.com/B9CEBnTs
4. Your log's error : 
Nothing happens in the console, actually. It just shows me executing '/t claim outpost' and that's it.
Here is my list of plugins: 
https://gyazo.com/701b8db25f6bdd3708bdcf0a7e02d364?token=348aff6c0ecb74b2d8b19cebe700af84

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Parts of the form were skipped, I cannot help you with this without them. Ticket invalid. Resubmit with form filled out completely.
