### ISSUE TITLE
Outpost Help/Bug?

### ISSUE THREAD

**Issue by onycius** [LlmDl/Towny#2565]
### What steps will reproduce the problem?
 I don't know honestly, HOWEVER:
- When I copy/pasted the files of the server onto a private server, everything works fine. World 'world' is present, but 'world' is not in the original server as the world's name is 'main'. It must be some kind of conflicting problem regarding the world names?
Possible Steps:
1.) I have all these plugins installed [https://gyazo.com/4e3cb44c9a81d66da416fd55c3f6641d](url)
2.) On the main server (the server with the issue), I have 4 worlds: main, main_nether, and main_the_end. On the test server (the server that works), I have world, world_nether, world_the_end, main, main_nether, main_the_end, void
3.) /t new (name), /t claim outpost OR /t claim outpost
The town has enough money to afford the outpost too.

### What is the expected output?
1. The message: [Towny] null
2. No errors in the console

### What is your Towny version?
Do not say "latest".
0.91.4.0 (1.10.2) 

### What is your spigot/craftbukkit version?
Do not say "latest".
1.10.2-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
logs: http://pastebin.com/kLMhwveM
2. Your Towny config.yml (if using MySQL please remove password,) : http://pastebin.com/zf5eTjCC
3. Your townyperms.yml : http://pastebin.com/VCCvB7tL
4. Your log's error : No error?

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
I need to see the full server startup log.

**Comment by onycius** [comment]
Here!
Ignore the other errors because I'm still tinkering with things hehe
http://pastebin.com/02tfFyBy

> I need to see the full server startup log.

**Comment by LlmDl** [comment]
The startup looks ok, can you show me the log of you using the commands?

**Comment by onycius** [comment]
14.02 22:07:17 [Server] INFO Xorius issued server command: /t claim outpost
14.02 22:07:17 [Server] INFO [PLAYER_COMMAND] Xorius: /t claim outpost

that's it. nothing else happens.
[Towny] null in-game as a result

**Comment by LlmDl** [comment]
I don't see anything wrong, its probably due to the worlds you set things up in not being present. You could try turning no debug_mode in teh config and then showing me a new startup.

**Comment by onycius** [comment]
http://pastebin.com/kYq6PKVa

**Comment by LlmDl** [comment]
Nothing amiss there, what does it say when you try to claim a plot for your town while the debug is on?

**Comment by onycius** [comment]
Reloaded with debug on, tried claiming, and nothing happened
http://pastebin.com/Dyfw0mHw

**Comment by LlmDl** [comment]
Nothing amiss there either. Have you tried not using your test server's towny data folder? You can keep your config/settings folder but using a fresh data folder will probably fix this. Rename the towny\data\ folder to \olddata\ and see if you can make a new town.

**Comment by onycius** [comment]
the thing is, the test server is fine.
it's the main server that's experiencing problems.
they both have the exactly same towny files too

**Comment by LlmDl** [comment]
I know you've said this, did you start on the test server and move the files to the main server?

**Comment by onycius** [comment]
yeah.
i retried copying the files but still same result on the main server. [Towny] null

**Comment by onycius** [comment]
is it possible that this is a world or conflicting plugin problem?

**Comment by LlmDl** [comment]
Have you tried not using your test server's towny data folder? You can keep your config/settings folder but using a fresh data folder will probably fix this. Rename the towny\data\ folder to \olddata\ and see if you can make a new town.

**Comment by onycius** [comment]
it says 'the resident 'xorius' is not registered' when i try to make a town with the new data folder

**Comment by LlmDl** [comment]
Can you please show me the log of you doing that, as well as the latest startup. You renamed teh data folder while the server was stopped right?

**Comment by onycius** [comment]
xD i did it when the server was on my bad.
Okay so i restarted and everything, [Towny] null still occurs.
Here's the startup log: http://pastebin.com/Bdm2Ahpa

**Comment by LlmDl** [comment]
That's not the startup log at all.

Please start with a fresh towny\data folder and show me your full server startup.

**Comment by onycius** [comment]
http://pastebin.com/cAXsaPwT

**Comment by onycius** [comment]
Oh! Outpost claiming works now!

**Comment by LlmDl** [comment]
So its working now? It was probably something in your data folder regarding the old worlds from your test server causing an issue.
