### ISSUE TITLE
Suggestion: Ranges or Ceilings on Plot Flags

### ISSUE THREAD

**Issue by acagliano** [LlmDl/Towny#2566]
Title with Suggestion:

I think a decent addition to towny is to allow ranges for toggles. For example, someone might build a PvP arena within a building and want PvP on inside it, but not above or below it. Simply allowing something like this to be issued would be cool:

/plot set pvp on 70 102     ; turns pvp on for the y range 70-102. PvP remains its default value for all y values outside that range.

Same for all other flags/perms.

Also I suggest adding chest access perms on town/player controlled plots. The same permission groups would work.

**Comment by LlmDl** [comment]
Working with height ranges, especially when they can differ between plots, means that we have to constantly check player location. This is too taxing, I'm sorry this won't be added.
