### ISSUE TITLE
Revert on unclaim speed setting not working

### ISSUE THREAD

**Issue by Freddyexpress** [LlmDl/Towny#2568]
The speed setting of revert on unclaim seems to ignore the speed factor, and is always reverting with 1s/block.

### What steps will reproduce the problem?
1. set the speed of revert on unclaim to 300s in the config.yml and in your world settings (/data/worlds/WORLDNAME.txt)
2. start the server and create a new town
3. place some blocks in the town block
4. delete the town with /town delete and /accept
5. the blocks will always be reverted with a rate of 1 block/second no matter what value is set in the configs

### What is the expected output?
1. the block changes should be reverted with the speed set in the config file (300s)

### What is your Towny version?
Towny Version 0.91.4.2

### What is your spigot/craftbukkit version?
Spigot 1.11.2-R0.1-SNAPSHOT

1. Your full server startup from the logs\latest.log : http://pastebin.com/hv9f6nnp
2. Your Towny config.yml (if using MySQL please remove password,) : http://pastebin.com/xLH3zWNA
3. Your townyperms.yml : http://pastebin.com/N7y2e4Yn
4. Your log's error : -- No error in logs --

**Comment by CakeLady** [comment]
i can confirm this problem on my server too

**Comment by LARTCraft** [comment]
Me too. Trying to set the speed to 60 seconds so that buildings on blocks can be conquered when unclaimed.. But it does not work :( please fix it

**Comment by LlmDl** [comment]
Took a while sadly but this is fixed as of 0.91.4.6 and will be available soon.
