### ISSUE TITLE
Problems with TownyChat

### ISSUE THREAD

**Issue by xDizasterCYx** [LlmDl/Towny#2569]
I have a problem with townychat, maybe it's caused by the channels, not sure, I hope you try to understand me. Okay first of all, i have other plugins like mcmmo's /adminchat or plugins like /report which lts me input the bug info in chat, like writing a msg in chat but its the actual description for the report and no one must see that, well tc chances that, it removes the privacy of that msg by announcing it in public like it was a normal chat msg. Here are some screens:

With townychat:
here's mcmmo's adminchat not working
http://i.imgur.com/PeQI5ao.png
Here's the report module not working, it should say the msg in chat
http://i.imgur.com/aD3RBYH.png

Without townychat:
http://i.imgur.com/jfDB7cr.png
and here i've reported a bug and no one saw what i said
http://i.imgur.com/Fj32IDy.png

### What is your Towny version?
Towny version 0.91.4.2

### What is your spigot/craftbukkit version?
Spigot/BuildTools Build #59

### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log :
https://hastebin.com/uqaqijaxiq.sql

2. Your Towny config.yml:
https://hastebin.com/alogepokog.http

3. Your townyperms.yml :
https://hastebin.com/edawemenot.php

4. Your log's error :
 There's no actual error.

(optional) If this is to do with chat,
6. Your chatconfig.yml :
https://hastebin.com/cahepomoke.php

7. Your channels.yml :
https://hastebin.com/enaheremof.bash

**Comment by LlmDl** [comment]
I can see in your townychat channels.yml you have the Hooked: flags from another chat plugin in there. 

Please post your full server startup log as requested in the form.

**Comment by xDizasterCYx** [comment]
Here we go: https://hastebin.com/jiregurofe.md
And about that, I am using another chat plugin and I do not need the format of townychat.

**Comment by LlmDl** [comment]
You've got a ton of chat-related plugins, I'd try using a test server with DeluxeChat removed to start.

**Comment by xDizasterCYx** [comment]
I've already tested it without Dchat and it's ok but that's the problem, I want dchat.

**Comment by LlmDl** [comment]
If I had to take a guess, DChat is the one that is making it so that the private chats are no longer private, that's not something I can fix. Try talking to the DChat author.

**Comment by xDizasterCYx** [comment]
My bad, I meant I tested it without townychat and it worked fine, dchat is not the problem.

**Comment by LlmDl** [comment]
Try it with McMMO and TownyChat and without DChat.

**Comment by xDizasterCYx** [comment]
Well the problem is weird, I tried without dchat and it worked fine. But I also tried without townychat and with dchat installed and it also worked fine, the problem appears when I have townychat and dchat installed at the same time.

**Comment by LlmDl** [comment]
That means its an issue in DChat, as far as I know, DChat is emulating townychat and bypassing what we do for the most part. If it doesn't happen when only TownyChat and McMMO is installed, it's not an issue in TownyChat.
