### ISSUE TITLE
Townychats and ranks colors.

### ISSUE THREAD

**Issue by MineServidorCraft** [LlmDl/Towny#2570]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

Hi, before i get towny my chat work like that:

http://i.imgur.com/TKfh5lc.png

Each rank have his colour, and you can know what is the rank about one users about the color (mainly).

http://i.imgur.com/PbNBo1t.png

Now, when you talk, the chat look like this(I want the same but with the color rank in your name).

http://i.imgur.com/ZZoR2A7.png

### What steps will reproduce the problem?
1. When i put the townychat.jar, the essecials chat dessapear and can't get the ranks about my users.

### What is the expected output?
1. If i can put on towny chat the ranks and their colors and when people talk get color in his name.
2. That Essencials chat and Towny chat work both.

### What is your Towny version?

Dev Build: Towny Advanced 0.91.4.1 

### What is your spigot/craftbukkit version?

Spigot 1.11.2 (I download stable lastest 2 weeks ago)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : http://pastebin.com/xi5t82Ms
2. Your Towny config.yml (if using MySQL please remove password,) : http://pastebin.com/dbQEp56P
3. Your townyperms.yml : http://pastebin.com/DeVYYZ1P
4. Your log's error : http://pastebin.com/XK7xj0w6 (I don't get any error, i dont find another thing)

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml : http://pastebin.com/1nSYHKmn
7. Your channels.yml :  http://pastebin.com/QQ4h97u6

**Comment by LlmDl** [comment]
To start you can remove this from your chatconfig.yml, it wont do anything:
```
    Esclavo: '&f'
    Mendigo: '&7'
    Jornalero: '&b'
    Campesino: '&3'
    Obrero: '&9'
    Artesano: '&1'
    Soldado: '&a'
    Mercader: '&8{DISPLAYNAME}&f:&f {MESSAGE}'
    Burgues: '&d{DISPLAYNAME}&f:&f {MESSAGE}'
    Hidalgo: '&5{DISPLAYNAME}&f:&f {MESSAGE}'
    Conde: '&e{DISPLAYNAME}&f:&f {MESSAGE}'
    Duque: '&6{DISPLAYNAME}&f:&f {MESSAGE}'
    Nephilim: '&c{DISPLAYNAME}&f:&f {MESSAGE}'
```

What you need to do it set up your colour codes for teh ranks in your permission plugin's prefix sections.

To use teh colour code in townychat's chatconfig.yml you'll use the {permprefix}.

Then you can use {permprefix}{playername}{permsuffix} on the general channel_format in the chatconfig.yml

**Comment by MineServidorCraft** [comment]
I was remove this. But i dont know how to do the prefix, i try on PEX but dont give me put a prefix.
Can you tell me or give me info or example that i need to do?
And i think that essencials block chat with towny or towny block essencials, i dont know.

**Comment by LlmDl** [comment]
I don't help with pex, sorry.

**Comment by Stormbow** [comment]
_**Official PEX guru here.**_

PEX doesn't have any chat management programming built into it.  PEX only provides a place to store the prefix and suffix for groups and players.  It's up to a chat management plugin to display that information in-game.

Personally, I have always used EssentialsChat and EssentialsXChat (when "EssentialsChat" was discontinued at Minecraft 1.8) to display prefixes and suffixes in-game.  Both of these plugins require the Vault plugin to be installed on the server before they will function correctly.

All of the standard [Color Codes](http://www.minecraftwiki.net/wiki/Classic_server_protocol#Color_Codes) and [Formatting Codes](http://minecraft.gamepedia.com/Formatting_codes) can be used in the EssentialsXChat config.yml file.  I can only assume they are also usable within the Towny plugin's config files.

**Comment by MineServidorCraft** [comment]
Yes, the problem is that when i put the TownyChat.jar my EssencialsChat dissapear. I think both isnt compatibility or something. Without it, i have color in the rank how i see you in the picture. But when i put townyChat isnt work. In others sv i see that have the both work good, but i dont know if they are using another plugin colors ranks. So, i ask here, because the dev can help me with colors into TownyChat or tell me if i have some wrong in my config and repair it. Thanx anyway :3

**Comment by Stormbow** [comment]
Oh!  Correct.  You can't use 2 chat management systems at the same time.  You have to pick one or the other.

**Comment by TekkitCommando** [comment]
That's not true.

**Comment by MineServidorCraft** [comment]
Okey, i choose towny chat because i love it. But i see in anothers server that they have colors in his ranks and townyChat. I think they put the ranks on TownyChat or something like that. If you know, Can help me to colors ranks with TownyChat or addond to can posible this?

**Comment by TekkitCommando** [comment]
TownyChat and EssentialsChat can be used together

**Comment by MineServidorCraft** [comment]
How can i do that TekkitCommando?

**Comment by Stormbow** [comment]
At any rate, this is not a PEX issue, so— Good luck.  I'll close the PEX ticket.

**Comment by MineServidorCraft** [comment]
@LlmDl @TekkitCommando If is not about PEX and can work both together. How can i do it?

**Comment by LlmDl** [comment]
I had told you earlier:

You put the colourcode for your ranks in your PEX option node section, using the prefix flag.

Then you can make that colour code show up using the {permprefix} tag in the townychat chatconfig.yml.

I'm sure there are pex tutorials out there for setting prefixes.
