### ISSUE TITLE
Revertonunclaim not turning off

### ISSUE THREAD

**Issue by CakeLady** [LlmDl/Towny#2571]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. We created a world called "world" then claimed a few towns (world1)
2. discovered a problem with the world generation so we renamed that world and created a new world called "world" (world2) (using a custom generator so the world name had to be world)
3. we then had to delete all the towns and make new towns in the new world2.
4. The towns that previously existed in the world1 are now rebuilding in the new world2 because of the revert on unclaim. 
5. I tried turning off the revertonunclaim using the command /townyworld toggle revertunclaim which is now set to off, but it is still regenerating. So we manually edited the world.txt file and it is still regenerating. 

### What is the expected output?
1. The world should stop regenerating on unclaim.

### What is your Towny version?
version: 0.91.4.2

### What is your spigot/craftbukkit version?
CraftBukkit version git-Spigot-d4f98a3-cb61ac0 (MC: 1.11.2) 

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : http://pastebin.com/vRwpA1ne
2. Your Towny config.yml (if using MySQL please remove password,) : http://pastebin.com/bwdgkcGV
3. Your townyperms.yml : http://pastebin.com/xF6b9P1W
4. Your log's error : no errors exist, it is just not functioning properly

(optional) If this is to do with permissions, 
5. Your permissions file : n/a

(optional) If this is to do with chat,
6. Your chatconfig.yml : n/a
7. Your channels.yml : n/a

**Comment by LlmDl** [comment]
To get it to stop you'll have to stop the server and delete the regen.txt in the towny\data folder, you will probably also want to remove the plot-block-data folder in that same folder, as those are the snapshots that are regenerating.

**Comment by CakeLady** [comment]
yes! Thanks so much! I searched forever for the solution and couldn't find it.
