### ISSUE TITLE
maven 2 repository

### ISSUE THREAD

**Issue by dirtyequi** [LlmDl/Towny#2572]
Hi,

I'm looking for a maven2 repository that plugin developers can define in their pom-file for automated artifact building/deploying.
Is there such a repository?

Thank you
d1rty

**Comment by LlmDl** [comment]
http://palmergames.com/file-repo/Towny%20Advanced/Latest/Towny.jar will always be the latest release build of towny

**Comment by dirtyequi** [comment]
Yeah, but this is not a maven2 repository.

**Comment by LlmDl** [comment]
Sorry we wont be setting up a maven. Adding an external jar or locally hosted jar is easy enough and our has changed once (an addition) in roughly 4 years.

**Comment by Locknlol** [comment]
Feel free to delete this post if you don't want this here @LlmDl.

I'll be using Towny as a dependency in my plugin, and have uploaded Towny to my Maven repo. It will pull and build the latest version of Towny from this Github repo, and be pushed to my maven once a week.

Anyone can feel free to add this to their pom.xml:

```

		<!-- Towny Repo -->
		<repository>
			<id>maven-releases</id>
			<url>http://repo.fiberoptic.xyz/repository/maven-releases/</url>
		</repository>

		<!-- Towny Dependency -->
		<dependency>
			<groupId>com.palmergames</groupId>
			<artifactId>Towny</artifactId>
			<version>0.91.4.8</version>
			<scope>provided</scope>
		</dependency>
```
