### ISSUE TITLE
Constant Error Spam

### ISSUE THREAD

**Issue by VolcanoMan3705** [LlmDl/Towny#2573]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Setting Gamerule doMobSpawning to "True"
2. Mobs entering town grounds(hostile)
3. (Blank)

### What is the expected output?
1. No spamming of error messages
2. If Mob Spawning in town is set to "false" the mobs will actually despawn
3. (Blank)

### What is your Towny version?
Do not say "latest".

### What is your spigot/craftbukkit version?
Do not say "latest". - Towny 0.91.4.0

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : http://pastebin.com/xFLh3QBH
2. Your Towny config.yml (if using MySQL please remove password,) : http://pastebin.com/uU873ze8
3. Your townyperms.yml : http://pastebin.com/MgVKDxfc
4. Your log's error : http://pastebin.com/SYiDN4r8    (over... and over.... and over...)

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Your citizens isn't made for 1.10.2, you need "citizens-2.0.20-SNAPSHOT.jar"
