### ISSUE TITLE
Bug plugin

### ISSUE THREAD

**Issue by xdrino** [LlmDl/Towny#2575]
Hello i have Install the plugin Towny on my server but ... We can't move when the plugin work and the all command of this plugin don't works we don't see a message in a tchat pls can you help me

**Comment by TekkitCommando** [comment]
Calling the plugin bad doesn't help you haha. Is the server in safe mode and that's why it restricts movement?

**Comment by LlmDl** [comment]
You skipped the form, so I'm closing this ticket. If you want real help you don't skip the form (as the form explains.)
