### ISSUE TITLE
Cant make a town/nation

### ISSUE THREAD

**Issue by R3kandH4V0k** [LlmDl/Towny#2576]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1.having towny installed period
2.
3.

### What is the expected output?
1.to be able to make towns and nations
2.
3.

### What is your Towny version?
Do not say "latest".
Dev Build: Towny Advanced 0.91.4.2 [1.11.2+]

### What is your spigot/craftbukkit version?
Do not say "latest".
spigot 1.11.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/RC246HNE
2. Your Towny config.yml (if using MySQL please remove password,) :https://pastebin.com/aBXiCEEL
3. Your townyperms.yml : https://pastebin.com/2d8HcBjT
4. Your log's error : unsure where it says. when I do /town new [townname] it says I don't have enough money.

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
From your startup:

[15:47:07] [Server thread/WARN]: [Towny] Error: No compatible Economy plugins found. You need iConomy 5.01, or the vault/Register.jar with any of the supported eco systems.

Go get Vault.jar
