### ISSUE TITLE
limit members

### ISSUE THREAD

**Issue by RaidersUnited** [LlmDl/Towny#2577]
Is it possible to be able to limit a number of members in a town? Also is there a way to limit a number of towns in a nation?

**Comment by LlmDl** [comment]
There is no way to put a hard cap on either, but you can severely punish a town or nation with too many members.

In the towny config: the Town_Levels and Nation_Levels are based on resident-count. You can set a very high upkeep cost on either towns or nations that go over the resident-count you want.

**Comment by LlmDl** [comment]
https://github.com/LlmDl/Towny/issues/2402
