### ISSUE TITLE
Flag war feature modification/request

### ISSUE THREAD

**Issue by ErrantSperm** [LlmDl/Towny#2578]
For the towny flag war, I would like to make it so that if you do not have additional plot claims available, it does not convert the plot to wilderness if you win a plot.  Maybe make it so that you can't even place a flag if you don't have plot claims available.  I need this because I have an area where I don't want plots to be allowed to convert to wilderness so that they can be reclaimed again.  The way this area of my server is set up, the towns in the area cannot claim plots using /t claim.  They can only get new land with flag wars.  Thanks.

**Comment by LlmDl** [comment]
I'm sorry to tell you that the Flag War in Towny isn't supported, it was added by the original Towny author a while after he'd left the project, but was never fully completed.

**Comment by ErrantSperm** [comment]
:(
