### ISSUE TITLE
[towny] null

### ISSUE THREAD

**Issue by Wizzi69** [LlmDl/Towny#2579]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. /t new {name}
2.
3.

### What is the expected output?
1. [towny] null
2.
3.

### What is your Towny version?
Do not say "latest". 
0.91.4.2

### What is your spigot/craftbukkit version?
Do not say "latest".
Spigot 1.11.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/jV5mRGZc
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/BNDHa6YH
3. Your townyperms.yml : https://pastebin.com/HtWjKytd
4. Your log's error : https://pastebin.com/j5UX6ZKW

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
![2017-04-14_20 26 04](https://cloud.githubusercontent.com/assets/27514155/25053700/9ac8633e-2150-11e7-994d-c4636efe0cd3.png)

7. Your channels.yml :

**Comment by LlmDl** [comment]
Your version of iconomy 5.01 doesn't download teh dependencies, try this one:
https://www.dropbox.com/s/qtkfsb1fav523eh/iConomy.jar?dl=0
