### ISSUE TITLE
Suggestion: PreciousStones protection compatability

### ISSUE THREAD

**Issue by Omanoctoa** [LlmDl/Towny#2580]
Hello!
I've been using the epic PreciousStones plugin for years and we started using Towny recently. Our players really like the towns and hierarchy concepts, but not all players want to be part of towns. We would love to be able to use PS and Towny together but protections can overlap and cause claiming controversy.

PreciousStones operates by having a block (say...Iron Blocks) designated as a Land Claim block. Basically, when placed it 'claims' land within a set amount of blocks (20) around it, granting land/grief/chest/entity protection within that radius. There are many other possibilities with fields, but that's the main claiming field. The problem...is when a Land Claim block is placed near a Towny town, the field overlaps with the Towny plot/city. Both protections are active, so the owner of the Town plot cannot build where the PS field overlaps, and the owner of the PS land claim cannot build where the town overlaps. Now...there are some practical uses for this but...not for players. A single misplaced PS field in a town could prevent anyone other than the field owner (and those allowed in it) from building/breaking.

What I'm requesting is simply a hook for the protect- flags for Precious Stones, ideally per player. I imagine this would require a little collaboration with Phaed428 but I know the issue has already been raised with him a few times (PreciousStones has a GitHub repository as well - https://github.com/marcelo-mason/PreciousStones/issues )

We are using CB 1.11.2, though we were using Spigot for years prior to a few months ago.

The default config is available on the PS GitHub or Jenkins repos, but if you want a copy (or snippet) of the one I'm using so you can see how it's set up, just ask.

**Also, to other readers** We use PS and Towny together with no issues apart from the one mentioned above. By making fields non-protecting and largely passive, we've created a series of very effective, fun fields that players can use to really advance their minecraft experience. We haven't experienced any of the issues other people have mentioned.

**Comment by LlmDl** [comment]
I'm sorry to say we wont be adding native support for this but if the PS API is thorough I'm sure that someone could code a plugin to prevent a PS claim if it will encroach onto a non-wilderness area in Towny. Our API supports this type of lookup easily, you just need to be able to cancel a PS claim.

**Comment by Omanoctoa** [comment]
I didn't expect so. Towny is far more complex than PreciousStones and adding support for different field types would be complicated.
