### ISSUE TITLE
Towny upkeep modifiers not working

### ISSUE THREAD

**Issue by Managering** [LlmDl/Towny#2582]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. https://hastebin.com/uvimuzovaf.coffeescript
2. http://imgur.com/a/Oz8ag
3. Tried to use it the other way around with a modifier of 10, broke towny basically. Couldn't enable.

### What is the expected output?
1. my upkeep should be 688500
2. 
3.

### What is your Towny version?
0.91.4.1

### What is your spigot/craftbukkit version?
1.11.2-r0.1-snapshot

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. https://hastebin.com/emicanevif.md
2. https://hastebin.com/uvimuzovaf.coffeescript
3. Your townyperms.yml : not a permissions thing
4. Your log's error : there is none

Please advice on a fix.

**Comment by LlmDl** [comment]
`    # Uses total amount of owned plots to determine upkeep instead of the town level (Number of residents)
    # calculated by (number of claimed plots X price_town_upkeep).
    town_plotbased_upkeep: 'true'`


you need to turn off plot based upkeep

**Comment by Managering** [comment]
Why isn't it possible to use plot based upkeep and the modifiers?

I'd prefer this option by far since it is a lot better to control the eco with.

**Comment by LlmDl** [comment]
I'll close this since you opened a suggestion ticket
