### ISSUE TITLE
Issue with daily taxes, gringotts economy.

### ISSUE THREAD

**Issue by MiguelG2016** [LlmDl/Towny#2585]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. At the time of collecting the daily taxes is not realized.
2. It gives me the error in the console.
3. I can not fix it, I need help.

### What is the expected output?
1. I need you to help me fix this please.
2.
3.

### What is your Towny version?
Do not say "latest". 91.2.0

### What is your spigot/craftbukkit version?
Do not say "latest". spigot 1.8.8

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/qqRchPZb
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/PT92Ckgx
3. Your townyperms.yml : https://pastebin.com/NqZ0qSwL
4. Your log's error : https://pastebin.com/S0f9xNPu

(optional) If this is to do with permissions, 
5. Your permissions file : https://pastebin.com/xbtcG6iQ

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/kbJe3ShN
7. Your channels.yml : https://pastebin.com/Ju1NrnBV

**Comment by LlmDl** [comment]
Sorry to tell you this, this isn't something on Towny's side. If I recall correctly, Gringott's hasn't had their side of working towny banks for a little while now. You could make sure that your Gringott's is up to date first, then making a report with the Gringott's team.
