### ISSUE TITLE
Protection problem

### ISSUE THREAD

**Issue by BluetoDark** [LlmDl/Towny#2586]
I have a town for spawn to Protect it from claiming but I want that people can look in de chesten and use shop sign and I have a plugin that can do the protection configuration for me so I don`t need the default protection of the town so a lookt in the command and there I don`t find anything and in the data of the town I deleted the protection option but it didn`t work. So please help

**Comment by LlmDl** [comment]
If you have a spawn area you need protected and you use something else for most of it already, you can stop people from claiming a town there by making an admin town.

After you start the town, put some money in the bank and add a bunch of townblocks to your town using /ta givebonus NAME AMOUNT

Then claim your area and use /t set perm on

That will make it so towny doesn't protect any of it and your other plugin can handle it.

Finally use /ta set town npc TOWNNAME. 

That will make the town not pay tax or upkeep and it will exist forever.

Afterwards you can leave the spawn town and rejoin your normal town.

**Comment by BluetoDark** [comment]
Thank you very much this helps a lot
