### ISSUE TITLE
Option to disable fireworks in item_use

### ISSUE THREAD

**Issue by KarlOfDuty** [LlmDl/Towny#2588]
Some players who are a bit too clever for their own good found out that you can destroy armor stands with firework explosions. Could we get the option to disable them in item_use?

**Comment by LlmDl** [comment]
Since it's an entity that could potentially be fired from outside of the plot the armour stand is located in i'll have to add firework_explosions to the list of entity explosion types we watch for.

**Comment by KarlOfDuty** [comment]
Ok, sounds good.

**Comment by LlmDl** [comment]
Couldn't reproduce this issue so you'll have to resubmit and not skip the form and give me very detailed instructions as to how you got it to work.

**Comment by KarlOfDuty** [comment]
What part was it that you could not reproduce? As I was not there I have no idea how exactly it was done, I only found out using coreprotect afterwards. 

If the issue is that there is no damaging effect regardless of protection, you need to craft the firework using a firework star, which is not what you get with the normal spawned in version (And you need to be in 1.11+).

If this is a permissions/protection issue I can repost with all the necessary information after figuring out how to reproduce it.

**Comment by LlmDl** [comment]
Still didn't work despite crafting them with the new Firework Star, please resubmit and don't skip the form. Make super-detailed instructions/provide screenshots if you have to so I can do exactly what you're doing.
