### ISSUE TITLE
Towny modifiers plot based taxes suggestion

### ISSUE THREAD

**Issue by Managering** [LlmDl/Towny#2591]
**# Suggestion**

What steps will reproduce the problem?

https://hastebin.com/uvimuzovaf.coffeescript
http://imgur.com/a/Oz8ag
Tried to use it the other way around with a modifier of 10, broke towny basically. Couldn't enable.
What is the expected output?

my upkeep should be 688500
What is your Towny version?

0.91.4.1

What is your spigot/craftbukkit version?

1.11.2-r0.1-snapshot

Please use Pastebin.com to link the following files:

Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.

https://hastebin.com/emicanevif.md
https://hastebin.com/uvimuzovaf.coffeescript
Your townyperms.yml : not a permissions thing
Your log's error : there is none

Please add compatability.

**Comment by Managering** [comment]
Any word on this possible being added or not?

**Comment by LlmDl** [comment]
This is now a thing in teh forthcoming 0.94.1.13
