### ISSUE TITLE
Error spamming consol

### ISSUE THREAD

**Issue by RaidersUnited** [LlmDl/Towny#2592]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What is your Towny version?
Do not say "latest". 0.91.4.2

### What is your spigot/craftbukkit version?
Do not say "latest". 1.11.2-RO.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/ygKxBg5c
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/SZn489DF
3. Your townyperms.yml : https://pastebin.com/AcK5j5kY
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/3LW6gLHE
7. Your channels.yml : https://pastebin.com/5EdRL7H0

Issue is the console being spammed, with the towny error

**Comment by LlmDl** [comment]
What was the player doing when they got that message, is the world they were in using Towny?

**Comment by RaidersUnited** [comment]
All the world are using towny, I've no idea since there is 20 players on that server.

**Comment by LlmDl** [comment]
https://github.com/LlmDl/Towny/blob/master/src/com/palmergames/bukkit/towny/listeners/TownyPlayerListener.java#L207

It's erroring on that line. Did you edit the towny\data\worlds.txt or any file in the towny\data\worlds\ folder?

**Comment by RaidersUnited** [comment]
Haven't touched any of that, Only touched channels, Chatconfig, config and townyperms. Could that have been changed in game? as someone might have touched it then.

**Comment by LlmDl** [comment]
Couldn't say what's going on, try and find out what the player is doing when the error message appears.
