### ISSUE TITLE
In town used bank money should flow back to the mayer when town is deleted

### ISSUE THREAD

**Issue by MrKiller01** [LlmDl/Towny#2594]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Build or setup a town, expand it.
2. Fill the bank with my money, setup taxes and prices...
3. Then come to the understanding that some is wrong, delete the town, forgot to retransfer, money is lost!

### What is the expected output?
1. /
2. /
3. /

### What is your Towny version?
Do not say "latest".
0.91.4.2

### What is your spigot/craftbukkit version?
Do not say "latest".
[13:43:20 INFO]: This server is running CraftBukkit version git-Spigot-3fb9445-6
e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
[13:43:20 INFO]: You are 7 version(s) behind (causing the updated version 1.12 where i am not yet at.

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Beelzebu** [comment]
The money isn't lost, this is transferred to the towny-war-chest bank account, a NPC account created by towny who keeps the money until a war, also, the server taxes to towns and nations go to this account

**Comment by Beelzebu** [comment]
The money isn't lost, is transferred to the towny-war-chest bank account, a NPC account created by towny who keeps the money until a war, also, the taxes by the server to towns and nations go to this account. I think that should be an option to disable this and make the money get back to the mayor of the town.

**Comment by LlmDl** [comment]
I think a good compromise is adding a warning about bank funds being lost to the warning message that already exists when a mayor deletes a town. If a mayor wants to remove his/her money then they will have a change before fully deleting the town.

This will be a part of the latest dev builds.
