### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by MrKiller01** [LlmDl/Towny#2595]
I might have told you yet, or not, lost track, anyhow, Towny is not compatible with spigot 1.12
Might want to start looking into that before hell breaks loose.....

**Comment by LlmDl** [comment]
You might want to file a real ticket so that I can see "whats not working"

**Comment by MrKiller01** [comment]
You can close this, but the whole plugin does not work, it says that it is not compatible, and so i am not filing a ticket, because there is nothing to test for me.

**Comment by LlmDl** [comment]
You can file a ticket and show the startup.

**Comment by LlmDl** [comment]
Just as a followup to anyone reading this, I have now seen a startup of a server running 1.12 PreRelease 5 and Towny started up just fine.
