### ISSUE TITLE
Suggestion: Add pagination to /t list and /n list.

### ISSUE THREAD

**Issue by Metisuneatn** [LlmDl/Towny#2596]
/t list tends to get really long to the point where you can't actually see all the towns. What would be really nice is limiting to maybe 15 towns per page so they can just do /t list 1, /t list 2, and so on.

A large issue I've seen with setting 0 for resident tax but some amount for plot tax is players don't notice there's a plot tax. doing /t (/town) only shows the residence tax.

**Comment by LlmDl** [comment]
For some reason I thought we already did use pagination for the /n and /t lists.

The full prices can be seen for any resident by using /towny prices

**Comment by Metisuneatn** [comment]
Yea but most people don't use /towny prices. Just a hope no big deal :D

I don't see any pagination in the /t list, was it added to 1.11.2 versions? We are switching to that this week after we make sure we dont break stuff

**Comment by LlmDl** [comment]
This actually was taken care of in this build which hasn't been made public yet:

v0.91.4.3:
    - Have removeTownblock fire an TownUnclaimEvent.
    - Courtesy of WolfLeader116:
      - The /town list and /nation list commands will now paginate and accept page numbers. 

I'll have it up later today.
