### ISSUE TITLE
Suggestion: Open town kick timer

### ISSUE THREAD

**Issue by Metisuneatn** [LlmDl/Towny#2597]
On our server we showcase towns and really urge them to remain set as open. One issue that some mayors get (very rarely) is they kick someone for whatever reason, and they just join right back. My players were looking for a /banish command to stop people from rejoining, but perhaps a rejoin timer would be slightly more forgiving.

**Comment by LlmDl** [comment]
Instead of making the towns all open to join, do you think you could make use of the public flag for towns. Public towns can be /t spawn NAME'd to if you've given players that ability.

**Comment by Metisuneatn** [comment]
We don't make them all open we just help advertise the open towns. I've never used a public flag for that how would that work for this?

**Comment by LlmDl** [comment]
If a town has public toggled on (/t toggle public) then people can see the town coordinates on the /town TOWNNAME screen, and if the admin has allowed players the permission node towny.town.spawn.public then people can /t spawn to those towns with public turned on. No need to have them join the town.

**Comment by Metisuneatn** [comment]
The situation I was talking about just happened yesterday again, I'll try to reexplain because I think I didnt properly explain it.

So you have a town that's open, you want people to join without needing invites and be a big town and blah blah blah. But one person is being rude and what not. So you kick them. But then they join again and do it all over again. Or they do it when you are offline. But the mayor doesn't want to remove open because they do want to help those who don't get town invites and all that. 

Pretty much open town mayors wanted a type of blacklist so they could keep their town open but stop those few people who cause issues from joining. I thought a black list may be too far so perhaps if thats not a good idea, a type of cooldown on joining the same open town after leaving/getting kicked.

I have seen occasions where people spam /t join /t leave /t join just to bother people. 

Does that make more sense? What we do is we noticed that players would leave because they couldnt get a town invite, so these open towns have a display in our spawn and they want to stay open for it.

**Comment by LlmDl** [comment]
This is awfully close to the requested ability for mayors to ban someone from their town.
https://github.com/LlmDl/Towny/issues/1936
