### ISSUE TITLE
Summary of war bugs.

### ISSUE THREAD

**Issue by KarlOfDuty** [LlmDl/Towny#2598]
Hi, here is a short summary of war bugs that we discussed in this thread: https://github.com/LlmDl/Towny/issues/2552

I thought I'd repost this in a new issue for your convenience, as the old one was in the middle of a giant comment thread.

-The greifing seems to be inverted, when a town isn't taken over it can be looted, but as soon as it is taken it becomes protected again.

-Going neutral doesn't seem to protect except from plots being taken, people can still greif and kill.

-Being someone's ally doesn't do anything but I'm not sure if it's supposed to anyway.

-This was with greifing turned on. We first had it off thinking that would let players greif only when they had seiged the plot down, but it just turned it off completely. Once again, not sure if this is intentional.

-You can attack your own land but the bug can be overridden by turning on the plot healing option in the config. It doesn't just counter it by both healing and attacking, it seems to fix the bug completely.

-Even if I have set a base spoils number in the config all nations always get 0 gold at the end of the war regardless of points.

**Comment by LlmDl** [comment]
Are you on the Towny IRC, I'd like to start fixing these but a lot of the time war bugs require a couple testers. If you're on the IRC we can coordinate that.

**Comment by LlmDl** [comment]
Fixed so far:
- Neutral nations' players are excluded from the PVP during wars, regardless of the world pvp status.
- Players can attack their own plots when healing is off.
- Players can attack neutral towns when healing is off.

ToDo:
- Test Townless players' PVP abilities.
- Make use of the " towns_are_neutral: 'true' " config option.
- Fix griefing. (Vs enemies, Vs allies, Vs neutrals, also griefing by neutrals.)
- Fix base spoils not populating.
- Test that Allies can help heal plots.
- Test that Allies can not PVP each other.

**Comment by LlmDl** [comment]
I'm going to be needing a bunch of testers very soon to go through the last bits that require testing as well as people to test one more new feature. Please watch this space for more details or visit the Towny IRC.

**Comment by TekkitCommando** [comment]
@LlmDl I may be able to help. Maybe make a discord or even Skype for towny? More people will be used to that than IRC.

**Comment by LlmDl** [comment]
http://towny.palmergames.com/?p=986 All part of the big 0.91.4.6 dev build.

**Comment by LlmDl** [comment]
@TekkitCommando I invite you to join the Discord I made: https://discord.gg/gnpVs5m
