### ISSUE TITLE
Suggestion: Towny perms "syntax error" when typing perm command wrong

### ISSUE THREAD

**Issue by Devonshiresab** [LlmDl/Towny#2602]
Hello Towny coders,

Setting up permissions is one of the more difficult tasks for a mayor. It has a lot of variables and options. Lots of easy mistakes in the formatting of the command.

Right now, even when a mayor types in a wrong permission change, like **/t set perm GARBAGE** or **/t set perm outsider resident**

Towny still returns 

> Succesfully changed permissions to:

Why change this?
Because it  is confusing to the mayor, because they will see no change in the permissions even though the plugin says they successfully modified it.

It will help novice and new mayor greatly because they will see when they typed something incorrectly. 
(So they do not complain to me, or blame it on a plugin bug)

Hopefully this will be added in the next release.

**Comment by LlmDl** [comment]
Fixed in 0.91.4.7 http://towny.palmergames.com/?p=990
