### ISSUE TITLE
[Suggestion] TownyChat: userprefix-override-groupprefix

### ISSUE THREAD

**Issue by arkobat** [LlmDl/Towny#2606]
I have a problem where the permission plugin i have does not offer to replace groupprefix with playerprefix, and the author of the plugins has stopped working on it (PowerfulPerms)

So when I write in the chat, it says 
[GroupPrefix][CustomPrefix]Arkobat: Message
But what i want is either
[GroupPrefix]Arkobat: Message
[CustomPrefix]Arkobat: Message
One of those (The last if they have a custom prefix, if not, it shall fallback on the group prefix)

Is this an option TownyChat could implement?

**Comment by arkobat** [comment]
Bump.
Is this something we will see in a near future, or shall i explore other opportunities for my problem?

**Comment by LlmDl** [comment]
I have a build of towny and townychat that should fix this, join the IRC so I can get them to you and you can tell me if it works.

**Comment by LlmDl** [comment]
Part of 0.91.4.8 and requires TownyChat 0.48
