### ISSUE TITLE
UUIDs for Towns and Nations

### ISSUE THREAD

**Issue by Wolf2323** [LlmDl/Towny#2607]
Suggestion:

My suggestion is simple. I want UUIDs for Towns and Nation. I want to Programm addons for Towny, but if a Town or Nation renamed, i have to do a lot of workaround to do something similar.

**Comment by LlmDl** [comment]
Why aren't you just using the renametownevent and renamenationevent? It's the same amount of work to use the names as it is a uuid, no?

**Comment by Wolf2323** [comment]
You are right, but it would be much more easier when someone programm an add on for Towny, if he hasn't to listen to the rename event and has to update all the data in his Files/databases.

**Comment by LlmDl** [comment]
You'll still have to listen for the event regardless of whether there are events or not though. These addons you're planning, will they be public? I don't see any public repos on your github.

**Comment by Wolf2323** [comment]
At the moment my addons are not public. Later that is possible that my addons are public, but in the moment i'm still programming it.
Thanks for your time for the support.

**Comment by LlmDl** [comment]
This is a thing as of 0.91.4.12
