### ISSUE TITLE
*bug* towny 1.12 over-riding commands

### ISSUE THREAD

**Issue by Demonkid1112** [LlmDl/Towny#2608]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

I don't feel the need to complete anything after requesting bukkit version, as this issue is still occuring, on a fresh server, fresh towny install. 

The issue I'm having is that towny seems to want to over-ride commands like /stats from mcmmo and default them to the normal minecraft commands. For example with /stats from mcmmo it should display a scoreboard with all the skill levels, or another is with chatcontrolpro and essentials. CHCPro and essentials both provide a much better private message feature. However towny rids these features and makes any default minecraft commands auto take the highest priority and is rather annoying for me and my players. 

### What steps will reproduce the problem?
1. install towny 0.91.4.7, McMMO 1.5.07-SNAPSHOT or ChatControlPro 7.3.19 and have spigot 1.12-R0.1-SNAPSHOT
2. If using ChatControlPro configure to allow private message feature (or use my config attached below)
3. Else start up server and try /stats if using mcmmo, or /tell if using ChatControlPro

### What is the expected output?
1. With ChatControlPro you should get the message format you configure to be
2. with /stats you should get an mcmmo scoreboard saying your skills and their levels

### What is your Towny version?
Do not say "latest".
Towny 0.91.4.7 

### What is your spigot/craftbukkit version?
Do not say "latest".

Spigot 1.12R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
I've tested a server already that has mcmmo and Towny on 1.12, we don't hook the /stats command at all. The /tell command from the chat plugin may have an alias set up for /t.

This could be caused by spigot's changing their handling of default commands maybe?

**Comment by LlmDl** [comment]
Have you tested without Towny added?

**Comment by Demonkid1112** [comment]
I have, without towny all the commands work like they normally should, but with towny, like I said it seems to want to give itself or default minecraft the highest priority, I have looked through my chat plugin which lets us assign aliases for private messaging and the only ones that are present include /msg, /whisper, /message, and /tell.

**Comment by LlmDl** [comment]
What does happen when you use /stats? What happens when you use /tell?

**Comment by Demonkid1112** [comment]
When I had used stats (before I found a small fix) I had recieved 
"Usage: /stats <entity|block> ..." rather than the scroeboard
which means the server is recognizing /stats as /minecraft:stats and not /mcmmo:stats, I got around this via bukkit commands file and forcing bukkit to give /stats to mcmmo

then with /tell it should give the format
"[{sender}->me] {message}" - reciever side
or 
"[me->{receiver}] {message}"  - sender side
but rather I get the default minecraft /tell message which is
"{sender} whispers to you: {message}" - receiver side
or
"You whisper to {receiver}: {message}" - sender side

**Comment by LlmDl** [comment]
I was asking you to provide what you do see, not what you want to see.

**Comment by Demonkid1112** [comment]
![2017-06-13_21 05 00](https://user-images.githubusercontent.com/22757020/27113751-0e54b03c-507c-11e7-8419-bd42b3b79d55.png)
![2017-06-13_21 04 42](https://user-images.githubusercontent.com/22757020/27113752-0e6ea55a-507c-11e7-8604-da5816d3fb7b.png)

**Comment by LlmDl** [comment]
Try using Towny and mcmmo without your chat plugin. Show me the results.

**Comment by Demonkid1112** [comment]
![2017-06-13_21 13 32](https://user-images.githubusercontent.com/22757020/27113918-381746ae-507d-11e7-8b44-18b44777045e.png)

**Comment by LlmDl** [comment]
I don't believe this is related to Towny. Your mcmmo command ia still conflicting with a defeat command, which can be solved by setting an alias in the spigot alias.yml, the tell command did seem to send a message according to your screenshot. This looks like a side effect of spigot changing how default Mc commands are handled.

**Comment by Demonkid1112** [comment]
I figured something of that sorts as well but this is with towny 
![2017-06-13_21 29 29](https://user-images.githubusercontent.com/22757020/27114249-850438d0-507f-11e7-80bf-8fa5aa060035.png)

and this is without towny 
![2017-06-13_21 25 47](https://user-images.githubusercontent.com/22757020/27114253-8bfafb74-507f-11e7-9fc5-422948136d1a.png) I didn't change any other plugins which is why I suspect towny

**Comment by LlmDl** [comment]
open the chat plugin's .jar file with winrar and pastebin.com the plugin.yml inside of it, link it here.

**Comment by Demonkid1112** [comment]
https://pastebin.com/psG6excM

**Comment by LlmDl** [comment]
Ok, fairly sure its essentials that is overriding /t with their /tell command, not your chat plugin.

Has mcmmo and essentials put out updates to accomodate the change spigot made?

**Comment by Demonkid1112** [comment]
Both have had fairly recent updates, essentials on june 11th, and mcmmo on june 10th both have addressed issues with 1.12 but are not overly specific with it. However I can try without essentials to see what happens

**Comment by Demonkid1112** [comment]
Another thing, is I had posted a bug report to the author of CHCPro and I had received this back 

ChatControl should take over the commands unless you have Towny, Towny interferes with the technique we use so I added an exception there that may result in the command not always being registered.

**Comment by LlmDl** [comment]
I am not familiar with that plugin but it doesn't have a /tell command. But neither does Towny. Neither of the commands you have an issue with are Towny commands. I dont believe any of this has to do with Towny.

**Comment by Demonkid1112** [comment]
Alright, well thank you for your time I will continue to search or just switch plugins
