### ISSUE TITLE
Towny error when starting a fire

### ISSUE THREAD

**Issue by Bezod** [LlmDl/Towny#2609]
### What steps will reproduce the problem?
1. Starting a fire. Tried with both flint and fireball.
2.
3.

### What is the expected output?
1. No error
2.
3.

### What is your Towny version?
0.91.4.8 dev-build 

### What is your spigot/craftbukkit version?
1.12, paperspigot

### Please use Pastebin.com to link the following files:
Error message amongst other info provided here:
https://pastebin.com/cThzNXGb

//Fix

**Comment by LlmDl** [comment]
Where was the fire started? Wilderness or a town?

**Comment by Bezod** [comment]
This appears only to happen in the wilderness and not in towns not matter the town's firespread setting.

**Comment by LlmDl** [comment]
Fixed in 0.91.4.8
