### ISSUE TITLE
TownyChat throws NullPointer exception during spigot 1.12 startup

### ISSUE THREAD

**Issue by schentuu** [LlmDl/Towny#2610]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Setup: Spigot 1.11 + Towny v0.91.4.2 + TownyChat v0.47
2. Server was in use for a while, some towns were created

3. Shutdown Server, replace Spigot1.11 with Spigot 1.12
4. Start Server
5. Exception occours in latest.log, caused by TownyChat 

See 'latest.log' line 247 to 260 --> https://pastebin.com/zgMtN6VL 

### What is the expected output?
1. Startup without Exception
2.
3.

### What is your Towny version?
Towny v0.91.4.2
TownyChat v0.47

### What is your spigot/craftbukkit version?
git-Spigot-8cbfc85-202da97 (MC: 1.12)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**

1. Your full server startup from the logs\latest.log : 
https://pastebin.com/zgMtN6VL

2. Your Towny config.yml (if using MySQL please remove password,) : 
https://pastebin.com/7yjKa473

3. Your townyperms.yml : 
https://pastebin.com/MzX6N9ck

4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :  
https://pastebin.com/aA4iYTuP

7. Your channels.yml : 
https://pastebin.com/JWdsTvpe

**Comment by LlmDl** [comment]
Your config is out of date and is missing the Alone message:
```

  modify_chat:
    # This is used for when you don't have another plugin to format chat.
    # or you want some other plugin to handle open chat, but want Towny formatting.
    # It will cause Towny to overwrite any other plugins alterations to the format.
    enable: 'true'
    # If true the chat formats will be read from below to allow per world formatting.
    # These can then be altered individually.
    per_world: 'false'
    # If true any player who speaks in a channel in which he cannot be heard, 
    # either by being along in the channel or out-of-range of another player in his chat channel,
    # that player will see a message saying they cannot be heard.
    alone_message: 'false'
    # This allows you to set your alone messaeg.
    alone_message_string: 'No one in range can hear you or you are alone in this channel.'
```

Add it manually and it will not error at startup.
