### ISSUE TITLE
Suggestion: Players should get a chat message with how much money was drawn after teleporting to a town

### ISSUE THREAD

**Issue by Bezod** [LlmDl/Towny#2611]

**Comment by LlmDl** [comment]
Looked at the code. Players ought to be getting a message already, can you confirm they don't?

**Comment by LlmDl** [comment]
Wait, looks like if you're using essentials we bypass the cost message

**Comment by LlmDl** [comment]
Nope, a third look at it, it should still be showing a cost, keep in mind anyone with towny.admin doesn't pay for teleports.

**Comment by Bezod** [comment]
My bad, you are correct.
