### ISSUE TITLE
Required residents to join a nation bug

### ISSUE THREAD

**Issue by KarlOfDuty** [LlmDl/Towny#2614]
Basically, if a town gets kicked from a nation for having too few players it can just rejoin again without adding more players.

### Related config lines:
  The required number of residents in a town to join a nation
  If the number is 0, towns will not require a certain amount of residents to join a nation
  required_number_residents_join_nation: '2'
  The required number of residents in a town to create a nation
  If the number is 0, towns will not require a certain amount of residents to create a nation
  required_number_residents_create_nation: '2'

### What steps will reproduce the problem?
1. Have a town in a nation (not as capital) with two people and have one of them leave.
2. The town is now kicked from the nation.
3. Rejoin the nation.

### What is the expected output?
Town can rejoin the nation without meeting the player requirement.

### What is your Towny version?
The pre-release one you sent us.

### What is your spigot/craftbukkit version?
1.12, can't check exact build right now.

**Comment by LlmDl** [comment]
Fixed in 0.91.4.8
