### ISSUE TITLE
[Suggestion] Capture the flag type Towny War

### ISSUE THREAD

**Issue by Szikszai60** [LlmDl/Towny#2616]
With my team we want to create a towny server. But we found the war system not suitable for us. 
I think you should add a second option: Capture the flag wars. You have to go to the homeblock than use a command (maybe) and you can steal the flag. Than you have to run to your or your allied's homeblock to put down it. If the flag is down the town lose the war.  If you kill the stealer the flag returns to the town or put down to the ground and others can pick it up.
The settings would be the same, if you want they can destroy blocks etc. but you can't win townblocks and forgot the townblock's hp system.
Rewards would be adjustable or the losing towns or nations money's x percent divided between the winner cities.

**Comment by LlmDl** [comment]
This isn't something I want to code, and seeing as the Towny API supports all the checks you would need to have this done by a separate plugin, I think this is best left to the people already making CTF plugins.
