### ISSUE TITLE
/t list with hundreds of towns...

### ISSUE THREAD

**Issue by 151baccardi** [LlmDl/Towny#2618]
### What steps will reproduce the problem?
1. do /t list
2. it will only show 50 or 60 towns....
3. the top towns are scrolled out of range and you can't scroll up in chat to see all the bigger towns... 

### What is the expected output?
1. it would be nice to have those towns displayed more compactly like comma separated instead of line separated. like 

Rome(112),Sparta(100),Greece(98),NewYork(88), [...} Dirtville(1),Cobblestoop (1)

instead of 
Rome(112)
Sparta(100)
Greece(98)
NewYork(88)

But those you can't scroll to because of hundreds of other towns ....

I the current method, all the big towns can't be viewed as they are scrolled out of chat range *with hundreds of towns

### What is your Towny version?
This is an issue on all towny versions. The formatting isn't compact enough to list all towns and still be able to scroll through them 

### What is your spigot/craftbukkit version?
1.12 R1

Simply change the output so things are parsed to be displayed separated by a comma with as many as 10 towns on one line instead of losing all the top towns to the limited chat scroll history.

Same happens with /t top --- it will not show the top towns, just the smallest ones bottom 50 towns or so. 

Dirtville (1)
Cobblestoop (1)

etc etc 

simple solution is to output the towns with as little bloat and as many on one line as possible...

**Comment by LlmDl** [comment]
You skipped the Towny version so I don't know if you're on the version that has pages for this command. Resubmit if you want.
