### ISSUE TITLE
explosion error 

### ISSUE THREAD

**Issue by hmmcrunchy** [LlmDl/Towny#2619]
Explosion occurs on server, all works ok this error appears in console

### What steps will reproduce the problem?
1. start server 
2. cause an explosion in a towny world
3.

### What is the expected output?
1. nothing / explosion occur
2.
3.

### What is your Towny version?

0.91.4.7

### What is your spigot/craftbukkit version?

1.12r1

### Please use Pastebin.com to link the following files:

1. on start no errors https://pastebin.com/QSD7wnCj
2. default new install
3. default perms new install
4. log error https://pastebin.com/Gv0KVNQ5

thanks for brilliant plugin :)

**Comment by TekkitCommando** [comment]
Seems it couldn't get the towny world.

**Comment by LlmDl** [comment]
Anything special about the world? Was it brand new? Is it somehow outside of bukkit's control?

**Comment by LlmDl** [comment]
Closed for lack of response, startup incomplete

**Comment by hmmcrunchy** [comment]
Hi sorry wasn't informed of replies 

Normal world quite old in fact :) 

Nothing special about it and been using towny for years on it

**Comment by LlmDl** [comment]
How is the explosion created? Can you give me the exact steps I would do to make this happen on my server?

**Comment by hmmcrunchy** [comment]
it seems after further ttesting to be the plugin cannons 

https://dev.bukkit.org/projects/cannons

when a cannonball impacts, may be an API change from you guys or will I have to send over to the cannons chap

**Comment by LlmDl** [comment]
Did you have Towny's War event in use at the time?

**Comment by hmmcrunchy** [comment]
Hiya no we don't tend to use that at the moment

**Comment by LlmDl** [comment]
Explosions are occuring in towns or in the wilderness or in both?

What is the town's explosion setting.
What is the world's explosion setting.

**Comment by hmmcrunchy** [comment]
Brill thanks so much just on holiday at the moment I'll test as soon as I get back

**Comment by hmmcrunchy** [comment]
hiya 

weirdly ive tested and still same error, but then kingdoms has the same issue in the log below 

https://pastebin.com/3XgWmST7 

maybe its the way cannons works

**Comment by LlmDl** [comment]
Could you please screenshot your /tw output for me and host it somewhere like imgur.com

**Comment by LlmDl** [comment]
Still need the screenshot to help me narrow-down where the error is coming from. I'll be on holiday soon but hope to see your response when I return.

**Comment by hmmcrunchy** [comment]
Hiya apologies yes I'm on h as well at moment I'll get that over as soon as I can 

Thanks for your help
