### ISSUE TITLE
Suggestion: Display line number on data file read error.

### ISSUE THREAD

**Issue by KarlOfDuty** [LlmDl/Towny#2623]
Makes fixing data files a whole lot easier.

**Comment by LlmDl** [comment]
Done the flatfile version of this.

**Comment by elian1203** [comment]
Not exactly showing the line number.
https://pastebin.com/C6FT3REP

**Comment by LlmDl** [comment]
Yeah it wont be line numbers @elian1203, the bulk of the data is many tokens on a single line, such as that resident in your linked startup. Knowing which resident is the problem is much better than the old message that just said "Error: Loading Error: Exception while reading town file SnowSlate"

**Comment by LlmDl** [comment]
I'm sticking a fork in it this is as done as I want to make it for the foresee-able future.
