### ISSUE TITLE
Arrows bounce off animals skin in wilderness

### ISSUE THREAD

**Issue by JarusB** [LlmDl/Towny#2624]
During shooting to animals with bow arrows bounce off them and make no damage.

### What steps will reproduce the problem?
1. Set in cofig.yml: unclaimedZoneDestroy=false
2. Nobody has "towny.wild.*"
3. Shoot with bow to the animal.

### What is the expected output?
1. Arrow should make damage.

### What is your Towny version?
0.91.4.7

### What is your spigot/craftbukkit version?
1.11.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/KXpNCyWV
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/KXpNCyWV
3. Your townyperms.yml : https://pastebin.com/hR1g3bDJ
4. Your log's error : None

(optional) If this is to do with permissions, 
5. Your permissions file : https://pastebin.com/f13G6BiQ

**Comment by LlmDl** [comment]
You're shooting just animals? Monsters? 

In the wilderness? In towns?

When you "Set in cofig.yml: unclaimedZoneDestroy=false" that isn't doing anything in any of your existing worlds, the setting in the config is only used for newly-created worlds' default settings.

What have you set in your towny\data\worldname.txt ?

Your permissions show you have given plenty of towny.wild.destroy and .build nodes. Which rank are you using to test with?

**Comment by LlmDl** [comment]
Also missing your config.yml

**Comment by JarusB** [comment]
Config.yml: https://pastebin.com/vpwqyQ3J

I've tried on animals and monsters.

Only in the wilderness.

Yes I had. I've set in my towny\data\worldname.txt.

I'm using "kmiotek_slowianie".

**Comment by LlmDl** [comment]
What happens if you test without towny enabled? I've looked over the code and it doesn't look like we care about monster/animal damage in the wilderness.

**Comment by JarusB** [comment]
Without towny it works correctly.

**Comment by LlmDl** [comment]
Can you pastebin.com the towny\data\worlds\worldname.txt for me as well

**Comment by JarusB** [comment]
Here you are: https://pastebin.com/9xrRwRfq

**Comment by LlmDl** [comment]
give your testers towny.wild.destroy.416 and retest on animals and then on a monster please.

**Comment by JarusB** [comment]
Still doesn't work.

**Comment by LlmDl** [comment]
I've just tested this myself after going over the code again and it does require you to give your players the permission node towny.wild.destroy.416

After doing this and moving around in order for towny to recache my plot permissions it did work as planned. You can use /ta toggle debug and watch your log to test this yourself.

The code that was responsible for this was not taking into account that the test might not be occuring in a town. I have made it so that in the wilderness the animal will not be protected. This is a part of the forthcoming 0.91.4.9
