### ISSUE TITLE
Change permission of maxplots to a file

### ISSUE THREAD

**Issue by SeDark** [LlmDl/Towny#2631]
https://github.com/LlmDl/Towny/issues/2474

I already suggested this time ago, since I need a user to have multiple groups and this causes problems.

I suggest that you can define how many parcels a group can have (in a file) and this is the primary (according to the permissions plugin), as does lwc, for example

**Comment by LlmDl** [comment]
File a bug ticket, not a suggestion. I want to see your files and be sure you're set up properly.
