### ISSUE TITLE
Problem with permissions (maxplots)

### ISSUE THREAD

**Issue by SeDark** [LlmDl/Towny#2632]
https://github.com/LlmDl/Towny/issues/2631
In response to the previous topic

### What steps will reproduce the problem?
1. Create multiple groups with different values to have plots, example (group a [towny_maxplots.10], group B [towny_maxplots.20], group C [towny_maxplots.30))
2. Set the weights correctly so that some have more priority than others
3. Adds a user to two groups at a time or creates inherit between groups
4. Try to claim a plot several times, sometimes it is correct correctly, sometimes not

### What is the expected output?
1.  Always take the permit with the group by highest weight

### What is your Towny version?
Towny Advanced 0.91.4.8 

### What is your spigot/craftbukkit version?
Paper Spigot 1.12 R01 1140

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/U15digq4

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/2RXeMUGv

3. Your townyperms.yml :
https://pastebin.com/RpD2PLbM

4. Your log's error : 
No error is displayed

https://github.com/lucko/LuckPerms/issues/363#issuecomment-313948837
Here I talked to the author of the permissions plugin that I use, inside there is proof of permissions

**Comment by LlmDl** [comment]
please also pastebin your permissions file(s)

**Comment by SeDark** [comment]
I'll give you an export and a .sql since it's all in mysql

https://pastebin.com/8VpfyYsb

https://pastebin.com/jX3FqbvQ

I'm sorry but I can not send you a permissions file as such because I do not have it, it's all in mysql

**Comment by LlmDl** [comment]
Have you considered using LuckPerms' meta nodes? The max_plots settings are meant to be used as info/option/meta nodes and the permission node you're using is only meant for plugin that do not have info/option/meta nodes.

GM calls them info nodes, pex calls them option nodes and bperms/luckperms calls them meta nodes.


Let me know if it works correctly after you begin using meta nodes.

**Comment by SeDark** [comment]
Sorry, I have already used this method and it continues to happen, the problem is that my users can have multiple groups and for some reason does not choose the one that has more priority

**Comment by LlmDl** [comment]
Pastebin.com your luckperms config

**Comment by SeDark** [comment]
https://pastebin.com/yDGdK4cp

**Comment by LlmDl** [comment]
Join the Towny IRC, I have a build for you to test.

**Comment by SeDark** [comment]
I'm sorry, I can come in but I will not understand anything, I'm not good in English, I'm using a translator

**Comment by LlmDl** [comment]
Try out your problem with the max_plots again, using the META sections of LuckPerms, using this build of towny: https://www.dropbox.com/s/q6t4kp5hr1u1wkp/Towny.jar?dl=0

**Comment by SeDark** [comment]
I'm sorry I was late, I had people inside and I had to clone the server to prove it

This time it works perfectly, I have tried 20 times with 3 different group configurations per user

I imagine it will not fail after this, tomorrow I will put the new version on the official server

Thank you so much for your time and for fixing this that I was already going crazy
