### ISSUE TITLE
Suggestion: UUID implementation / alternative.

### ISSUE THREAD

**Issue by TyJcksn** [LlmDl/Towny#2633]
Besides manually doing every player that changes their name with a command can there be a uuid update?

"Had an issue with towny a year ago about uuid implementation. Went scrolling through some old closed issues and actually saw my comment from a year ago asking for uuid conversion. Since then I've stopped and restarted minecraft and have been working on a new server only to find out uuid still isn't implemented even with the release of sponge and 1.12. Any chance you'll add it this time @ElgarL"

**Comment by LlmDl** [comment]
We have TownyNameUpdater, that does all the renaming for you. Towny will not use UUIDs in the database because it would make it unreadable/unfixable to human eyes.

I dont know what that quoted bit of text is, or who you're quoting.
