### ISSUE TITLE
Column 'outlaws' not created; stops towny-data from loading

### ISSUE THREAD

**Issue by bjornleijdstrom** [LlmDl/Towny#2634]
### What steps will reproduce the problem?
Updating from any dev-build before the outlaw release using mysql/mysql.

### What is the expected output?
Should create table for outlaws, won't.

### What is your Towny version?
0.91.4.8

### What is your spigot/craftbukkit version?
1.12, built today.

### Please use Pastebin.com to link the following files:
1. Startup: https://pastebin.com/tk33ZXQE
2. Towny-config: https://pastebin.com/UkMLxQJJ
3. Townyperms: https://pastebin.com/31EhsrKv

**Comment by LlmDl** [comment]
Try this build please: https://www.dropbox.com/s/q6t4kp5hr1u1wkp/Towny.jar?dl=0

**Comment by bjornleijdstrom** [comment]
@LlmDl same problem; I can see .9 loaded, but same error.

**Comment by LlmDl** [comment]
Can you set debug mode to true in teh config and show me your startup again.

**Comment by bjornleijdstrom** [comment]
https://pastebin.com/kQh3Ewzz

**Comment by LlmDl** [comment]
Fixed as of 0.91.4.9 available for download now
