### ISSUE TITLE
Suggestion: Make more of the status screens translatable

### ISSUE THREAD

**Issue by ghost** [LlmDl/Towny#2636]
Some letters in the status screen showed when use command /town can not be translated.
Such as "Board:" "Bank" "Mayor"
Hope that you can add it in language files.Thanks

**Comment by H3nkl3r** [comment]
Is it possible for you to realize it in the near future?

**Comment by LlmDl** [comment]
It's a low priority.

**Comment by LlmDl** [comment]
As of 0.92.0.10 this is a thing. All of the messages that were not translated inside of the the TownyFormatter  are now part of the language files 0.44 and onwards. Whether its a good idea to translate them is another question. I did add a new method that would try to intelligently split lines evenly at points there there are " " (spaces.) It may not look perfect and there will probably still be improvements made.
