### ISSUE TITLE
Not a bug? Channel issues.

### ISSUE THREAD

**Issue by TyJcksn** [LlmDl/Towny#2639]
I'm not sure what I'm doing incorrectly to set up the channels on my server.
http://prntscr.com/fxq81t
When I try to change channels it says "Unknown command" and the channel I made (helpchat) doesn't work. I gave defaults on my server the permissions, towny.chat.help but still nothing.

### What is the expected output?
1. Using vairous commands to change between chat channels.
2. /hc for help chanel, /mod, etc

### What is your Towny version?
1.11.2 / 1.12 Support: The latest Towny Dev Builds ( 0.91.4.1+ ) 

### What is your spigot/craftbukkit version?
1.12

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/tT8rcX9S
2. Your Towny config.yml (if using MySQL please remove password,) :https://pastebin.com/WzbUcQNa
3. Your townyperms.yml : https://pastebin.com/Rhx4TFh3
4. Your log's error : N/A

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :https://pastebin.com/Aks4NC2n
7. Your channels.yml : https://pastebin.com/0azpC8eT

**Comment by LlmDl** [comment]
To start, in your screenshot you're showing /help not working, it would be /hc as per your channels.yml configuration.

More importantly you cannot create new channel Types in the channels.yml, you'll have to change the helpchat type to default, and remove the help type from the chatconfig.yml. 

Do all this and show us a new screenshot.

**Comment by TyJcksn** [comment]
Like so? 
Chat config, http://prntscr.com/fxt5m8
Channels, http://prntscr.com/fxt5uz

**Comment by LlmDl** [comment]
default is just the type, its used for any channel that isnt town, nation or global. The changed files look good.

**Comment by TyJcksn** [comment]
Seems to have fixed the town and nation chat, help chat even works. However the mod chat still causes the "unknown command" to pop up. Any suggestions @LlmDl ?

**Comment by LlmDl** [comment]
I hadnt noticed it, the mod channel, is it still type: MOD ?

**Comment by TyJcksn** [comment]
**    mod:
        commands: [m,mod]
        type: MOD
        channeltag: '&f[&9MOD&f]'
        messagecolour: '&5'
        permission: 'towny.chat.mod'
        craftIRCTag: 'admin'
        range: '-1'**


    mod: '{channelTag}{playername}&5:{msgcolour} {msg}'

**Comment by LlmDl** [comment]
There's no MOD type, change that to default.

**Comment by TyJcksn** [comment]
Thanks for you patience and all your help LlmDl
