### ISSUE TITLE
Outposts randomly disappearing or teleport location moving with MySQL

### ISSUE THREAD

**Issue by BlackBeltPanda** [LlmDl/Towny#2641]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Setup Towny to use a MySQL database
2. Create some outposts
3. Try to teleport to an outpost
4. Sometimes the outpost no longer exists or you're teleported to a different outpost.

### What is the expected output?
1. User should be teleported to the correct outpost

### What is your Towny version?
0.91.4.7

### What is your spigot/craftbukkit version?
Paper version git-Paper-1143 (MC: 1.12)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/raw/S3tBgKCk
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/raw/YVkNhbw8
3. Your townyperms.yml : https://pastebin.com/raw/mXLjHDWY
4. Your log's error : N/A

(optional) If this is to do with permissions, 
5. Your permissions file : N/A

(optional) If this is to do with chat,
6. Your chatconfig.yml : N/A
7. Your channels.yml : N/A

**Comment by LlmDl** [comment]
There's been a fix for outposts in a build newer than the one you use.

https://github.com/LlmDl/Towny/blob/master/src/ChangeLog.txt#L2543

If you'd please retest with newly made outposts I'd appreciate it.

**Comment by BlackBeltPanda** [comment]
Testing out the latest version now.
I was immediately hit with these errors on startup, though: https://pastebin.com/raw/HNwttgAv

**Comment by LlmDl** [comment]
Number one rule of using Citizens is that it has to be a version made for the version of MC you use.

**Comment by BlackBeltPanda** [comment]
I'm using Citzens 2.0.22 build 1484 but I'll try build 1487.

**Comment by LlmDl** [comment]
Can you show me the full startup after you've gotten the newest Citizens please.

**Comment by BlackBeltPanda** [comment]
Here's the new startup log: https://pastebin.com/raw/WZS1jUg9

**Comment by BlackBeltPanda** [comment]
Here's the new startup with Citizens build 1487: https://pastebin.com/raw/Cs0t08AB

**Comment by LlmDl** [comment]
Could you try things out wihtout skRayFall? Citizens is fine, teh version is fine, but some of your NPCs dont appear to be registered as Citizens NPCs. Can you give me some more details about some of the NPCs like bfish_merchant and bjob_manager?

**Comment by BlackBeltPanda** [comment]
Fish_Merchant is an NPC handled by the MoreFish plugin (https://github.com/elsiff/MoreFish).
Job_Manager is a regular NPC but I've used CommandNPC to have the player run a command when they right click it. (https://www.spigotmc.org/resources/commandnpcs-1-7-1-8-1-9.8091/)
The rest are all handled by LeaderHeads. (https://www.spigotmc.org/resources/leaderheads.2079/)

I just noticed that the NPCs are also no longer spawning, now.

I'll try disabling skRayFall and see what happens.

**Comment by BlackBeltPanda** [comment]
Outposts are still disappearing after updating. They seem to convert to regular town plots instead of remaining as outposts.

**Comment by LlmDl** [comment]
Please re-test using 0.91.4.12, released today. We're going to put a close eye on this issue but we need up to date feedback.

**Comment by LlmDl** [comment]
Found a bug in 0.91.4.12, please use 0.91.4.13.

**Comment by LlmDl** [comment]
Closing this ticket as it is likely related to https://github.com/LlmDl/Towny/issues/2622 where the testing/discussion is active.
