### ISSUE TITLE
Easy Towny Safemode induction with Outlaws

### ISSUE THREAD

**Issue by elian1203** [LlmDl/Towny#2642]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Add any player as an outlaw in your town
2. Invite that player to your town
3. Restart the server

### What is the expected output?
1. The player should be removed as an outlaw, or at least a message shown that they must be removed as an outlaw to add them to town.

### What is your Towny version?
Do not say "latest".
0.91.4.9

### What is your spigot/craftbukkit version?
Do not say "latest".
1.12

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/0nRZD4Vg
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/HLfHmk7U
3. Your townyperms.yml : https://pastebin.com/PzDswRSq
4. Your log's error : https://pastebin.com/pZUAwsaS

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Fixed in 0.91.4.10

Thanks for finding this.
