### ISSUE TITLE
Town Slowly unclaiming itself

### ISSUE THREAD

**Issue by nukedassasin** [LlmDl/Towny#2643]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Unclaiming land
2. Town / nation being deleted
3. n/a

### What is the expected output?
1. Town to be deleted
2. Everything stays the same
3. No block reverts

### What is your Towny version?
0.91.4.9 

### What is your spigot/craftbukkit version?
1.12

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : 
[latest_logs.txt](https://github.com/LlmDl/Towny/files/1167013/latest_logs.txt)

[config.txt](https://github.com/LlmDl/Towny/files/1167006/config.txt)

3. Your townyperms.yml :
[towny_perms.txt](https://github.com/LlmDl/Towny/files/1167007/towny_perms.txt)

4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

I have disabled this within the config.

**Comment by LlmDl** [comment]
The version you say you use and the version your startup shows doesn't match. I cannot reproduce the town / nation being deleted when land is unclaimed. If you choose to resubmit this issue please provide better steps to reproduce the issue.
