### ISSUE TITLE
Outposts Not Deleting - outpost spawns still remain after /unclaim

### ISSUE THREAD

**Issue by AdamTragedy** [LlmDl/Towny#2644]
After unclaiming an outpost, the outpost is still present in the database and people can still teleport to its spawn coordinates with /t outpost

**What steps will reproduce the problem?**

1. Create an outpost and claim some chunks surrounding its main claim
2. Unclaim that outpost
3. Save-all, shutdown the server, watch in the MySQL database and the outpost spawn is still there, even after rebooting the players can still teleport to the outpost

**What is your Towny version?**

0.91.4.9

**What is your spigot/craftbukkit version?**

Spigot 1.12 (most recent version, up to date as of 7/24/2017)

**Comment by LlmDl** [comment]
Skipped form

**Comment by AdamTragedy** [comment]
You're a cunt.

**Comment by LlmDl** [comment]
You're lazy and can't follow instructions. I bet there's lots of other people who would rather ignore you.
