### ISSUE TITLE
You can set a mayor as an outlaw and then they are kicked from town

### ISSUE THREAD

**Issue by elian1203** [LlmDl/Towny#2645]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. As mayor promote (Johnny) to a rank that has access to add outlaws
2. As Johnny, add your mayor as an outlaw
3. Mayor is kicked and someone else receives mayor

### What is the expected output?
1. The mayor not being kicked by anyone else. I'd just recommend forcing players to kick a player from town before being able to add them as an outlaw <3.

### What is your Towny version?
Do not say "latest".
0.91.4.9

### What is your spigot/craftbukkit version?
Do not say "latest".
1.12

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**

Literally not wasting my time with this.

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Fixed and a part of 0.91.4.10

It's included in this build: https://www.dropbox.com/s/q6t4kp5hr1u1wkp/Towny.jar?dl=0
