### ISSUE TITLE
Towny somehow preventing damage to blocks from TNT outside of towns

### ISSUE THREAD

**Issue by TheZenKitteh** [LlmDl/Towny#2646]
I've spent the last week trying to figure out why TNT doesn't damage blocks. I've went through every plugin I could think of and checked every line for anything dealing with TNT. Finally out of desperation I downloaded a plugin manager that would allow me to disable plugins one by one. I just did that and the TNT damaged blocks after Towny was disabled. What I can't figure out is how is it blocking TNT damage? Unless I'm blind, I can't find any setting that is incorrect that could prevent TNT from damaging blocks outside of towns. The entire world is safe from TNT right now. I have another issue but I'm not sure if it's towny and that is PVP being disabled worldwide despite everything looking correct to allow PVP. At this time of night I can't test because there are no players on since the server is still fairly new. If it turns out Towny is preventing PVP too, I'll post a new issue and link to this issue as there is never any errors.

### What is your Towny version?
0.91.4.9

### What is your spigot/craftbukkit version?
git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/raw/YPccYsWX

2. Your Towny config.yml (if using MySQL please remove password,) 
https://pastebin.com/raw/f5QsAF8a:

3. Your townyperms.yml :
https://pastebin.com/raw/ap09Kde0
4. Your log's error : 
No errors

(optional) If this is to do with permissions, 
5. Your permissions file :
Not a permissions issue that I can tell.

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Could you take a screenshot of the /tw output please

**Comment by LlmDl** [comment]
Closing this ticket due to lack of response, if you decide to share the /tw output, link your image (on imgur.com or similar) here and I'll reopen this ticket. Otherwise I'll assume you figured out it could be the /tw toggle explosion setting.
