### ISSUE TITLE
Towny error "Format specifier '%s'" when addning a town with only 1 resident to nation.

### ISSUE THREAD

**Issue by Bezod** [LlmDl/Towny#2649]
### What steps will reproduce the problem?
1. Create town with only 1 resident. 
2. Leader of nation runs command /n add
3. Nation leader sees error "Format specifier '%s'"  (image linked bellow)

### What is the expected output?
1. Town should be added to nation without error.
2.
3.

### What is your Towny version?
0.91.4.10

### What is your spigot/craftbukkit version?
Paper version git-Paper-1155 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://hastebin.com/kiyefuwuhe.md
2. Your Towny config.yml (if using MySQL please remove password,) : https://hastebin.com/ximitoveja.coffeescript
3. Your townyperms.yml : https://hastebin.com/wuzafagiru.vbs
4. Your log's error : https://i.imgur.com/1TNEpcg.png No error shows up in console (even with debug enabled). Only players see the error.

**Comment by Beelzebu** [comment]
Seems that the error comes when you set this option and the nation doesn't have the required residents.
`required_number_residents_join_nation: '2'`

**Comment by LlmDl** [comment]
https://www.dropbox.com/s/q6t4kp5hr1u1wkp/Towny.jar?dl=0

Give that one a shot.

**Comment by LlmDl** [comment]
Fairly sure this was fixed.
