### ISSUE TITLE
[Suggestion] Please Support Dynmap!

### ISSUE THREAD

**Issue by PamMC** [LlmDl/Towny#2653]
I like this wonderful plugin, and dynmap.
So can you support dynmap, to show Towny plots in dynmap?
That will make the plugin perfect
Thank you.

**Comment by esmith715** [comment]
There is a towny version of dynmap

**Comment by Wowserman** [comment]
@esmith715 I believe he's suggesting plot inspections on the Towny Dynmap, as of right now the Dynmap only shows global town information not plot specific information.

**Comment by LlmDl** [comment]
The authors of Towny are not the authors of Dynmap-Towny. You can ask them to add support for Towny's plots.
