### ISSUE TITLE
Upgrading Towny causes SQL problems

### ISSUE THREAD

**Issue by RednedEpic** [LlmDl/Towny#2654]
### What steps will reproduce the problem?
Loading Towny in an older version with MySQL then updating.

### What is the expected output?
For Towny to load correctly.

### What is your Towny version?
"v0.91.4.10".

### What is your spigot/craftbukkit version?
"Spigot-1.12-R0.1-SNAPSHOT".

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Logs: https://pastebin.com/BsvSCYHC
2. Config: https://pastebin.com/tZBcZyrd
3. Perms: https://pastebin.com/L8XZDgzb
4. Error: https://pastebin.com/HYRkUsLs

What happens is basically when updating from an earlier version of Towny using MySQL is that the older version loads fine but when loading in a newer version, it throws an error as supplied above.

Thanks for taking your time to read this.

**Comment by LlmDl** [comment]
Which version did you upgrade from?

**Comment by RednedEpic** [comment]
Sorry, I upgraded from v0.91.4.0.

**Comment by BlackBeltPanda** [comment]
I had the same issue. I just added the missing column to the table in the database and it worked.

**Comment by LlmDl** [comment]
This has been fixed, and will be part of 0.91.4.12. Big thanks to Articdive
