### ISSUE TITLE
Issue with unclaimed generation

### ISSUE THREAD

**Issue by AIphaDragon** [LlmDl/Towny#2660]
Hello,
We have got an issue with generation of unclaimed areas.
The matter is, that in default configs there are blocks, which are ignored during generation: GOLD_ORE,LAPIS_ORE,LAPIS_BLOCK,GOLD_BLOCK,IRON_BLOCK,MOSSY_COBBLESTONE,TORCH,MOB_SPAWNER,DIAMOND_ORE,DIAMOND_BLOCK,SIGN_POST,WALL_SIGN,GLOWSTONE
We wanted to add some more blocks to ignored: IRON_ORE,REDSTONE_ORE,COAL_ORE.

But the problem is, that during unclaiming plot and generating it, new blocks are not ignored and are generated normally according to world's seed. We have tested the default blocks - everything works good.

So, how can we provide new blocks to be ignored during generation?

- Our Towny version: 0.91.4.9

- Our Spigot version: 1.11.2

Server startup: https://pastebin.com/hiU1n9hC
Towny config.yml: https://pastebin.com/1miCTjv3
Towny perms: https://pastebin.com/BSGw9BwU

**Comment by LlmDl** [comment]
That section of hte config is only default settings for newly made worlds, are you configuring the towny\data\worlds\WORLDNAME.txt file when you're testing?

**Comment by AIphaDragon** [comment]
Oh, I didn't think it was for new words. Now, having configured the existing world, everything works okay. Thank you very much
