### ISSUE TITLE
Suggestion: Outpost delete command

### ISSUE THREAD

**Issue by Managering** [LlmDl/Towny#2663]
Hi,

Please add a command (perhaps a admin command) to delete outpost claims as they can sometimes bug, plus it could be easy on use to unclaim a big outpost that is no longer being used.

for example:
/ta unclaim outpost 4
'Are you sure you want to delete outpost 4? This will unclaim all plots connect to it! Type /ta uclaim outpost 4 again to confirm'

Thank you :)

**Comment by LlmDl** [comment]
/t unclaim outpost is now a command as of 0.91.4.14, it should even clean up the picky non-outpost townblocks for our mysql users (which we weren't able to clean up auto-magically.)
