### ISSUE TITLE
Area no longer oupost after plugin reload or server restart but plots remain.

### ISSUE THREAD

**Issue by Croyd** [LlmDl/Towny#2664]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Claim an outpost.
2. Either reload towny or wait for server restart.
3. Area is now just town plots and not considered an outpost.

### What is the expected output?
1. Outpost persisting after server or towny reload.

### What is your Towny version?
0.91.4.11

### What is your spigot/craftbukkit version?
Spigot 1.12.1 #1390

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :https://pastebin.com/dzP8GE1L
2. Your Towny config.yml (if using MySQL please remove password,) :https://pastebin.com/GkFHtYZf
3. Your townyperms.yml :https://pastebin.com/SAXdt4sX
4. Your log's error : no error is shown.

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by BlackBeltPanda** [comment]
Probably the same as #2641

**Comment by LlmDl** [comment]
Please retest this using 0.91.4.12, released today.

**Comment by LlmDl** [comment]
And yes, closing this because it is more than likely the issue with outposts and saving in mysql.
