### ISSUE TITLE
[REQUEST] REGISTER plugin / Translating Towny

### ISSUE THREAD

**Issue by AIphaDragon** [LlmDl/Towny#2666]
Hello,
We are non-english server and we want to fully translate Towny plugin. For this, we require Register plugin for compilation.
So, could you please help us, how to find .jar file of this plugin, where to search? Or, could you please send us this plugin, if you have it?
We are looking forward to your answer and thank you in advance.

**Comment by Beelzebu** [comment]
Here you have all the libs that Towny uses: http://palmergames.com/file-repo/libs/

**Comment by LlmDl** [comment]
The Ant build file in Towny will download all the required libs from teh above repo.
