### ISSUE TITLE
Requesting the Towny EULA

### ISSUE THREAD

**Issue by IsaiahJM97** [LlmDl/Towny#2667]
Hello, I did delete the format here because I am not making a ticket, just a request. I was told that selling in-game towny blocks with in-game money is against the Towny EULA. Would someone mind posting it please? A link would be appreciated.

**Comment by LlmDl** [comment]
Using in game money is something that is in-built to Towny using the /towny bonus buy command.

It is selling townblocks for actual money that isn't allowed.
