### ISSUE TITLE
[REQUEST}] Multiworld chat problem

### ISSUE THREAD

**Issue by AIphaDragon** [LlmDl/Towny#2672]
Hello,
We are using MultiVerse on our Towny server and we created the second world - resource world, where we have disabled Towny there.
The problem is with chat, as resource world does not support Towny Chat anymore. So, we have tried to combine Towny with Essentials Chat. It caused the issue, when OP'ed players cannot write in global chat, only through /broadcast, as nobody can hear them.
Could you please advise us, how to leave only Towny chat in our resource world, while it is disabled there, or are there any other solutions?
We are looking forward to your answer

Towny version: 0.34
Spigot version: 1.11.2

Pastebins of
TownyChat: https://pastebin.com/3ez4n12G
Channels: https://pastebin.com/j2dYQFqk

**Comment by LlmDl** [comment]
Don't disable towny in the resource world, you can set the resource world to not be claimable using /tw toggle claimable. Hopefully that will work for you.
