### ISSUE TITLE
towny_default_modes permission not work

### ISSUE THREAD

**Issue by MrXmarks** [LlmDl/Towny#2674]
i'm using luckperms plugin.
permission for plotborder, map or other doesn't work.

this is my towny permissions :
[https://pastebin.com/SgksCdTL](url)

**Comment by Beelzebu** [comment]
Use towny.default.modes instead of towny_default_modes

**Comment by MrXmarks** [comment]
still same.
@Beelzebu @LlmDl

**Comment by LlmDl** [comment]
Skipped form.
