### ISSUE TITLE
Suggestion: Way to disable /town {name} & /res {name}

### ISSUE THREAD

**Issue by AIphaDragon** [LlmDl/Towny#2675]
Hello,
We have got some complaints from players, that everyone can see their information about player and towns. We were asked to forbid such commands, as /town [town name] and /resident [nick].
There were no perms, that could allow or disallow player to do that.
So, how could we forbid such commnads?

We are looking forward to your answer.

**Comment by LlmDl** [comment]
Part of 0.91.4.12
