### ISSUE TITLE
[Suggestion] Custom variable in config to put Town in front of nation

### ISSUE THREAD

**Issue by Articdive** [LlmDl/Towny#2677]
ChatConfig.yml : 
# First %s is the nation tag, second is the town tag.
Would really appreciate if you could add a custom variable for town and nation instead of just first and second, then we could put Town : Nation & not **always** Nation : Town

**Comment by LlmDl** [comment]
Could you not just use teh individual tags, in the order you want? ex: {towntagoverride}:{nationtagoverride}

**Comment by Articdive** [comment]
I suppose this would be possible but then a space would be left over if nation doesnt exist , and then when there is no nationtag the town tag would have an unused ":", which would look kinda bad.

**Comment by LlmDl** [comment]
TownyChat 0.50 contains this change
