### ISSUE TITLE
Unable to toggle town board.

### ISSUE THREAD

**Issue by ChibbyGit** [LlmDl/Towny#2678]
### What is your issue?
Just wanted to report that there is no way to toggle the state of town boards. (enable/disable)
No configuration or permission that allow toggling of this message/feature.

### What is your Towny version?
0.91.4.11

### What is your spigot/craftbukkit version?
CraftBukkit version git-Spigot-7754231-362ed32 
(MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by LlmDl** [comment]
Do you mean where you're shown the town board when you log in, or the entire town board feature?

**Comment by LlmDl** [comment]
Will be available in 0.91.4.12
