### ISSUE TITLE
towny plot types not working

### ISSUE THREAD

**Issue by jordanwilliams1** [LlmDl/Towny#2683]
### What steps will reproduce the problem?
1. Install towny on your server
2. Change config.yml default_perm_flags to https://pastebin.com/raw/PHVv0DX7
3. Reload the server and add someone to your town.
4. do /plot set farm
5. The player won't be able to break any blocks on the plot even if they are in farm_plot_allow_blocks

### What is the expected output?
1. for players to be able to break the plots defined in the config under farm_plot_allow_blocks

### What is your Towny version?
  version: 0.91.4.11

### What is your spigot/craftbukkit version?
git-Paper-1155 (MC: 1.12)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/raw/cS1KPCi2
2. Your Towny config.yml: https://pastebin.com/VT9YRPam
3. Your townyperms.yml : https://pastebin.com/VpxYq2yn
4. Your log's error : there is no error

**Comment by LlmDl** [comment]
Go to the plot you're testing and do /plot perm, take a screenshot and host it on imgur.com and link it here.
