### ISSUE TITLE
World Save event causing lags

### ISSUE THREAD

**Issue by AIphaDragon** [LlmDl/Towny#2685]
Hello, we have faced the problem with Towny, that sometimes our server freezes and lags for a short time. There are only up to 30 players online.
According to our timings, there was a problem with World Save event.
https://timings.spigotmc.org/?url=momemakucu

We have no AutoSave plugins. Could it be connected with exactly Towny plugin? If yes, is there a way to reduce chunk data storage time in cofigs? 

Here is the list of our plugins:
CrazyCrates, Questioner, AntiAFKPlus, BetterChairs, RecipesGUI, Arconix, VoxelSniper, EpicWorldGenerator, Ping, ViaVersion, HideStream, CoreProtect, HealthBar, Essentials, ClearLag, AutoMessage, CreativeLimiter, WorldBorder, Multiverse-Core, ProtocolLib, NoCheatPlus, eZProtector, FastAsyncWorldEdit, EssentialsChat, PermissionsEx, CS-CoreLib, StaffChat, Vault, TrueCommand, HolographicDisplays, KillerMoney, SkinsRestorer, PacketBookFix, ChestCommands, Multiverse-Inventories, ChatGuard, EXPBottles, EssentialsSpawn, PlayerHeads, TitleManager, PaidRanks, WorldEdit, Orebfuscator4, CustomEnderChest, SimpleFreeze, SafeTrade, Citizens, ColoredTags, Reporter, KitPreview, WorldGuard, CitizensCMD, Quests, 

Towny config.yml: https://pastebin.com/1kcSPcUU

Our Towny version: 0.91.4.9

Our Spigot version: 1.11.2

If you could, please help us solve this problem.
We are looking forward to your answer

**Comment by LlmDl** [comment]
Nothing points to Towny here. You would do better to have run your timings for longer than 153 seconds. World save is likely unloading/saving of chunks.
