### ISSUE TITLE
Suggestion: Outpost list

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [LlmDl/Towny#2690]
I think it would be cool to have a outpost list command, showing all the available outposts.

Also a neat thing would be a GUI with pages for that, the mayor or whoever can add outposts and they select the name and icon and lore, so you do /t outposts and it opens a GUI.

**Comment by LlmDl** [comment]
An outpost list is a great idea, I don't think we'll do any GUIs though. There are Towny GUI plugins out there for free already.

**Comment by LlmDl** [comment]
Now a thing in 0.91.4.14
