### ISSUE TITLE
Lag for everyone online while running town/nation/player lookup commands

### ISSUE THREAD

**Issue by Bezod** [LlmDl/Towny#2697]
### What steps will reproduce the problem?
1. Have much town data
2. Run a town/player/nation lookup eg /town America
3. Everyone online will lag until towny delivers the request, usually around 2 seconds. Very apparent when a lot of people are online.

### What is the expected output?
1. No lag
2.
3.

### What is your Towny version?
0.91.4.11

### What is your spigot/craftbukkit version?
git-Paper-1211 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://hastebin.com/ozicotiduf.md
2. Your Towny config.yml (if using MySQL please remove password,) : https://hastebin.com/ofedinowas.coffeescript
3. Your townyperms.yml : https://hastebin.com/vozavobuca.vbs
4. Your log's error : No error in console

Youtube video: https://www.youtube.com/watch?v=ek8WFquW-SQ&feature=youtu.be

I've talked with llama before about performance of mysql and it should about the same as flatfile considering towny files are loaded into ram on boot.

**Comment by LlmDl** [comment]
Solved as best I can in 0.91.4.13
