### ISSUE TITLE
Towny War Issues

### ISSUE THREAD

**Issue by elian1203** [LlmDl/Towny#2698]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Toggle war on
2. Walk onto another town's plot
3. No health points lost for the plot

### What is the expected output?
1. The chunk will lose health and eventually be claimed

### What is your Towny version?
Do not say "latest".
0.91.4.12

### What is your spigot/craftbukkit version?
Do not say "latest".
1.12.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/rvnHJduT
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/eXg9DKLt
3. Your townyperms.yml :
https://pastebin.com/Wa08f68p
4. Your log's error : 
N/A
(optional) If this is to do with permissions, 
5. Your permissions file :
(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

Not sure if I've just configured it wrong or what, but I'd like to have it fixed so I can host a war soon. Additionally, the War HUD lags the server a little; I would suggest managing the scoreboard asynchronously if possible.

**Comment by LlmDl** [comment]
Is your town in a nation? Is the town you're trying to attack also in a nation? Do your nations consider each other enemies? Does your war hud show Attackable: yes on the plots you're trying to attack.

**Comment by elian1203** [comment]
Both towns are in separate nations. Adding the other nation as an enemy does allow me to attack, though it didn't used to be like this so I'm a little confused. Also, the HUD shows no "Attackable" in any case.

**Comment by LlmDl** [comment]
The requirement for enemies to be declared was always meant to be a thing, lots of war bugs were fixed recently. Can you show me a screenshot of your war hud while on enemy land?

**Comment by elian1203** [comment]
https://gyazo.com/aead19cc3c526cb2cc8a5c6521705946

**Comment by LlmDl** [comment]
Which nation are you in, in that screenshot?

**Comment by elian1203** [comment]
mlgn

**Comment by LlmDl** [comment]
Ah, the attackable part of the warhud only shows when  only_attack_borders: 'true' is set. Looks like the war is working for you now though?

**Comment by elian1203** [comment]
Yeah, all good. Thanks for the help.
