### ISSUE TITLE
Suggestion: War event should survive server time outs/restarts

### ISSUE THREAD

**Issue by Bezod** [LlmDl/Towny#2702]
Had a huge war and the server crashed, it would be great if the war could continue after the server booted up again :)

**Comment by LlmDl** [comment]
Looking at this in depth, there is no realistic way to store the progress of a war without having to constantly save the progress as it happens. All of the nation/town/townblocks statuses are worked on in memory.

**Comment by Bezod** [comment]
I see. Would it be possible to store war progress on disk every 1/2/5 minutes? Better to lose some progress than all.

**Comment by LlmDl** [comment]
Might be in the future but it's not a high priority, the focus ought to be on not having crashes of course.
