### ISSUE TITLE
Suggestion: Ability to list who has what towny ranks in a nation/town

### ISSUE THREAD

**Issue by Bezod** [LlmDl/Towny#2703]
Good tool for large towns/nations to check which players have a certain towny rank.

**Comment by LlmDl** [comment]
Like a /town ranks and /nation ranks command that outputs page-inated lists of ranks and their members?

**Comment by Bezod** [comment]
Exactly!

**Comment by LlmDl** [comment]
Is this not already accomplished with the command /town ranklist?

**Comment by LlmDl** [comment]
2+ weeks of inactivity. Closing ticket.
