### ISSUE TITLE
Towny new day essentials error reposted.

### ISSUE THREAD

**Issue by Metisuneatn** [LlmDl/Towny#2704]
### What steps will reproduce the problem?
1. Its just towny new day which is set to noon est for us. 
2. I attempted to recreate it on a test server and could not.
3.

### What is the expected output?
1. Towny new day should have taken taxes
2.
3.

### What is your Towny version?
Do not say "latest".

The error is on 0.91.4.11 but I updated again to v0.91.4.12. And got it again.

### What is your spigot/craftbukkit version?
Do not say "latest".

spigot-7754231-94b0980 1.12.2

1. Your full server startup from the logs\latest.log :
https://pastebin.com/na23XjHM

Due to my terms of service agreement with the server I cannot give you FULL logs of the entire startup. Here are the towny parts of the log. I can look for specific startups for you like the essentials startup.

2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/ZWSYPbFf
I am aware it is missing some newer stuff, we just started updating due to the tax error and have not added everything new yet.

3. Your townyperms.yml :
https://pastebin.com/puQbh0KS

4. Your log's error : 
https://pastebin.com/j0NjaGkq

(optional) If this is to do with permissions, 
5. Your permissions file :

n/a

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

n/a

**Comment by LlmDl** [comment]
Aside from Towny trying to access the accounts and generating the error, the entire error is within essentials. Still don't think this is Towny. Ess Eco has been having trouble for years now with town and nation bank accounts reseting at random. The inability to reproduce the error on a test server could point to this being a fairly random thing too.

**Comment by LlmDl** [comment]
Does your test server have the identical essentials database?

**Comment by Metisuneatn** [comment]
It does not, the database is pretty large and I didn't get a chance to move it.

I will note that I believe we cleared inactive essentials data on Sunday night (I think, I am not positive) so I'm not sure if that perhaps caused the error. We do this often though so I'm not sure if that makes a difference. I created a new issue ticket on their end as well (EssentialsX)

**Comment by LlmDl** [comment]
Lol "The towny creator instantly said its essentials."

**Comment by Metisuneatn** [comment]
Truth :D 

The amount of arguments over this issue lol I'm just like screw this look at me look at me.

Is there any known tempfix or anything I can do with towny that can at least get taxes to work? Or is this just stuck till a hopeful essentials fix?

**Comment by LlmDl** [comment]
I've been telling people to try out the fork of iconomy 5 I maintain on towny.palmergames.com. Its got a convert feature that's worked for everyone so far except this poor guy: https://github.com/LlmDl/Towny/issues/2676

**Comment by Metisuneatn** [comment]
I cant get iconomy to work either, not sure if it fixed the new day I cant even run /money yet.

Should I post the info here or create a new ticket?

**Comment by Metisuneatn** [comment]
I cant get iconomy to work correctly should I post it here or create a new ticket?
