### ISSUE TITLE
Suggestion: Town invite cooldown on new players

### ISSUE THREAD

**Issue by Bezod** [LlmDl/Towny#2705]
Whenever a new player joins I've noticed that everyone spams that player an invite making it difficult to /accept the right town to join. This could be solved by having a cooldown which prevent mayors from inviting new players.

**Comment by LlmDl** [comment]
That would be possible. For the time being just put the players into a town automatically when they join, using the option in the config.

**Comment by Portanna** [comment]
A cooldown is really needed, the spam issue that the OP is experiencing is a common problem.

**Comment by LlmDl** [comment]
This is a thing as of 0.91.4.14
