### ISSUE TITLE
Assistants cant build or destroy?

### ISSUE THREAD

**Issue by Rollo37** [LlmDl/Towny#2706]
I'm just playing on a normal Minecraft Towny server, and everyting is working perfectly, ecxept for 1 thing, i cant make my Assistants in my towny to build or destroy... When i give them the highest rank ecxept for Mayor (assistant) they only can switch and itemuse.... I do /t set perm assistant build on (destroy as well) But nothing happened? No one know why.... I've seen a Danish server called FreakyVille, they just added a "Vice-mayor" rank, who could build, destroy and alot more commands. But when i do that command doesn't anything change... Its not a fail by the server, ever server gets theese fails... I can add so everyone can build or destroy, but i only want my assistant to do that... Hope you can help...

**Comment by LlmDl** [comment]
Your server admin probably just has to put the towny.claime.owntown.* node in the assistant rank in the townyperms.yml
