### ISSUE TITLE
Random Exception with inventory

### ISSUE THREAD

**Issue by Wolf2323** [LlmDl/Towny#2707]
There was a random exception in the log

### What steps will reproduce the problem?
1. not clear

### What is the expected output?
there should no exception

### What is your Towny version?
0.91.4.13

### What is your spigot/craftbukkit version?
1.12.2

### Please use Pastebin.com to link the following files:
Your Towny config.yml https://pastebin.com/xu7J8rBF
Your log's error : https://pastebin.com/nLyFLEAX

**Comment by LlmDl** [comment]
Looks like something blew up, a chest of some type, that was being regenerated? Does that sound right?

**Comment by Wolf2323** [comment]
i i think so, but is is hard to reproduce, because i don't know the situation

**Comment by Articdive** [comment]
Happens when a double chest is blown up and regenerated

**Comment by LlmDl** [comment]
Fixed as of 0.91.4.16
