### ISSUE TITLE
[Sugghestion] Towny townblocks

### ISSUE THREAD

**Issue by maxlehot1234** [LlmDl/Towny#2709]
Hi, is it possible for you to remove:
![image](https://user-images.githubusercontent.com/5159244/31856699-a8a3088a-b695-11e7-8435-557b1e5dfb7c.png)

This is simply bad to having this on a server... Also, if a server want to break eula, it was his choice, not yours :(

Why you force to having this text?

Thank you

**Comment by LlmDl** [comment]
Duplicate: https://github.com/LlmDl/Towny/issues/2479
