### ISSUE TITLE
Command to remove bonus townblocks

### ISSUE THREAD

**Issue by Portanna** [LlmDl/Towny#2710]
Is there any way with commands to remove previously given bonus townblocks from a town? If there isn't, I suggest creating a command to clear or to remove townblocks that have been given with "/ta givebonus {town} {#}".

An example command would be "/ta removebonus {town} {#}", and to clear, "/ta clearbonus {town}".

Why is this needed?
If your server gives bonus as a prize for an event or build battle and you have given plots as part of the prize for winning the contest, but then realize that the players have been cheating using some mod and want to take the prize back, it would be really cool to have a command to do that instead of having to manually edit the database in order to remove bonus claims.

**Comment by LlmDl** [comment]
You can just use /ta givebonus NAME -AMOUNT

**Comment by Portanna** [comment]
Thanks, didn't know that
