### ISSUE TITLE
iconomy 5 super fast request

### ISSUE THREAD

**Issue by Metisuneatn** [LlmDl/Towny#2712]
Just wanted to know if its possible to remove the word "dollars" from +balance placeholder. I looked into the template and plugin.yml and couldnt find a way to just remove the word. 

Sorry if this isn't the right area for iconomy suggestions, couldn't find its own github and just assumed it would be fine to post here

**Comment by LlmDl** [comment]
Would it be more helpful if the word was configurable?

**Comment by Metisuneatn** [comment]
Oh yes totally or able to be left blank even

**Comment by LlmDl** [comment]
Uhm, I just took a look at the config, you can already set what the currency is called. I tested this:
'''
System:
    Default:
        Currency:
            Major: [ '', '' ]
'''
Then in game I did /money and saw my balance without the trailing Dollars.

Is it something else you want it to do than this?

**Comment by Metisuneatn** [comment]
I'm a special cookie whose test server doesn't like to load in config files properly lol. My config started at system: formatting. Reset it a few times and it finally loaded in that setting.

My bad! ><
