### ISSUE TITLE
Suggestion: min_plot_distance_from_town_plot for outposts

### ISSUE THREAD

**Issue by Bezod** [LlmDl/Towny#2714]
A configurable distance from towns where no outposts can be claimed.

**Comment by LlmDl** [comment]
Does the min-distance-between-homeblocks not accomplish this already? Its supposed to cover both outposts and homeblocks.

**Comment by Johnsonk2** [comment]
Towns being able to set an outpost 1 chunk next to another town. If you go from a homeblock, whats the minimum distance for another towns outpost? Unless it's disabled by default, I've never seen that.

**Comment by Bezod** [comment]
In our case we want people to be able to place towns close to other towns. Outposts on the other hand are used block expansion of enemy towns/nations which is why we want to set a higher max distance between outposts and towns.

**Comment by LlmDl** [comment]
A thing as of 0.92.0.10:
```
    - New Config Option: town.min_distance_for_outpost_from_plot
      - default: 5
      - Minimum number of plots an outpost must be from any other town's plots.
      - Useful when min_plot_distance_from_town_plot is set to near-zero to allow towns to have claims 
        near to each other, but want to keep outposts away from towns.
```
