### ISSUE TITLE
/town jail Commands don't exist

### ISSUE THREAD

**Issue by Sprungente** [LlmDl/Towny#2717]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. I use /town jail or any subcommand from /town jail like /town jail ?
2. I read the message
3. Look in the log with debugmode - No error accoured

### What is the expected output?
1. Chat : The German version, that this command don't exist
2.
3.

### What is your Towny version?
0.91.4.13

### What is your spigot/craftbukkit version?
This server is running CraftBukkit version git-Spigot-93e20b3-b8f84f3 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
I controlled the hole log more times and all is works normally. No error, no warnings.

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml : 
7. Your channels.yml :

Thank you for helping

**Comment by LlmDl** [comment]
You skipped the form, which is besides teh point, there is no /town jail command, there is a /town toggle jail command.

**Comment by Sprungente** [comment]
ok look at this picture: https://picload.org/view/drrordwi/unbenannt.png.html 
You see: the helping list display that command, that not exist

When we talking about the helping list, please add a /plot set ? - Helping menu. At the moment when someone use /plot set ?, then will be open the /plot set perm ? - Menu

I know it isn't an importent bug but i think it is nice to know. 

BTW: Thank you for answering.

**Comment by LlmDl** [comment]
Fixed those in 0.91.4.14
