### ISSUE TITLE
Death penalties not working

### ISSUE THREAD

**Issue by MidnightSugar** [LlmDl/Towny#2718]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Set price_death_pvp_only to false
2. Die of natural causes or player kills

### What is the expected output?
1. Money should be taken from account

### What is your Towny version?
Do not say "latest".
0.91.4.10

### What is your spigot/craftbukkit version?
Do not say "latest".
git-Spigot-93e20b3-31d3159 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by LlmDl** [comment]
Fixed as part of 0.91.4.14
