### ISSUE TITLE
Certain "block" types get removed when you unclaim a chunk even with revertunclaim enabled

### ISSUE THREAD

**Issue by ullert** [LlmDl/Towny#2720]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. With revertunclaim toggled off in-game and turned off in the config, certain "block" types still disappear when you unclaim(also if they were placed even before claiming the chunk in the first place)
2.The "blocks" so far have been, placed redstone, repeaters, signs, redstone torch, torch, pressureplates, anything planted like seeds or full grown wheat, etc.

### What is the expected output?
1.That all placed blocks and items remain after using /t unclaim

### What is your Towny version?
Do not say "latest".
0.91.4.11

### What is your spigot/craftbukkit version?
Do not say "latest".
Not sure how to check spigot version....
Update:(1.12.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

Some logs were too big to be created, maybe im doing it wrong? (first time im using pastebin)
1. Your full server startup from the logs\latest.log : 
[(https://pastebin.com/fP0winwR](url)
2. Your Towny config.yml (if using MySQL please remove password,) : 
[https://pastebin.com/WuCCmGQ1](url)
3. Your townyperms.yml :
[https://pastebin.com/w49gG8Pi](url)
4. Your log's error : Not sure??

**Comment by Articdive** [comment]
For future reference to check the version of spigot/craftbukkit type /version as a command.

**Comment by LlmDl** [comment]
Please pastebin.com your towny\data\worlds\WORLDNAME.txt please

**Comment by ullert** [comment]
[https://pastebin.com/eGxECrdG](url)
Thanks, thats the file! 
I took a look in that file and i can see whats going on, but why is the "usingPlotManagementDelete" set to true? Is there a command to turn it off(well now that i know about it i guess i can just change the statement in here to false). Or is there a reason why these specific items are set to disappear?

**Comment by LlmDl** [comment]
I figured that was what was happening, I dont remember if there's a /tw toggle command for that feature. Just set it to false in the world files and it wont happen again. The reason behind it was to have remove signs (locks for deadbolt/lockette) and other items that 'pop' off of blocks when the blocks are reverted. Not using it means that fallen towns are covered in items.
