### ISSUE TITLE
Suggestion: Percentage Death Penalty Cap

### ISSUE THREAD

**Issue by MidnightSugar** [LlmDl/Towny#2721]
I have my death penalty set to a percentage so that newer players aren't hit as hard when they die. However my current problem is that as people get richer and richer, eventually they lose ridiculous amounts of money when they die.

The solution I have thought of would be to add an option to cap the money loss. For example,  if I set the the percentage to 5%, and the cap to 5000. Then people will lose 5 % of their money until they reach $5000. If they get more money, they will continue to just lose $5000.

**Comment by MidnightSugar** [comment]
I realized my example of this is worded horribly. Here is a better example if tax percentage is set to 5% and cap is set to 500.

Player has $100, loses $5 on death.
Player has $1000, loses $50 on death
Player has $10000, loses $500 on death
Player has $100000, loses $500 on death

**Comment by LlmDl** [comment]
That's what I was thinking you meant.

**Comment by LlmDl** [comment]
This is now a thing for players only as of 0.92.0.2

Towns and Nations are still uncapped. Please clarify if you want them capped as well, and wether there ought to be different caps for those.
