### ISSUE TITLE
Suggestion: Town-Made ranks with Town-decided Permissions

### ISSUE THREAD

**Issue by daftprophet** [LlmDl/Towny#2724]
On my server, I am in a town of about 80, and our mayor (and nation king) isn’t on as much. Me, being one the most trustworthy in the nation is the “regent” as you would say. The only problem in this is that the king doesn’t want to transfer leadership to me, as he isn’t gone long term. He is gone a week or so at a time, and he always comes back.  The bigger problem is that, even as being the second most powerful rank, assistant has 0 power when it comes to the nation, the bank, and other necessary things that it could have.

My suggestion is that you could add a way to create special ranks (additional to assistant, etc.) that you can decide the permissions they have, or give specific people permissions. Is this a possibility and what do I need to know from you guys?  Multiple people on the server which I play agree that a system like this is a good idea and it allows for things like a dual leadership, or making people treasurers, or property dealers, etc.

**Comment by LlmDl** [comment]
The townyperms.yml already allows for admin-created ranks. Your server admin can make the ranks you're talking about.

**Comment by daftprophet** [comment]
LlmDl I want to point out that I know it was added. I feel that there should be an enable-able thing that allows the MAYORS to do this, not the admins.

**Comment by LlmDl** [comment]
Since its related to permission nodes, admins can't really let mayors add permission nodes for their residents, or all kinds of malicious permission nodes could be handed out. Mayors can ask their admins to create ranks for their use. When it's done, mayors can then pass out the ranks to their residents.

**Comment by daftprophet** [comment]
So there is no way to make it so the mayor will only be given access to non-malicious nodes?

**Comment by LlmDl** [comment]
Not really, what is and isn't malicious is entirely up to the admin of the server. Since the number of ranks the admin can create is limitless, it doesn't really make sense to work around that feature.
