### ISSUE TITLE
TownyChat Prefixes and Suffixes problem

### ISSUE THREAD

**Issue by CadCal** [LlmDl/Towny#2725]
Image of issue : https://imgur.com/a/fCNet 

### What steps will reproduce the problem?
1.  _It just happened one day when I got on my server._

### What is the expected output?
1. _The titles and prefixes that go before the username are their variable from the chat config_

### What is your Towny version?
0.91.4.0

### What is your spigot/craftbukkit version?
_Craftbukkit version git-Spigot-d21162c-25959fa (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
(2 versions behind)_

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : _Couldn't fit logs into one paste._
2. Your Towny config.yml (if using MySQL please remove password,) :  https://pastebin.com/wapjCxhU
3. Your townyperms.yml: https://pastebin.com/tDL7visi
4. Your log's error : _No error, just need a simple explanation and fix_

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/pvjMzr0v
7. Your channels.yml : https://pastebin.com/hxviyfry

**Comment by LlmDl** [comment]
You skipped the server startup log, what version of TownyChat are you using?

**Comment by CadCal** [comment]
This is the server startup log:  https://pastebin.com/qZ2XMWC0
And here is the TownyChat Version: 0.47

**Comment by LlmDl** [comment]
Your pex is failing to load because the yaml formatting has been ruined (there's spaces or tabs where there shouldnt be.) If that doesn't fix your problem with townychat, make a new comment here and I'll re-open the ticket.
