### ISSUE TITLE
Error with messages of TOWNY

### ISSUE THREAD

**Issue by Golvore** [LlmDl/Towny#2727]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### Description
 When you do /t and you dont have town you receive the message:
 
  msg_err_dont_belong_town: '&cYou don''t belong to a town.'

 But in the latest version of towny this message don't works. When you execute / t, /town without belonging to a city you don't get message.

 (Other error >) The translations of Towny to spanish don't works correctly, i use es-mx translations and  " ´ " (accents) don't works correctly.  https://imgur.com/bw62Gpj

### What is the expected output?
1.
2.
3.

### What is your Towny version?
Do not say "latest".

0.91.4.15

### What is your spigot/craftbukkit version?
Do not say "latest".

Spigot 1.12.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Articdive** [comment]
The Spanish-Mexican lang file contains unknown charcters, for some nobody has updated them in a while and all the accents went missing, probably due to an IDE Error so, that is why there are no accents.

We don't speak Spanish let alone Mexican Spanish so we can't really update the file, unless some Mexican does it for us.

**Comment by Articdive** [comment]
As for the problem regarding /t & /town I'm sending in a pull-request to fix that.

**Comment by LlmDl** [comment]
Fixed in 0.91.4.16
