### ISSUE TITLE
Bug inventory

### ISSUE THREAD

**Issue by TheCalypso** [LlmDl/Towny#2729]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. When installing the plugin, since forever. 
2. I recently updated the plugin but nothing helps

### What is the expected output?
1. It is related to the inventory. When I craft or pick up an item, it does not stack with others.

### What is your Towny version?
Version Towny : 0.91.4.15
Version TownyChat : 0.49
Version TownyNameFix : 1.0.0

### What is your spigot/craftbukkit version?
Version Spigot : 1.12.1
But we can change version by going to Craftbukkit version 1.12.1 or 1.12.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/GagE4BX6
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/dC8yxH33
3. Your townyperms.yml : https://pastebin.com/VQNpg0Nm
4. Your log's error : https://pastebin.com/5bJjifnV

(optional) If this is to do with permissions, 
5. Your permissions file : PermissionEX https://pastebin.com/g0w6F3AX

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/zmFYjvGR
7. Your channels.yml : https://pastebin.com/fYZ8iAX1

**Comment by LlmDl** [comment]
This isn't an issue with Towny, it could be TownyWands, or something that actually does things to the player inventory. We do not have any effect on player inventory, item stacks.
