### ISSUE TITLE
Cannot Outlaw Mayors

### ISSUE THREAD

**Issue by lkjfdsaofmc** [LlmDl/Towny#2731]
No matter how many times I attempt to /town outlaw add [name] , if that person is the mayor of a town (any town) the command has no output. No failed message, no null message, and the person is not set as an outlaw according to /town outlawlist. This happens regardless if I am the leader of a town, opped, or leader of nation (as long as I have a title available to outlaw people). I have tested this with every person (about 4 mayors and 12 total people on the server) and all the people who are either nomads or residents can be outlawed and anyone who is a mayor cannot.

Running towny version: 0.91.4.15

Unsure about spiggot version. When I run the /version command in game I get the result:
This server is running CraftBukkit version
git-Spigot-7129aeb-c15d869 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
You are 6 version(s) behind

Server Latest.log: https://pastebin.com/akNvg2b9
Towny Configs: https://pastebin.com/MpLNjh4Y
Towny Permissions File: https://pastebin.com/VeBAL057
No error in log. (that I see)
 
bPermissions Group Perm File: https://pastebin.com/jZ5kJ8Q1

**Comment by LlmDl** [comment]
Good catch, thanks for the ticket, I will look into it.

**Comment by lkjfdsaofmc** [comment]
Would a list of other plugins I have be useful?

**Comment by LlmDl** [comment]
Nope, entirely our fault, this is fixed as of 0.91.4.16 (to be released soon.)
