### ISSUE TITLE
Bug involving initial teleport to jail.

### ISSUE THREAD

**Issue by Golvore** [LlmDl/Towny#2732]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### Description
 When i toggle jail for one resident of my town appears this message for resident: 'Waiting to teleport...' (msg_town_spawn_warmup: '&bWaiting to teleport...') and nothing happens, only appears this message.

 Essentials config: https://www.hastebin.com/kumaponaji.coffeescript

### What is your Towny version?
Do not say "latest".

Towny 0.91.4.15

### What is your spigot/craftbukkit version?
Do not say "latest".

Spigot 1.12.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Fixed in the forthcoming 0.91.4.16
