### ISSUE TITLE
Suggestion: Flag War additions

### ISSUE THREAD

**Issue by DracarysPro** [LlmDl/Towny#2736]
- Add a configurable max number of active flag per-nation. At the moment only Max Active Flags Per Person is configurable, what I suggest is adding a Max Active Flags Per Nation.

- Replace the chunk coordinates of the cell that is being attacked with the coordinates of the flag in the message that gets broadcast when a flag is being placed/defended, players often do not understand that the coordinates in chat are those of the chunk and get confused

- Add an in-game command to toggle the possibility to start a flag war (to place a flag generally speaking), so that the server owners can decide when to enable the flag wars without having to restart the server.

- When you place a flag on the enemy's soil successfully, while you are waiting for the flag to win the attack, players of your nation have all permissions on the attacked plot, I suggest to add a configurable toggle for this feature. (I tried editing the "warzone:" configuration section, in order to but it seems like this configuration section is not affecting the flag war system)

**Comment by LlmDl** [comment]
I'm sorry to inform you that flag war is no longer supported by myself. You're welcome to fork Towny and add what you're requesting and if it is in working order, make a Pull Request and I will add it to Towny.

For # 3, you can edit the config and use /ta reload to turn flag war on/off.
