### ISSUE TITLE
strange wild_revert_on_mob_explosion bug

### ISSUE THREAD

**Issue by Wolf2323** [LlmDl/Towny#2743]
### What steps will reproduce the problem?
1.place logs with cacao on it
2. let a creeperexplade
3. when the cacao is regenerated a dirt block is placed in front of it

### What is the expected output?
1. no dirt that appears!?

### What is your Towny version?
0.91.4.16

### What is your spigot/craftbukkit version?
Spigot 1.12.2 git-Spigot-5695bca-53fccdf

**Comment by LlmDl** [comment]
This is fixed now, good find.
