### ISSUE TITLE
Towny 92.0.0 Start Erros with german.yml

### ISSUE THREAD

**Issue by Wolf2323** [LlmDl/Towny#2746]
https://pastebin.com/fXvhVPGp

**Comment by LlmDl** [comment]
There was a flag missing, https://github.com/LlmDl/Towny/commit/18bccdbaefaf451c8d0912dce645005ae0a8b145

Try this and let me know if its fixed.

**Comment by LlmDl** [comment]
Works for me fine now, must have just been that one line's flag being deleted.
