### ISSUE TITLE
Cant claim town

### ISSUE THREAD

**Issue by Wolf2323** [LlmDl/Towny#2749]
When i try to clam with "/t claim", i get the msg_err_not_enough_residents message. This comes, because i have option "minimum_amount_of_residents_in_town_for_outpost: '10'". Is seems like there is a little issue with this code

### What steps will reproduce the problem?
1. Set the option minimum_amount_of_residents_in_town_for_outpost higher than your town resident number
2. try to claim a new plot for your town

### What is the expected output?
1. a claimed plot

### What is your Towny version?
0.92.0.0

### What is your spigot/craftbukkit version?
1.12.2

**Comment by LlmDl** [comment]
Fixed, thanks.
