### ISSUE TITLE
Towny and silkspawners regen issue

### ISSUE THREAD

**Issue by MsArtix** [LlmDl/Towny#2751]
### What steps will reproduce the problem?
1. Install towny and silk spawners
2. Place a spawner other than PIG (zombie and skeleton were tested)
3. Let a creeper blow up the spawner (make sure regeneration is on for explosions)
4. Wait till it all regens (spawner takes a few extra seconds to be replaced)
5. Look at the fancy new pig spawner that used to be something else. 

### What is your Towny version?
92.0.0

### What is your spigot/craftbukkit version?
1.12.2

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://hastebin.com/qolawevihi.md
2. Your Towny config.yml: https://hastebin.com/ixonodilij.coffeescript
3. Your townyperms.yml : https://hastebin.com/biyimefiyo.php

**Comment by LlmDl** [comment]
Fixed as of 0.92.0.2
