### ISSUE TITLE
Suggestion: Configurable max towns per nation

### ISSUE THREAD

**Issue by DracarysPro** [LlmDl/Towny#2752]
Add to the config a maximum amount of towns per nation, so that a nation cannot exceed a certain number of towns. Useful when you  want to avoid an enormous nation against little nations.

**Comment by LlmDl** [comment]
Looked  at https://github.com/LlmDl/Towny/issues/2402 and this ticket is a duplicate. A town cap and a % of residents cap to nations will happen.
