### ISSUE TITLE
Towny Bug/Glitch (Not 100% sure)

### ISSUE THREAD

**Issue by AccioAce** [LlmDl/Towny#2754]
Hello! I was wondering If anyone knows about towny plugin.

Towny: http://towny.palmergames.com/

I have a question to ask so does anyone know how to disable unclaim_delete blocks. Basically like when you /t claim outpost than build inside towny claim area than after you /t unclaim to unclaim it than builds you built started disappearing. I have tried disabling it but it seems to be not working properly. I'm not 100% If is a bug/glitch problem that causing it or not.

ScreenShot: https://gyazo.com/0ef57e64dbfee2d94c4d201458d84279

**Comment by LlmDl** [comment]
As it is explained in the install guide and the how towny works page, the config only has default settings for new worlds. You have to turn teh feature off in the world using /tw toggle revertunclaim.
