### ISSUE TITLE
Essentials Chat/Suffix

### ISSUE THREAD

**Issue by AccioAce** [LlmDl/Towny#2758]
Hello Author, 

I was wondering what do I need to remove in chat in order to show essentials chat and also when I ever I give someone suffix it shows 2 of them it shouldn't be. Have a look - https://gyazo.com/a5b2321d2e3ae8501748e8225eba3a86

**Comment by LlmDl** [comment]
Set your general Channel_format line in the chatconfig.yml

Remove the {permsuffix}
If you have {playername} set it to {modplayername}, this will pull everything that essentials uses as a DisplayName
