### ISSUE TITLE
Suggestion: Keepinventory in Towns

### ISSUE THREAD

**Issue by Sheepotastic** [LlmDl/Towny#2762]
I'm wanting to create a server that adds a sense of security when in a town, however, the only thing that can currently be done to alleviate this is to set the regeneration in a town up. I want people to still be able to kill one another, however, I want people not to get anything out of it, cutting down on the problem.
I've been looking for other ways of doing this, but I've yet to see any.

**Comment by Articdive** [comment]
Will work on this, I'm going to set a new config option to enable / disable this.
Well leave a disclaimer, stating that if you have other plugins running KeepInventory on Death, to disable this, it will be disabled on default

**Comment by LlmDl** [comment]
Part of 0.92.0.4
