### ISSUE TITLE
[Help-wanted] Putting outlaws into jails

### ISSUE THREAD

**Issue by AIphaDragon** [LlmDl/Towny#2763]
Hello,
We have faced a problem with jails.
A player founds a town and sets plot type 'jail' (/plot set jail), as well as jail spawn (/town set jail), and he wants to send one of his residents into jail. He writes /town toggle jail 1 <resident nick> to send into jail. A resident is expected to become an outlaw, and in case he is killed on town's area, he is sended to jail.

The problem is, that after /town toggle jail 1 <resident nick>, resident recieves such message 'Waiting for teleportation' (msg_town_spawn_warmup), but is not sended to jail.
So, how can we set the jail spawn and how to send resident to jail besides being a nation's enemy?

We are looking forward to your answer.

Towny version: 0.34
Spigot version: 1.11.2

**Comment by LlmDl** [comment]
0.34 isnt a towny version. Pastebin.com your server starup and link it here like the form asked you to do,

**Comment by AIphaDragon** [comment]
https://pastebin.com/vTP31Awi

**Comment by LlmDl** [comment]
Get 0.92.0.0: http://towny.palmergames.com/?p=1070 this will solve the teleporting problem.

As for residents not becoming outlaws when jailed, jailing a resident doesn't outlaw them, you have to use /t outlaw add {name}.

**Comment by AIphaDragon** [comment]
Hello.
Well, the updated version fixed an issue with teleportation, thank you.
The only problem is still with outlawed players. When they are killed inside town, the are not teleported to jail, but on their sethome point/spawn.
'is_jailing_attacking_outlaws' is set to 'true'

config: https://pastebin.com/bPLBBbhk

**Comment by LlmDl** [comment]
The player that is killing them has to have the required permission node, its all explained in the Outlaw section of the How Towny Works wikipage.

**Comment by AIphaDragon** [comment]
I was killing my twink account with OP and admin, as well as mayor account. Also, I tried to kill it from the 3rd sheriff account. The problem remains the same

**Comment by LlmDl** [comment]
pastebin.com the townyperms.yml

**Comment by AIphaDragon** [comment]
https://pastebin.com/pM3Eyxkw

**Comment by LlmDl** [comment]
Give me your server address and we'll test it out

**Comment by AIphaDragon** [comment]
Unfortunately, our server uses previous version, as we didn't translated the new one.
We test Towny server on localhost first, so the new translated version will be ready in ~3 days

**Comment by LlmDl** [comment]
Alright well if you need any further help, file a new ticket and don't skip any part of the form next time.
