### ISSUE TITLE
Suggestion: Rename Outposts and a list

### ISSUE THREAD

**Issue by Ronnie0982** [LlmDl/Towny#2766]
I hope that one day i would be easy or even able to rename your outposts, and of cause see them in a list #2690 That would be cool!

**Comment by LlmDl** [comment]
Outposts lists already show plot names for outposts. You'll always have to use the number of the outpost to travel to it, but assigning a plot name will make it clearer which outposts are which in the outpost list. Is there something else to this suggestion?

**Comment by LlmDl** [comment]
Closing until there's feedback given.

**Comment by Ronnie0982** [comment]
Okay, so you can't type a name for the outpost travel number:
/t outpost North
Normally: /t outpost 1

**Comment by LlmDl** [comment]
We wont be changing how the command works, its just how outposts are coded/saved.  This is why we made the outpost list show plot names of the outposts. So when you look up the list you have a name to reference the number from.

**Comment by Ronnie0982** [comment]
Okay then :D

**Comment by LlmDl** [comment]
I have to take it back, ArticDive has made it so that names can be used. This feature will be available in the forthcoming 0.92.0.4.
