### ISSUE TITLE
Towny bank and assistant money.

### ISSUE THREAD

**Issue by MineServidorCraft** [LlmDl/Towny#2768]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. User put some friend to assistant.
2. Assistant put to sell any plot without claiming it personally.
3. Some user buy this plot.
4. Town don't get this money, and recive the assistant that put the plot to sell..

### What is the expected output?
1. Get the money the towny.

### What is your Towny version?
I have this version: Towny Advanced 0.92.0.0 with paperspigot-1.12.2-b1274 and iConomy 5.05

### What is your spigot/craftbukkit version?
I have this version: Towny Advanced 0.92.0.0 with paperspigot-1.12.2-b1274 and iConomy 5.05

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/AyJU2sLe
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/qFTFdv04
3. Your townyperms.yml : https://pastebin.com/qCeUfYVm
4. Your log's error : Don't get any error on console.

**Comment by LlmDl** [comment]
As an assistant I went to a plot freshly claimed by the town and use '/plot fs 2'
My other non-mayor/non-assistant account went to the plot and used '/plot claim'
The plot was claimed by the 2nd account and the money for the plot was placed into the town's bank. 

Please give me better instructions on how to reproduce this bug and I will reopen the ticket.

**Comment by MineServidorCraft** [comment]
If the assistant put for sale the plot and buy it, he get the money (if he had 10k, stay with 10k). 
If some user buy the plot, money get the assistant that put on sale.

SS : https://imgur.com/a/rMbfL

**Comment by LlmDl** [comment]
https://i.imgur.com/2uMJaF1.png
The screenshot says: payasy bought tatobellic's plot for 5000.
So the plot must have been claimed by tatobellic previously. This is why, when I tested it, I used a plot that had just been claimed by the town.

**Comment by MineServidorCraft** [comment]
How claim the plot by the town (?)
Plot was claimed by me (the mayor), when i buy the plot on wild.

**Comment by LlmDl** [comment]
Mayors can use /plot claim  or /plot unclaim (I don't recall which) on player-owned land to return ownership to the town.
