### ISSUE TITLE
Mob spawning in Towns

### ISSUE THREAD

**Issue by Wolf2323** [LlmDl/Towny#2769]
I have a little problem with towny.
Mobs spawn in our towns., with mobspawn disabled. 
I want no spawning of mobs in the towns, but i dont want any mobs removed, when they walk in a town.
Its it a problem in the config or a bug?

### What is your Towny version?
0.92.0.2

### What is your spigot/craftbukkit version?
CraftBukkit version git-Spigot-5695bca-53fccdf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

 Towny config.yml: https://pastebin.com/Q1z9FTTg

**Comment by LlmDl** [comment]
Skipped form, invalid ticket. Please resubmit.
