### ISSUE TITLE
Mob spawning in Towns

### ISSUE THREAD

**Issue by Wolf2323** [LlmDl/Towny#2770]
### What steps will reproduce the problem?
1. Use my Config
2. have a Town
3. have low enough Light level

### What is the expected output?
1. No Mob spawning in Town
2. No Mob despawning in Town

### What is your Towny version?
0.92.0.2

### What is your spigot/craftbukkit version?
CraftBukkit version git-Spigot-5695bca-53fccdf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/ueZbGPUK
2. Your Towny config.yml (if using MySQL please remove password,) :https://pastebin.com/Q1z9FTTg
3. Your townyperms.yml : https://pastebin.com/aHeHMfmz
4. Your log's error : none

**Comment by LlmDl** [comment]
Can you pastebin.com you towny\data\towns\townname.txt and towny\data\worlds\worldname.txt files please. Usually this is caused by citizens being out of date but your version is MC 1.12.2 compatible.

**Comment by Wolf2323** [comment]
Problem solved:

I first tried to fix the error myself. I made the following things.

"town_mob_removal_entities: ''" changed to "town_mob_removal_entities: Monster,WaterMob,Flying,Slime,Shulker,SkeletonHorse,ZombieHorse"
and executed "/ta reload"
but the problem was still ther.
later i restarted the server and this solved it.

Conclusion the "ta reload" command does not reload this configuration
