### ISSUE TITLE
Suggestion: Gender

### ISSUE THREAD

**Issue by Johnsonk2** [LlmDl/Towny#2772]
Suggestion: Pretty straightforward, although **not by my own request**.

<img width="179" alt="title" src="https://user-images.githubusercontent.com/25190838/34623676-40a95bf8-f24a-11e7-91e8-ad432fb556f1.png">

-Gender Neutral plots. 
When it says for example 'King' <player>. I have a friend who would like this to be changed somewhat. Maybe even by selecting your gender when creating a nation? Or have those titles gender neutral in the first place.

Thanks.

**Comment by Wolf2323** [comment]
This is possible but i think it would be the best if you change this in the config file.

**Comment by LlmDl** [comment]
We won't be storing gender in the resident files. If you want to run a gender neutral server all the prefixes/suffixes are configurable in the town/nation levels.
