### ISSUE TITLE
Regeneration bug Torch(see #2743)

### ISSUE THREAD

**Issue by Wolf2323** [LlmDl/Towny#2773]
### What steps will reproduce the problem?
1. Let a creeper explode, so that the torch is dropped but not the block below
2. Break the Blocks below
3. When the Torch is regenerated a dirt block appears below it

### What is the expected output?
1. No dirt block

### What is your Towny version?
0.92.0.2

### What is your spigot/craftbukkit version?
CraftBukkit version git-Spigot-5695bca-53fccdf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by LlmDl** [comment]
Skipped form, invalid ticket, resubmit
