### ISSUE TITLE
Regeneration bug Torch

### ISSUE THREAD

**Issue by Wolf2323** [LlmDl/Towny#2774]
When a Torch regenerate a dirt block will be placed below if there is no block.

### What steps will reproduce the problem?
1. Let a creeper explode, so that the torch is dropped but not the block below
2. Break the Blocks below
3. When the Torch is regenerated a dirt block appears below it

### What is the expected output?
1. No dirt block

### What is your Towny version?
0.92.0.2

### What is your spigot/craftbukkit version?
CraftBukkit version git-Spigot-5695bca-53fccdf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/pNRDW6e9
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/C0BSzsde
3. Your townyperms.yml : https://pastebin.com/6V2Nz4a1
4. Your log's error : none

**Comment by LlmDl** [comment]
Is the torch on top of a block or attached to a side of the block? I've since done a lot of work on this feature in prep for 1.13's removal of BlockIDs, so I tested this with torches on teh sides of blocks. I don't remember testing this when the torches were on the tops of blocks.

**Comment by Wolf2323** [comment]
The Torch is on top of the block.

**Comment by LlmDl** [comment]
Are the players breaking the blocks below which did not explode for fun or something? The way the regeneration works, we arent tracking any blocks that aren't broken in the explosion. If the block is all of a sudden not there, towny makes a placeholder dirt block so the attachable block still attaches later.

**Comment by LlmDl** [comment]
You're wanting the torches to not place correctly?

**Comment by Wolf2323** [comment]
"The way the regeneration works, we arent tracking any blocks that aren't broken in the explosion. If the block is an attachable and cannot be placed without a placeholder, towny makes a placeholder dirt block so the attachable block still attaches later."

I mean that dirt block

**Comment by LlmDl** [comment]
Fixed as of 0.92.0.3
