### ISSUE TITLE
SQL ERROR

### ISSUE THREAD

**Issue by Golvore** [LlmDl/Towny#2775]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### Problem
 I can't delete tables on TOWNY_TOWNS
 And i have option delete old residents enabled
 Towny delete them from TOWNY_RESIDENTS, but does not delete them from TOWNY_TOWNS
 Then when I start the server I get errors like this: https://hastebin.com/heyuwajutu.sql

### What is your Towny version?
Towny 0.92.0.2

### What is your spigot/craftbukkit version?
Spigot 1.12.2

### Please use Pastebin.com to link the following files:

Those two backslashes  https://cdn.discordapp.com/attachments/387020787854344193/399622483231244319/unknown.png

Make the pMA page just reload

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
3. Your townyperms.yml :
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Form Skipped. Invalid Ticket. Resubmit.
