### ISSUE TITLE
[MySQL] Resident Purge causing Safe Mode

### ISSUE THREAD

**Issue by Golvore** [LlmDl/Towny#2776]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. OPTION DELETE OLD RESIDENTS enabled
2. Towny delete OLD RESIDENTS from TOWNY_RESIDENTS but no from TOWNY_TOWNS
3. And produce this error: https://hastebin.com/heyuwajutu.sql

### What is the expected output?
1. No errors
2.
3.

### What is your Towny version?
Do not say "latest".

Towny 0.92.0.2

### What is your spigot/craftbukkit version?
Do not say "latest".

Spigot 1.12.2

### MySQL Version?

Server version: 5.6.38 - MySQL Community Server (GPL)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://hastebin.com/nagozojura.sql
2. Your Towny config.yml (if using MySQL please remove password,) : https://hastebin.com/omilalutic.coffeescript
3. Your townyperms.yml :
4. Your log's error : https://hastebin.com/heyuwajutu.sql

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by Golvore** [comment]
There is no error in sample, the code simply fails and reloads the page.
Because of the bad syntax that pMA generates

**Comment by LlmDl** [comment]
Turn on your mysql logging and when it happens again (or make it happen again,) supply that section of your mysql logs.

**Comment by Naskel** [comment]
I'm experiencing a similar issue.
https://hastebin.com/aharuhanuf.sql
Basically the town is still registered in TOWNY_TOWNS but not in TOWNY_WORLDS table. I'm not sure if it happens when a player renames a town and it doesn't fully delete it in the database or if it happens when a player renames the town.

**Comment by LlmDl** [comment]
For years there's been one-off issues with mysql db's that don't affect all servers and I've just chalked it up to the mysql db used. Without logs from your mysql we can't really say whats happening.

**Comment by Naskel** [comment]
What logs specifically do you need? And how do I get them? I'd love to get this resolved as it is triggered by restarts every now and then which makes it very hard for me to setup automatic server restarts.

**Comment by LlmDl** [comment]
I need everything a standard ticket asks for, your mysql information/version and the mysql logs which you'll probably have to enable before your server will begin logging. All of this in a new ticket.

**Comment by LlmDl** [comment]
2 weeks of inactivity. Closing ticket.
