### ISSUE TITLE
Suggestion: Nation Spawn

### ISSUE THREAD

**Issue by Lenti99** [LlmDl/Towny#2779]
Hello, I got this suggestion from a player on my server and I thought that something like this would be nice so I'll just copy and paste the idea.

_"Hello there. A quick simple suggestion here, to make a nation spawn. Apart from nations helping the towns via chunks etc. I believe adding a spawn to them would be really cool. Where players from the towns within certain nations can get together to build a nation spawn. Overall a quick suggestion would be cool thanks."_

**Comment by LlmDl** [comment]
https://github.com/LlmDl/Towny/issues/1163 Duplicate
