### ISSUE TITLE
Regeneration bug Cobblestone Slab

### ISSUE THREAD

**Issue by Wolf2323** [LlmDl/Towny#2781]
When a Cobblestone Slab, placed on the top position of a block, regenerate a Stone Slab on the bottem position will be placed.

### What steps will reproduce the problem?
1. Place a Cobblestone Slab on the top of a block
2. Let a creeper explode
3. Wait for the regeneration

### What is the expected output?
1. cobblestone slab top position instead of stone slab bottem position

I not tested this with other slab types

### What is your Towny version?
0.92.0.2

### What is your spigot/craftbukkit version?
CraftBukkit version git-Spigot-5695bca-53fccdf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log : https://pastebin.com/pNRDW6e9
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/C0BSzsde
3. Your townyperms.yml : https://pastebin.com/6V2Nz4a1
4. Your log's error : none

**Comment by LlmDl** [comment]
Fixed in 0.92.0.3 which is available now. Thanks for catching these regen bugs.
