### ISSUE TITLE
Suggestion: Ability to add Friends at a Town Level

### ISSUE THREAD

**Issue by mindstormer7** [LlmDl/Towny#2785]
Pretty much just allowing mayors to allow friends to build on a town basis instead of having to allow people only on the basis of residents, allies, and outsiders.

It gets really annoying to have to allow all my allies (part of a 40 person nation) to build in my town when I just want to add one friend who already has a town as some of those people in the nation aren't too kind.

Don't really know if this would be considered a step away from the purpose of towny, but it's annoying a lot of people on my server that they have to allow so many people to build just to allow one person in a different town.

**Comment by LlmDl** [comment]
Towns don't have a Friend option like Residents do because the Resident takes up the Friend section. Most of the time a server will sell the outsider the plot they want the person to work on as an Embassy plot. Embassy plots cover single person cases fairly well.

**Comment by LlmDl** [comment]
For the time being this will not be added as there is a work around.
