### ISSUE TITLE
Explosions Regeneration

### ISSUE THREAD

**Issue by iSkeptical** [LlmDl/Towny#2786]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Tnt and all other explosions are regenerating in the world, wilderness, and town when
I specifically told it not to.
2. Copy and paste my pastebin into the config file after looking for errors.

### What is the expected output?
1. f*cking blocks regenning after having the setting disabled.

### What is your Towny version?
Do not say "latest".
0.92.0.0

### What is your spigot/craftbukkit version?
Do not say "latest".
1.12.2-R0.1-SNAPSHOT

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Config File
https://pastebin.com/TEGPrNe8

**Comment by iSkeptical** [comment]
wild_revert_on_mob_explosion:
      # Enabling this will slowly regenerate holes created in the
      # wilderness by monsters exploding.
      enabled: 'true'
      entities: Creeper,EnderCrystal,EnderDragon,Fireball,SmallFireball,LargeFireball,TNTPrimed,ExplosiveMinecart
      delay: 20s

 I believe it is this... I have set it to false and its still reverting tnt and all other explosions. I have restarted the server countless times. Its pissing me off.

**Comment by iSkeptical** [comment]
Yeah... I have checked /tw toggle and explosions are enabled and even enabled forced explosions. I am in a wild claim that has never been claimed before. I'm op so i know it isnt permission error.

**Comment by iSkeptical** [comment]
Apparently these options dont work if you add towny after already creating a world.... I had to look in Data, Worlds, and text files. 

Organization in this plugin is non existent.

**Comment by alexander-q** [comment]
Delete your towny world files, or just edit them. The config determines the default settings for a world when it is generated

**Comment by LlmDl** [comment]
I'm sorry you had a bad time. As you have found out, the "Default new world settings" section of the config is only for newly added worlds. The install guide explains how you must change worlds' data files or use the ingame /tw toggle commands to turn off reverting in worlds that were already present when Towny is installed. Hopefully you have a better time starting now.
