### ISSUE TITLE
Regeneration bug Concrete

### ISSUE THREAD

**Issue by Wolf2323** [LlmDl/Towny#2787]
### What steps will reproduce the problem?
1. Place a Concrete (not White)
2. Let a creeper explode
3. Wait for the regeneration

### What is the expected output?
1. Concrete in the previous color instead of white

### What is your Towny version?
0.92.0.2

### What is your spigot/craftbukkit version?
CraftBukkit version git-Spigot-5695bca-53fccdf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/pNRDW6e9
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/C0BSzsde
3. Your townyperms.yml : https://pastebin.com/6V2Nz4a1
4. Your log's error : none

**Comment by LlmDl** [comment]
Fixed as of 0.92.0.4 https://github.com/LlmDl/Towny/commit/3c2fe7b0b8357b5aeb4b81552739abb2b6294953
