### ISSUE TITLE
Wild_Revert_On_Mob_Explosion duplicates Shulker Boxes

### ISSUE THREAD

**Issue by BlackBeltPanda** [LlmDl/Towny#2789]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Place a Shulker Box in the wild
2. Blow it up with TNT
3. Collect the drops with hoppers
4. Shulker Boxes regenerate with their contents
5. Repeat

### What is the expected output?
1. Shulker Boxes should either not drop when blown up in the wilderness or
2. Shulker Boxes should not regenerate

### What is your Towny version?
0.91.4.10

### What is your spigot/craftbukkit version?
git-Paper-1143 (MC: 1.12)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/raw/vjJxxzxq
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/raw/8zp5mRXa
3. Your townyperms.yml : https://pastebin.com/raw/Zrc1NCcW
4. Your log's error : N/A

**Comment by LlmDl** [comment]
Fixed as of 0.92.0.4
