### ISSUE TITLE
Suggestion: Add item_use support for other boat types

### ISSUE THREAD

**Issue by KarlOfDuty** [LlmDl/Towny#2791]
SPRUCE_BOAT,BIRCH_BOAT,JUNGLE_BOAT,ACACIA_BOAT,DARK_OAK_BOAT do not seem to prevent their respective types from being placed.

**Comment by LlmDl** [comment]
Are those the item or the actual entity?

**Comment by KarlOfDuty** [comment]
I have no idea what that means. The above is what I entered into the config which I got from following the syntax of other wood items from the switch ids list, but these ones didn't work.

**Comment by LlmDl** [comment]
I'll test it out, items and the blocks/entities they represent are typically not named the same thing.

**Comment by LlmDl** [comment]
Add ,BOAT_BIRCH,BOAT_ACACIA,BOAT_DARK_OAK,BOAT_JUNGLE,BOAT,BOAT_SPRUCE to your item_use_id list, these are the actual item names of the boats which are tested against. I'll add these to the default config.
