### ISSUE TITLE
Upkeep not being taken

### ISSUE THREAD

**Issue by monochrome-blue** [LlmDl/Towny#2797]
### What steps will reproduce the problem?
1. Using paperspigot version git-paper-1310 (MC: 1.12.2)
2. Using saneconomy version 0.13.-SNAPSHOT (Using MySQL)
3. Using towny version 0.92.0.2 (Using flatfile)
4. On new day, money is not being taken from town banks.

### What is the expected output?
1. On new days, towns should take the upkeep

### What is your Towny version?
Towny version 0.92.0.2 

### What is your spigot/craftbukkit version?
paperspigot version git-paper-1310 

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/A9nFst04
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/jfcG9XZr
3. Your townyperms.yml : https://pastebin.com/WbrhUiJd
4. Your log's error : N/A, nothing happens, except this:
```
[12:00:28] [Server thread/INFO]: [com.palmergames.bukkit.towny.log] [Global Message] A new day is here!
[12:00:28] [Thread-926/INFO]: [com.palmergames.bukkit.towny.log] [Towny] Scanning for old residents...
[12:00:28] [Thread-926/INFO]: [com.palmergames.bukkit.towny.log] [Towny] Resident purge complete: 0 deleted.
```

Here's my saneeconomy config: https://pastebin.com/Gz6iC6qz , included since it was relevant. Interestingly enough, other things which require the town bank, such as buying bonuses, works properly.

**Comment by LlmDl** [comment]
you have:

```
  daily_taxes:
    # Enables taxes to be collected daily by town/nation
    # If a town can't pay it's tax then it is kicked from the nation.
    # if a resident can't pay his plot tax he loses his plot.
    # if a resident can't pay his town tax then he is kicked from the town.
    # if a town or nation fails to pay it's upkeep it is deleted.
    enabled: 'false'
```
set that to true, save the config and do /ta reload
then do /ta newday to manually fire a new day and let me know if it works.

**Comment by monochrome-blue** [comment]
Worked, thanks! Can't believe I overlooked that..
