### ISSUE TITLE
Mayor permissions doesn't appear to adhere to nodes

### ISSUE THREAD

**Issue by KingBohica** [LlmDl/Towny#2798]
We were trying to replace the towny.claimed.owntown.* line of the 'mayor' permissions in townyperms.yml with the line towny.claimed.townowned.* with the idea that Mayors could then edit land that was part of their town (for civic buildings and the like), but would be unable to edit a resident's personal plot. Unfortunately, even if we remove ALL permissions given to Mayors in that file (as well as the assistants, etc.) they are still able to open chests, break blocks, etc. in a resident's private plot. We are guessing it stems from this method: https://github.com/LlmDl/Towny/blob/master/src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java#L417

So, it would seem this ability is hard coded. If that was the intent, I guess I'm curious why Mayors are given the towny.claimed.owntown.* node, since they can do anything to any plot in the town regardless. 

### What steps will reproduce the problem?
1. Remove towny.claimed.owntown.* line of the 'mayor' permissions in townyperms.yml
2. Have a Mayor attempt to modify block or open chests in a resident's private plot
3.

### What is the expected output?
1. They Mayor should no longer be able to access private property in their town, as they no longer have permission to do so.
2.
3.

### What is your Towny version?
0.92.0.0

### What is your spigot/craftbukkit version?
Spigot 1.12.2 (01/16/2018)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
https://pastebin.com/Ryg7GEmk
2. Your Towny config.yml (if using MySQL please remove password,) :
https://pastebin.com/8bAkvz3i
3. Your townyperms.yml :
https://pastebin.com/TQAhc3ph
4. Your log's error : 
No Errors
(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
This is something that can be fixed. It was probably unintentionally left behind after the owntown node was added (I believe it was added a bit after the other two claimed nodes.

**Comment by LlmDl** [comment]
Fixed as of 0.92.0.5

**Comment by KingBohica** [comment]
"It was probably unintentionally left behind after the owntown node was added"

Yeah, it seemed like it must have been something left over to me too. Thanks for fixing it! =D
