### ISSUE TITLE
ChatControlPro - Messages to town & nation channels appear in global chat too.

### ISSUE THREAD

**Issue by Roy416** [LlmDl/Towny#2799]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Using ChatControlPro (not using it's channels). Have the Listening Priority for "FORMATTER" at the LOWEST setting. Any other setting will not show the townychat chat. 
2. When joining the town channel, or doing /tc text, it is repeated in the global chat. 

### What is the expected output?
1. Expected output is that it doesnt get repeated in the global chat. 

### What is your Towny version?
0.92.0.0

### What is your spigot/craftbukkit version?
MC 1.12.1

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/nLqFKiUH
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/nunrf0Lk
3. Your townyperms.yml : https://pastebin.com/nmRds8Cx
4. Your log's error : none

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/AtdKAuUw
7. Your channels.yml : https://pastebin.com/06RW9FTG

ChatControlPro settings.yml : https://pastebin.com/08Nt4e0B

**Comment by LlmDl** [comment]
User has since stated that this was due to WorldGuard somehow changing the chat control pro priority to high. Issue closed.
