### ISSUE TITLE
Suggestion: Make TownyChat messages configurable.

### ISSUE THREAD

**Issue by Killdore** [LlmDl/Towny#2802]
Here is an example of what I want to change: https://gyazo.com/685278873e159346dbb757e9e132ee23

**Comment by SirKillian** [comment]
I agree with this suggestions. Multiple lines should also be supported so we can do things like this:
http://prntscr.com/ic7yox
(but then of course for chat channels and not toggling off chat)

**Comment by LlmDl** [comment]
Everything is translate-able as of TC 0.52 and Towny 0.92.0.10. Can't say if the multi-line messages will happen. That could go into a new ticket and we'll see if it works.
