### ISSUE TITLE
McMMO ignores private plugin Towny

### ISSUE THREAD

**Issue by Chypik** [LlmDl/Towny#2808]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1.The plugin McMMO ignores the city's private, the plugin has active skills, as an example of "berserk", this skill gives you the right to destroy in urban private units, such as earth, gravel, sand....
2.The plugin McMMO ignores city Privat, the player can break the blocks that are restored after 2-3 seconds, that's enough let's go through the wall ...
3.The plugin McMMO ignores city Privat, the player can break blocks foliage

### What is the expected output?
Protection of the city's private, the plugin WorldGuard with this as well.

### What is your Towny version?
Towny v0.92.0.0

### What is your spigot/craftbukkit version?
1.12.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/z5fZ0RTj
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/urzb78iG
3. Your townyperms.yml :https://pastebin.com/Y8YbF8vx
4. Your log's error : -----

(optional) If this is to do with permissions, 
5. Your permissions file : -----

(optional) If this is to do with chat,
6. Your chatconfig.yml : ----
7. Your channels.yml :-----

the version of McMMO
mcMMO v1.5.09-SNAPSHOT

Made through the interpreter the first time, do not judge strictly, what you need can provide

**Comment by LlmDl** [comment]
In the config find the setting: regen_delay: 1s and set it back to 0s.
Then retest please.

**Comment by Chypik** [comment]
yeah, I realized it will not break the blocks and pass through them! Wow!

**Comment by LlmDl** [comment]
The regen_delay is very old code that was added to Towny by someone that did not develop Towny. It should be removed because it doesn't work very good.

**Comment by Chypik** [comment]
I would be very happy to change something, but I don't understand, and completely demolish and sit with the translator again and configure patience is not enough. If only in extreme cases when no other way out.

**Comment by LlmDl** [comment]
You should get your translator, I do not understand you.

**Comment by Chypik** [comment]
thank you, no problem. Protection of the city's private works. Active skills from McMMO plugin no longer breaks the integrity of the private city
