### ISSUE TITLE
Exact same issue as #2796

### ISSUE THREAD

**Issue by Cewkaurai** [LlmDl/Towny#2809]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

What steps will reproduce the problem?
running the command /t buy bonus [any number] as either normal player OR as /op

What is the expected output?
Bonus blocks added to the town chunk limit (i.e bonus blocks added), and price of blocks removed.

What is your Towny version?
v 0.91.4.11

What is your spigot/craftbukkit version?
Spigot 1.12.2-R0.1-SNAPSHOT

Your full server startup from the logs\latest.log : <there is more after the startup, but it's mainly chat, so I wiped that part> https://pastebin.com/QcRxp8ME
Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/48RB9Di8
Your townyperms.yml :https://pastebin.com/hiawAErp
Your log's error : <Command yields no messages in console, including with towny debug mode enabled>

Bit of extra info: The issue seems to completely ignore permissions, as even ops are unable to run the command and receive blocks. Currently extra towny blocks are being gained by using the /givebonus command

**Comment by LlmDl** [comment]
In the config,

  # Limits the maximum amount of bonus blocks a town can buy.
  max_purchased_blocks: '0'

You need to set that above zero.

**Comment by Cewkaurai** [comment]
would it work as -1? (as in no limit)?

**Comment by LlmDl** [comment]
Had to check the code, -1 is not an option. You'll have to set a high number.

**Comment by Cewkaurai** [comment]
I set it to 1 mil xD My server's map has the room for it xD

**Comment by LlmDl** [comment]
https://github.com/LlmDl/Towny/issues/2810 I'll it fixed up so there's error messages and what not.
