### ISSUE TITLE
BlockPlaceEvent NPE

### ISSUE THREAD

**Issue by Wolf2323** [LlmDl/Towny#2818]
### What steps will reproduce the problem?
1. not sure

### What is the expected output?
1. no exceptions

### What is your Towny version?
0.92.0.6

### What is your spigot/craftbukkit version?
CraftBukkit version git-Spigot-5695bca-53fccdf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/hdv0F5Bi
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/DkFpPi8a
3. Your townyperms.yml : https://pastebin.com/eSHYyv5i
4. Your log's error : included in 1

**Comment by LlmDl** [comment]
Your server has a town with a nation in it on that world?

**Comment by Wolf2323** [comment]
no

**Comment by LlmDl** [comment]
Fixed as of 0.92.0.7
