### ISSUE TITLE
Late Reply from my previous post 

### ISSUE THREAD

**Issue by AccioAce** [LlmDl/Towny#2820]
Hello sorry for late reply

like these message is there way to edit it. So it doesn't say (PvP) or (NoPvP). Like the messages. 

Like, edit the config files like the PvPs message parts just wondering.

https://gyazo.com/3e5875df6a1e56858201295f93675d84
https://gyazo.com/d1b3769f7b8ed7c84d02cd11b09df894

**Comment by LlmDl** [comment]
Answered in previous ticket
