### ISSUE TITLE
Have to /townychat reload to fix unknown command for chat

### ISSUE THREAD

**Issue by WalkingPixel1** [LlmDl/Towny#2821]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Once the server restarts the /tc command is unknown
2. has to /townychat reload after restarts for it to work meaning i have to manually reload it after every restart.
3.

### What is the expected output?
1. Suppose to make /tc let players talking in a town chat but doesn't let you since it gives you ''unknown command use /help''
2.
3.

### What is your Towny version?
Do not say "latest".

Towny Advanced 0.92.0.0 for Minecraft 1.11-1.12 servers

### What is your spigot/craftbukkit version?
Do not say "latest".

MC 1.12.2 Spigot.

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/FjaxY8xE
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/fp1jjkEC
3. Your townyperms.yml :  https://pastebin.com/78w2YyKN
4. Your log's error :  Cannot find an error logs

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml : https://pastebin.com/aSnUv8Cf
7. Your channels.yml : https://pastebin.com/LqurbaV3

**Comment by Wolf2323** [comment]
In your server startup you see a exception in line 2124. This is the reason why it wont work. It wont work because you have commented out the content of section worlds.
that should work https://pastebin.com/VZ2sX7Rc

**Comment by WalkingPixel1** [comment]
so what if i don't want to use towychat as my formats for global? i have multiple rank titles so i cant use townychat for global.

**Comment by LlmDl** [comment]
You mean you have players multiple ranks and each rank has a prefix? And none of those ranks are considered a primary rank?

If you don't want players to speak in TownyChat's global channel just dont give them the towny.chat.general permission node.

**Comment by WalkingPixel1** [comment]
Doesn't matter if i take the permission away it still conflicts and overrides normal chat. for exmaple about the ranks we use something like this:

[StaffRank] [Donation Rank] [FreeRank] NAME/NICK : Chat

i want it to stay like that but i have to comment it out for it to do that but then i need to manually reload it .

**Comment by LlmDl** [comment]
I guess show me a startup where you dont have a townychat exception so I know you aren't still using a broken chatconfig and we can go over what you're doing with your chat afterwards.

**Comment by WalkingPixel1** [comment]
Okay I'll send this tomorrow as I can't do that right now! Also than you

**Comment by LlmDl** [comment]
Feedback required. Please submit within 14 days.

**Comment by WalkingPixel1** [comment]
Hi sorry my account doesnt send notifications. I fixed the issue but now it seemed to randomly conflict with chatex

**Comment by LlmDl** [comment]
File a new ticket for the new trouble you're having please.
