### ISSUE TITLE
townychat incompatible with mcmmo party chat

### ISSUE THREAD

**Issue by SirKillian** [LlmDl/Towny#2827]
When you are using mcmmo party chat alongside towny chat this will cause a small minor issue. Players have to join a channel which is not the default channel before they are able to toggle mcmmo party chat. When they do toggle on party chat without joining another channel besides global. Their message will be sent to global chat and not mcmmo party chat. Please add support for mcmmo party chat.

### What steps will reproduce the problem?
1. toggle mcmmo party chat on while being in general (global) chat. (not inside town or nation chat)

### What is the expected output?
1. mcmmo party chat should also be able to be toggled while in default (global) chat

### What is your Towny version?
0.92.0.0

### What is your spigot/craftbukkit version?
PaperSpigot git-paper-1266 (1.12.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Startup log : https://hastebin.com/aseroqedop.log
2. Config.yml: https://hastebin.com/qorajayuja.yml
3. townyperms.yml : https://hastebin.com/uqeguzepeg.yml
4. Your log's error : no error was displayed

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. chatconfig.yml : https://hastebin.com/uharofocaw.yml
7. channels.yml : https://hastebin.com/nikakegini.yml

**Comment by Articdive** [comment]
Please test this without "DeluxeChat". If it works without DeluxeChat, then it is a problem with the hook DeluxeChat is making, if not, let us know!

**Comment by SirKillian** [comment]
Works without DeluxeChat. Never realized it was actually caused by this. I'm sorry for inconvenience.

**Comment by LlmDl** [comment]
No worries.
