### ISSUE TITLE
PVP on Arena plots

### ISSUE THREAD

**Issue by AIphaDragon** [LlmDl/Towny#2831]
We have got an issue, that players in their towns cannot PVP with each other on Arena plots. It only works if they have a shield in left hand. They are in the same town and even nation. So what can be the problem connected with?
We are looking forward to your answer.

Towny version: 0.91.4.11
Spigot version: 1.11.2
config.yml: https://pastebin.com/JDMnNGVX
townyperms.yml: https://pastebin.com/QxKnqMAi

**Comment by LlmDl** [comment]
Form skipped, resubmit.
