### ISSUE TITLE
Bed explode cause NullPointerException in BlockExplodeEvent

### ISSUE THREAD

**Issue by Doc94** [LlmDl/Towny#2832]
### What steps will reproduce the problem?
1. Enter to nether
2. Place a bed in world
3. Try to sleep in bed from nether
4. See the console for error

### What is your Towny version?
0.92.0.8

### What is your spigot/craftbukkit version?
Paper version git-Paper-1322 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/f0JSy6g4
4. Your log's error :  https://pastebin.com/s9rX7pkB

**Comment by LlmDl** [comment]
Do you have a towny war active when this happened?

**Comment by Doc94** [comment]
Towny war off, and is strange not in all zones of nether the Exception happens.
https://i.imgur.com/H4sDcCo.jpg

**Comment by LlmDl** [comment]
can you pastebin.com your towny\data\worlds\world-nether.txt (or whatever your nether world is called.)

**Comment by Doc94** [comment]
Here: https://pastebin.com/rvMNDMHp

**Comment by LlmDl** [comment]
And can you screenshot the /plot perm screen while in the townblock that the bed is in.

**Comment by Doc94** [comment]
i active again the "/tw toggle usingtowny" for this test. (in usingtowny desactivate not trigger the error)
Screen: https://i.imgur.com/K558CUn.jpg

**Comment by LlmDl** [comment]
Can you retest using this build: https://www.dropbox.com/s/q6t4kp5hr1u1wkp/Towny.jar?dl=0

**Comment by Doc94** [comment]
Not work.
Error: https://i.imgur.com/cTbnswl.png

**Comment by LlmDl** [comment]
Thought that might happen, try this please: https://www.dropbox.com/s/i9n9id5j0panmma/Towny2.jar?dl=0

**Comment by Doc94** [comment]
Now not trigger any error for put beds in nether and explode.

**Comment by LlmDl** [comment]
So you're saying it's fixed?

**Comment by Doc94** [comment]
I dont see another error by place and explode beds in nether.
