### ISSUE TITLE
Suggestion: Allow /t rank add command support capitalized ranks

### ISSUE THREAD

**Issue by SirKillian** [LlmDl/Towny#2833]
So i would like to have my Towny ranks have capitalized ranks. The reason why is because it looks rather bad in the "/town" menu:
http://prntscr.com/idmjqo
Please notice how "co-mayor" is not capitalized.

Once you give the ranks a capitalized letter in the townyperms.yml, this happens when you try to add ranks to players:
http://prntscr.com/idmf8u

It does not support the capital letter in the command. Hence why I'm making this suggestion.
- Thanks for considering

**Comment by LlmDl** [comment]
This has been fixed up as of 0.92.0.9.
