### ISSUE TITLE
Error access

### ISSUE THREAD

**Issue by MineServidorCraft** [LlmDl/Towny#2840]
Yesterday i don't have any problem, and now i have acces to iconomy:

15.02 20:09:17 [Server] ERROR null 15.02 20:09:17 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'money' in plugin iConomy v5.05 - plugin is disabled. 15.02 20:09:17 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[PaperSpigot-1.12.2-b1327.jar:git-Paper-1327] 15.02 20:09:17 [Server] INFO at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) ~[?:?] 15.02 20:09:17 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:677) ~[PaperSpigot-1.12.2-b1327.jar:git-Paper-1327] 15.02 20:09:17 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472) ~[PaperSpigot-1.12.2-b1327.jar:git-Paper-1327] 15.02 20:09:17 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[PaperSpigot-1.12.2-b1327.jar:git-Paper-1327] 15.02 20:09:17 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[PaperSpigot-1.12.2-b1327.jar:git-Paper-1327] 15.02 20:09:17 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[PaperSpigot-1.12.2-b1327.jar:git-Paper-1327] 15.02 20:09:17 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-1.12.2-b1327.jar:git-Paper-1327] 15.02 20:09:17 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151] 15.02 20:09:17 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151] 15.02 20:09:17 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-1.12.2-b1327.jar:git-Paper-1327] 15.02 20:09:17 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [PaperSpigot-1.12.2-b1327.jar:git-Paper-1327] 15.02 20:09:17 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [PaperSpigot-1.12.2-b1327.jar:git-Paper-1327] 15.02 20:09:17 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-1.12.2-b1327.jar:git-Paper-1327] 15.02 20:09:17 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-1.12.2-b1327.jar:git-Paper-1327] 15.02 20:09:17 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

I don't know more....

**Comment by LlmDl** [comment]
```
Cannot execute command 'money' in plugin iConomy v5.05 - plugin is disabled.
```

This ticket is not helpful. Make a new ticket and do not skip the form.

**Comment by MineServidorCraft** [comment]
I can load the plugin, when i try to do it said me that it's loaded but not.
