### ISSUE TITLE
Mayors unable to own land in their town

### ISSUE THREAD

**Issue by KingBohica** [LlmDl/Towny#2841]
With the recent fix to mayor permissions (thank you for fixing, btw) there seems to be a new issue. If a mayor doesn't have - towny.claimed.owntown.*, so that they can't mess with the private plots of residents, they also can't do anything with their own plots. The issue seems to stem from here:
https://github.com/LlmDl/Towny/blob/master/src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java#L383
The code seems to be checking for the player's relationship to the block in question. It first checks for TOWN_OWNER then checks for PLOT_OWNER.
Then there is this:
https://github.com/LlmDl/Towny/blob/master/src/com/palmergames/bukkit/towny/utils/PlayerCacheUtil.java#L453
I see you've commented out the check for TOWN_OWNER, which is good as there is no longer an automatic override if they are the mayor. However, since in the first link it is returning after TOWN_OWNER, it never check to see if they are PLOT_OWNER as well. So the case then becomes if the player owns a plot in their own town, they can't do anything on it because it doesn't see them as PLOT_OWNER. I'm not sure how flexible the code is, but I can see 1 of 2 things helping. Either make it so that on the initial check it can return multiple results. That is, they can be both TOWN_OWNER and PLOT_OWNER. Or, move the PLOT_OWNER check ahead of the TOWN_OWNER check, so that if a mayor is standing in his private residence, it checks for that first. The drawback to the 2nd option is that depending on how the code is written, a mayor might not be able to use mayor commands while in his house, but they would just have to step outside. 

### What steps will reproduce the problem?
1. Remove - towny.claimed.owntown.* from townyperms.yml (we replaced with - towny.claimed.townowned.*)
2. As mayor, claim a plot for personal use in your town.
3. Try to do anything in that plot.

### What is the expected output?
1. Mayor should be able to edit their personal plot.
2.
3.

### What is your Towny version?
0.92.0.8

### What is your spigot/craftbukkit version?
Spigot 1.12.2 (02/12/2018)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. https://pastebin.com/QWr79F88
2. https://pastebin.com/M6SE9Zck
3. https://pastebin.com/xpUWc0Gv
4. No errors

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Good catch, fixed in this new dev: http://towny.palmergames.com/dev-build-towny-advanced-0-92-0-9-1-11-2/

**Comment by KingBohica** [comment]
Awesome! Thanks again for being on top of things! =D
