### ISSUE TITLE
[Bug] Negative Perms with Permission Plugin

### ISSUE THREAD

**Issue by Golvore** [LlmDl/Towny#2842]
Basically the denied permissions in Townyperms.yml do not work when a permissions plugin is installed (PEX, LuckPerms). I tried to refuse to build with tnt in wilderness, it does not work when there is a permissions plugin installed, but it works when there is not.

 Sorry for my bad english, i'm spanish.

### What steps will reproduce the problem?
Install a permission plugin (PEX, LuckPerms)

### What is the expected output?
Being able to deny permissions through TownyPerms.

### What is your Towny version?
Towny 0.92.0.9

### What is your spigot/craftbukkit version?
Spigot 1.12.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/jaBr4n8h
2. Your Towny config.yml (if using MySQL please remove password,): https://pastebin.com/WjU8KLjS
3. Your townyperms.yml : https://pastebin.com/C1ESsmXf
4. Your log's error: No errors

(optional) If this is to do with permissions, 
5. Your permissions file : https://pastebin.com/rqrRpbb7

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
I'm giving you another try at this because of the language barrier. Normally I would just close the ticket and tell you to resubmit without skipping the form. You skipped all of these:

1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) :
4. Your log's error :
5. Your permission file:

**Comment by Golvore** [comment]
Added

**Comment by LlmDl** [comment]
In the LP config have you tried setting: use-vault-server: true ?

**Comment by LlmDl** [comment]
I still cannot see the permissions you've given in luckperms.

**Comment by Golvore** [comment]
I don't have perms on LuckPerms, is one test server.

**Comment by LlmDl** [comment]
Your sentence doesn't make sense. Please try again. Please answer whether you've tried setting use-vault-server: true in your LP config.

**Comment by Golvore** [comment]
DB: https://pastebin.com/j7T63gDj

**Comment by Golvore** [comment]
I will do it.

**Comment by LlmDl** [comment]
The DB you linked wasn't helpful.

**Comment by Golvore** [comment]
I'm going to use the option you told me

**Comment by Golvore** [comment]
Con't works :(

**Comment by LlmDl** [comment]
Remove luckperms and tell me if it works.

**Comment by Golvore** [comment]
I mentioned in the report that it worked without LuckPerms, but I will try again.

**Comment by Golvore** [comment]
Yes, it works without LuckPerms.

**Comment by LlmDl** [comment]
Users can build in teh wild with all blocks except TNT ?

**Comment by Golvore** [comment]
Correct.

**Comment by LlmDl** [comment]
I'd guess that its something you've configured improperly in LuckPerms. You still haven't shown me what permissions the person testing this has in LP.

**Comment by Golvore** [comment]
I don't have perms.

**Comment by Golvore** [comment]
And the config of LuckPerms is default

**Comment by Golvore** [comment]
I do not know if you remember, but I had the same problem with PermissionsEx.

**Comment by Golvore** [comment]
Do you have a test server where you can test what I say? If you do not have one, I can give you mine.

**Comment by LlmDl** [comment]
I just ran a test server and saw the same thing happen. I did some troubleshooting and set the  use-vault-server: true and then apply-wildcards: false and it works just fine.
