### ISSUE TITLE
TownyChat lacks Towny for automated building

### ISSUE THREAD

**Issue by Androkai** [LlmDl/Towny#2848]
TownyChat's [build.xml](https://github.com/LlmDl/TownyChat/blob/master/build.xml) references http://palmergames.com/file-repo/libs/Towny.jar for the Towny dependency which isn't available under this url.

**Comment by LlmDl** [comment]
Usually a person would already have Towny.jar in their local libs folder so it would not have to look to the file-repo. I've added the jar to the repo for those who haven't built Towny first.
