### ISSUE TITLE
Problem with jails

### ISSUE THREAD

**Issue by AIphaDragon** [LlmDl/Towny#2849]
Hello,
We have noticed an issue with town jails. The problem is, that in case a jail is a 1 block high platform and player tries to destroy a block under him, so he falls down and is able to escape the jail.
Here is a video, where it's visible: https://www.youtube.com/watch?v=_vWaErODwjg&t=1s

So, how could we solve this problem?
We are looking forward to your answer.

Server start: https://pastebin.com/4aVs2GCV
Towny version: 0.92.0.9
config: https://pastebin.com/GiUNSzHg
Townyperms: https://pastebin.com/Gxs0CJDf

**Comment by LlmDl** [comment]
That is caused by the client lagging into the floor. They still need to escape the floor and run into the wilderness to be considered free from the Jail. Make your jails with a double-thick floor, there's nothing Towny can do to stop what is happening here.
