### ISSUE TITLE
Unprotected entity, flame.

### ISSUE THREAD

**Issue by AIphaDragon** [LlmDl/Towny#2850]
Hello,
We have faced another problem. On chunks, where outsiders cannot switch or use items, they can use wooden buttons and distinguish fire, as well as destroy end crystalls.
Here is a video: https://www.youtube.com/watch?v=_vWaErODwjg&t=1s

So, how could we solve this problem?
We are looking forward to your answer.

Server start: https://pastebin.com/4aVs2GCV
Towny version: 0.92.0.9
config: https://pastebin.com/GiUNSzHg
Townyperms: https://pastebin.com/Gxs0CJDf

**Comment by LlmDl** [comment]
Wood buttons are not in the switch list by default. Same with wood pressure plates. This is so that outsiders are able to use some redstone devices without having to give outsiders full switch perms on plots.

I can look into the fire/ender crystal thing.

**Comment by LlmDl** [comment]
Fixed ender crystals. Cannot do anything about the flame because there's no event for it see the spigot ticket:
https://hub.spigotmc.org/jira/browse/SPIGOT-2181

**Comment by AIphaDragon** [comment]
Thank you for ender crystals' fix.
But what about wooden buttons and wooden plates? Does it mean, that players should not place them in their towns? Or could it be fixed in some way?

**Comment by LlmDl** [comment]
They can use stone buttons/plates. Or you can add those wooden buttons and plates to the switch_id list.
