### ISSUE TITLE
Outlaws are not put into jail being killed in Town

### ISSUE THREAD

**Issue by AIphaDragon** [LlmDl/Towny#2852]
Hello,
We have found a problem, when a player, being labeled as an outlaw and killed in Town is teleported to spawn or bed point, instead of jail point. When he goes out of Spawn Town, he "escapes" the jail.
Here is a video: https://www.youtube.com/watch?v=C0S3HDzBPrY

So, how could we solve this problem?
We are looking forward to your answer.

Server start: https://pastebin.com/4aVs2GCV
Towny version: 0.92.0.9
config: https://pastebin.com/GiUNSzHg
Townyperms: https://pastebin.com/Gxs0CJDf

**Comment by LlmDl** [comment]
I need to know what townyperms rank the player who killed the outlaw is.

**Comment by AIphaDragon** [comment]
The outlaw was killed by town mayor

**Comment by LlmDl** [comment]
The config says:

```
  #If true attacking players who are considered an outlaw, that are killed inside town land will be placed into the defending town's jail if it exists.
  #Requires town_respawn to be true in order to work.
  is_jailing_attacking_outlaws: 'true'
```
and you have:   
```
town_respawn: 'false'
```

**Comment by AIphaDragon** [comment]
Yes, we have changed, so now it works good. Thank you for your help
