### ISSUE TITLE
Towny Glitch - Deleted Towns & Frozen Players

### ISSUE THREAD

**Issue by LoociM00** [LlmDl/Towny#2853]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
I'm not entirely sure what caused the problem, I edited the English file to change one of the messages and it started glitching. I reverted the config file and it still bugged out.

### What is the expected output?
For players to be able to move around freely and use towny as they were before, except with the correct message displaying when they enter a specific plot.

### What is your Towny version?
Do not say "latest".
0.91.4.0

### What is your spigot/craftbukkit version?
Do not say "latest".
Spigot 65a0347-a552117 (MC 1.11.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log: https://pastebin.com/2X8ajJ5p
2. Your Towny config.yml (if using MySQL please remove password,):  https://pastebin.com/9gsXkFJX
3. Your townyperms.yml : https://pastebin.com/UiRkriBg
4. Your log's error : 

`[13:31:58] [Server thread/INFO]: [Towny] Enabling Towny v0.91.4.0
[13:31:58] [Server thread/INFO]: ====================      Towny      ========================
[13:31:58] [Server thread/INFO]: [Towny] Database: [Load] flatfile [Save] flatfile
[13:31:58] [Server thread/WARN]: [Towny] Error: Loading Error: Exception while reading world file plugins/Towny/data/worlds/PlotsMap.txt
[13:31:58] [Server thread/INFO]: [Towny] Loading Error: Could not read world data 'PlotsMap'.
[13:31:58] [Server thread/INFO]: [Towny] Error: Failed to load!
[13:31:58] [Server thread/INFO]: =============================================================
[13:31:58] [Server thread/INFO]: [WARNING] - ***** SAFE MODE ***** 0.91.4.0
[13:31:58] [Server thread/INFO]: =============================================================`

(optional) If this is to do with permissions, 
5. Your permissions file : N/A

(optional) If this is to do with chat,
6. Your chatconfig.yml : N/A
7. Your channels.yml : N/A

Extras:
I've tried reverting from the backup files, editing the file from other files but nothing works unless I remove the towns from the world, but that doesn't fix my problems. If players try to move, they are frozen in place - any commands that move players do not work.

**Comment by LoociM00** [comment]
I'll attach the PlotsMap.txt here as well.
https://pastebin.com/3j4Fa1rd

**Comment by LlmDl** [comment]
https://code.google.com/archive/a/eclipselabs.org/p/towny/wikis/Troubleshooting.wiki#Towny_locked_in_safe_mode

See the section about fixing world file corruption and the town list being the culprit.

This was not caused by editing the language file.
